### ISSUE TITLE
Should we be using .Rmd or .md files?

### ISSUE THREAD

**Issue by aammd** [swcarpentry/r-novice-gapminder#10]
Just noticed that all the files are .md and .html -- should we be using .Rmd instead?

**Comment by hdashnow** [comment]
Does GitHub automatically render .Rmd to html for viewing?

**Comment by aammd** [comment]
No, but I believe the project Makefile knits the .Rmd into  the md and .html files

**Comment by hdashnow** [comment]
- Con: .Rmd would need to commit html as well. Might set the bar a little harder for new material contributors.
- Pro: .Rmd would make it natural to check all the code runs etc.

Other pros/cons?

**Comment by karawoo** [comment]
I'd vote .Rmd to make it easier to include code output, plots, etc. in the lesson materials (well, easier for those who know Rmarkdown...). This would be consistent with r-novice-inflammation, where contributors make changes to the .Rmd files and the maintainers update the .md and .html files.

**Comment by hdashnow** [comment]
I'm happy to switch to .Rmd, as long as the workflow is well documented for new users. Maybe with some links to useful resources.

**Comment by karawoo** [comment]
I guess the biggest con is that it will be a big pain to have to create all the .Rmd files to correspond with the existing .md files, unless the .md files were originally generated from .Rmd and the source files are lying around somewhere...

**Comment by hdashnow** [comment]
@sritchie73 do you have any old source .Rmd?

**Comment by sritchie73** [comment]
No, unfortunately I edited the .md files directly because I was unfamiliar with the process. 

I think the conversion from .md to .Rmd should be relatively straightforward though?

**Comment by sritchie73** [comment]
Also I think we as a community had a discussion several months ago and decided we should be using R markdown. At least that's what the official lesson template says: https://github.com/swcarpentry/lesson-example/blob/gh-pages/LAYOUT.md#writing-lessons-with-r-markdown

**Comment by karawoo** [comment]
Converting from .md to .Rmd won't be hard but it will probably be time consuming. If we're going to convert them I'd advocate for splitting that work up between several volunteers. We'll also need to update the contributing guide to reflect the change.

**Comment by aammd** [comment]
@karawoo I agree. Perhaps we should open issues corresponding to each lesson and assign people!

**Comment by aammd** [comment]
Just so that we are all on the same page

.Rmd ---> Rmarkdown (code + text, compiled with knitr into plain markdown and then into html)
.md -----> markdown (plain markdown, later turned into html)

**Comment by karawoo** [comment]
Assigning people to issues makes sense to me. I can volunteer to convert a couple lessons.

**Comment by sritchie73** [comment]
I'm happy to volunteer as well. 

Also worth noting that some of the lessons (at least when I last looked) relied on data structures loaded into the workspace in earlier lessons. For example `gapminder` is used throughout, but read in early on in the workshop.

**Comment by hdashnow** [comment]
I suggest we include a note with the code for importing the data in all
lessons that rely on it.

On Fri, May 1, 2015 at 9:51 AM, Scott Ritchie <notifications@github.com>
wrote:

> I'm happy to volunteer as well.
>
> Also worth noting that some of the lessons (at least when I last looked)
> relied on data structures loaded into the workspace in earlier lessons. For
> example gapminder is used throughout, but read in early on in the
> workshop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/r-novice-gapminder/issues/10#issuecomment-98003871>
> .
>



-- 
Harriet Dashnow
BSc, BA, MSc (Bioinformatics), PhD candidate
au.linkedin.com/in/hdashnow

**Comment by sritchie73** [comment]
I don't think the Rmarkdown will compile properly without that reading in the data at the top of each lesson?

**Comment by aammd** [comment]
@sritchie73 that's correct. We want this behaviour, because it means that an instructor reading one lesson has all the information needed.

**Comment by naupaka** [comment]
Given the interest in having people work on this for the [Mozilla Science sprint soon](https://etherpad.mozilla.org/sciencelab-2015globalsprint) (ca. line 191 on the etherpad), I propose we add issues for each of the lessons that include the notes above (e.g. load data) and ask people to convert the md files to Rmd. This won't be too hard, but will take time, as others have said, so might be a perfect thing to have people hack on for the sprint. Thoughts @aammd @sritchie73 @hdashnow @karawoo ?

**Comment by hdashnow** [comment]
Great idea!

**Comment by sritchie73** [comment]
Sounds good @naupaka. Does it make sense to create a single issue and do the conversion first thing? The mozsprint kicks off in Australia first, so I could push to convert them all first thing in the morning before everyone else gets started.

**Comment by aammd** [comment]
@naupaka that's a great idea!  I suggest we have a discussion about the structure of the lessons first, before someone devotes time to making a .Rmd of a lesson that we don't think we'll actually keep.

**Comment by gvwilson** [comment]
+1 to that. I strongly suggest someone create `outline.md` temporarily, 
which will hold a bullet-point outline of the lessons - it's much easier 
to iterate on that via PRs than to discuss major reorg of a lesson by email.

**Comment by karawoo** [comment]
I'm up for helping with this but probably can't do it during the actual sprint as I'll be just getting back to the office after a few weeks away. I'll keep an eye on the issues and help out when I can.

**Comment by hdashnow** [comment]
It looks like we can close this once #24 is merged.

**Comment by naupaka** [comment]
Closed via PR #24
