### ISSUE TITLE
08-plot-ggplot2 Switch axis for life exp. & GDP?

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#100]
The examples show GDP on the y-axis and life expectancy on the x-axis.  As many discussions (elsewhere) concern the utility of GDP in _predicting_ life expectancy, should GDP instead be on the x-axis?

**Comment by jcoliver** [comment]
BTW, what do I win for opening the 100th issue?

**Comment by naupaka** [comment]
I agree. Submit PR with fix? And for 100th issue: 👍  😄

**Comment by naupaka** [comment]
Closed by #117
