### ISSUE TITLE
make problems:  .html not produced by 'make preview'

### ISSUE THREAD

**Issue by carpenterbennet** [swcarpentry/r-novice-gapminder#102]
The original issue was about 'make check' failing.  That got filed as an issue in the lesson template repo at https://github.com/swcarpentry/lesson-template/issues/299

I was unable to get 'make preview' to work.  I created a new file with a .Rmd extension, and ran 'make preview' and it did not create a corresponding .html file.  I removed all the .html files, even.  R is in my path.

I am doing this on a fresh installation of El Capitan, with freshly installed R, RStudio, Pandoc, Anaconda[23], etc.  All of the necessary R libraries are installed, and if I manually knit the new .Rmd file, it produces the proper output.

I may not be able to get to this this evening, but I'll try it again, just to be sure it was not an oversight on my part.

**Comment by naupaka** [comment]
Try modifying one of the existing Rmd lesson files and then running `make preview`. The makefile (on line 5) looks for Rmd files that match the pattern used by the lessons: `SRC_RMD = $(wildcard ??-*.Rmd)`. So, just any name won't be rendered.

**Comment by carpenterbennet** [comment]
I am pretty sure that was the first thing I tried.  No dice.  That's when I thought the more extreme version -- creating a brand new 07a_functions.Rmd file -- was in order.  The original error message did notice I hadn't installed knitr.  I did so and progressed to the 'no op' situation.

Before you spend too much time on this, let me poke at it for a day or two, and if I can't figure out what's wrong, I can at least give you accurate diagnostics.

**Comment by naupaka** [comment]
It would have to be `07-functions2.Rmd` to be picked up by the script.

**Comment by carpenterbennet** [comment]
If I delete all the .html files, those should rebuild, correct?  I'll fix
my new file name and retry with that.


On Tue, Apr 19, 2016 at 3:17 PM, Naupaka Zimmerman <notifications@github.com

**Comment by naupaka** [comment]
Right; if you delete all lesson `.md` and `.html` files and they should rebuild with `make preview` from the Rmd sources.

**Comment by justbennet** [comment]
Between having the `a` in the new section name and maybe not having deleted the `.md` files, `make preview` now works a treat!  Thanks @naupaka 

Please close this issue.
