### ISSUE TITLE
Link githubrepo page to rendered html

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/r-novice-gapminder#105]
At the top of https://github.com/swcarpentry/r-novice-gapminder, please add a link to http://swcarpentry.github.io/r-novice-gapminder/index.html so people know where to find the rendered version. I can't put in a PR for that, only those with commit access can add it (right after where it says 'Introduction to R for non-programmers using gapminder data.')

**Comment by naupaka** [comment]
Good idea. There's currently a link to the rendered content at the bottom of the README. I can't add the link at the top of the page though - perhaps @gvwilson can do that?

**Comment by gvwilson** [comment]
Done.
