### ISSUE TITLE
Unnumbered challenge in 06-data-subsetting

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/r-novice-gapminder#106]
06-data-subsetting has an unnumbered challenge between challenge 1 and 2. This challenge also lacks a solution at the bottom of the page.

**Comment by naupaka** [comment]
Good catch. I will add this to the milestone for the upcoming Bug BBQ.

**Comment by tomwright01** [comment]
The unnumbered challenge seems to have been fixed by commit f89abd5f87b3cdd0b656cd2ba32bc529812d9c75

**Comment by tomwright01** [comment]
Solution added by PR #134 
Thanks
