### ISSUE TITLE
08-plot-ggplot2 Subset data before creating multi-panel figure?

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#118]
Subsetting the data to countries with names starting with the letter "A" might provide a more visually appealing demonstration of the multi-panel figure, while preserving the utility of by-continent coloring (all five continents/colors are represented in the set of seven "A"-countries).

**Comment by naupaka** [comment]
I agree, good suggestion.

**Comment by naupaka** [comment]
Closed via #124
