### ISSUE TITLE
`if` syntax is used in lesson 07-functions before lesson 10-control-flow

### ISSUE THREAD

**Issue by stevenhwu** [swcarpentry/r-novice-gapminder#120]
Based on the current order, lesson `07-functions` will be covered before `10-control-flow`.
However, in the second half of the lesson, the `if` statement is used in the function, which is not properly introduced until lesson `10-control-flow`
```
calcGDP <- function(dat, year=NULL, country=NULL) {
  if(!is.null(year)) {
    dat <- dat[dat$year %in% year, ]
  }
  ...
```
It might make more sense to switch the order around. There are several ways to get around this, here are just a few of them;
- Design a different example without `if`
- Switch lesson 7 and 10
- Introduce `if`, follow by functions, then `for`
- Revisit functions after `if` and `for`.

**Comment by naupaka** [comment]
I generally teach control flow before functions, so perhaps switching 7 and 10 would work well. Someone would have to go through them carefully to make sure there aren't any other content dependencies that are broken by changing the order.

**Comment by marcsze** [comment]
Umich is taking a shot at this issue

**Comment by marcsze** [comment]
There is a conflict with 1issue #129 but the extra recommended changes made in issue #137 should help resolve some/most of these

**Comment by tomwright01** [comment]
I think this is now resolved. Thanks @marcsze
