### ISSUE TITLE
11-writing-data html version is empty 

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/r-novice-gapminder#121]
http://swcarpentry.github.io/r-novice-gapminder/11-writing-data.html shows no lesson content. https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/11-writing-data.md is empty but seems to have content.

**Comment by naupaka** [comment]
Good catch @lexnederbragt. Not sure why that happened. I'll take a look and see if I can't fix that later this week. Perhaps some glitch in the knitting process...

**Comment by mickley** [comment]
11-writing-data.Rmd seems to compile fine and generate well-formed md and html for me.  So it seems to be the build process.

**Comment by naupaka** [comment]
This is fixed by commit 5d39fdfe6f3. Closing.
