### ISSUE TITLE
No challenge solutions in lesson 7

### ISSUE THREAD

**Issue by noracmitchell** [swcarpentry/r-novice-gapminder#135]
There are no challenge solutions in workflow control lesson 10 (in addition to a small typo in Challenge 4 that should refer back to Challenge 3, not itself).

**Comment by noracmitchell** [comment]
These challenges seem very challenging for this level. Has anyone tried to go through these during a lesson? Especially challenges 3-5. Perhaps a simpler for loop challenge to start with would be better, especially since they don't use the gapminder dataset until the challenges. Spacing the challenges more throughout the lesson might also help. Further challenges could build on that (nesting, etc.)

**Comment by gvdr** [comment]
Is anybody else taking charge of this? Otherwise, I'll do it.

**Comment by naupaka** [comment]
NB: Flow control is now lesson 7 instead of 10.

**Comment by gvwilson** [comment]
@gvdr any progress?

**Comment by gvdr** [comment]
I'm sorry, I've been busy with relatives and such things, I'll look into
it soon.

Greg Wilson wrote:
> @gvdr any progress?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/swcarpentry/r-novice-gapminder/issues/135#issuecomment-236981747


-- 
Giulio Valentino Dalla Riva

Beaty Biodiversity Reseach Centre
University of British Columbia
Vancouver, Canada

**Comment by naupaka** [comment]
Closed by #209
