### ISSUE TITLE
04-data-structures-part1 Data.frames as mixed lists?

### ISSUE THREAD

**Issue by gvdr** [swcarpentry/r-novice-gapminder#139]
I find line 313 a bit confusing and potentially wrong.

> We see that data.frames look like lists 'under the hood' - this is because a data.frame is really a list of vectors and factors, as they have to be - in order to hold those columns that are a mix of vectors and factors, the data.frame needs something a bit more flexible than a vector to put all the columns together into a familiar table.

I think that the list in a data.frame are not of mixed type. Am I wrong here?

If not I'll propose a PR with a less problematic (imho) wording.

**Comment by tomwright01** [comment]
With hindsight, I agree this wording could be confusing.

**Comment by gvdr** [comment]
I've proposed a pull request for this. Not sure it's much better ;-)

**Comment by aammd** [comment]
i do believe this was closed in #151 ?
