### ISSUE TITLE
Integrate gapminder data into 15-knitr lesson

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#164]
The addition of `knitr` into the lessons is great.  In the long term, it might be nice to use the `gapminder` data in the lesson, to maintain continuity with the rest of the lessons.

**Comment by tomwright01** [comment]
Completely agree. Currently the lessons references mtcars and gapminder. A
trivial fix is to change the initial reference to mtcars, I can submit a PR
for that now.

**Comment by naupaka** [comment]
Closing this because the knitr lesson does in fact mention gapminder (albeit not extensively) and a challenge asks learners to make a plot from that data set.
