### ISSUE TITLE
Fix times for lesson episodes

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-gapminder#167]
The teaching and exercise times for each episode need to be filled in.

**Comment by naupaka** [comment]
I am not sure what these times should be unfortunately... They vary so much from workshop to workshop, depending on audience experience and etc. How should these be estimated?

**Comment by gvwilson** [comment]
Rough guesses :-)

**Comment by naupaka** [comment]
Just submitted a PR for this against your fork @gvwilson

**Comment by naupaka** [comment]
Closing this, although I imagine it would be good to keep updating those times in the future as we get a better sense for them in different contexts and with different audiences.
