### ISSUE TITLE
Getting Gapminder dataset

### ISSUE THREAD

**Issue by cwmohr** [swcarpentry/r-novice-gapminder#172]
Currently there are two options presented for loading in the gapminder dataset in session 5 data structures part 2 [https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes/05-data-structures-part2.md]:

The use of the `read.csv()` function:
`gapminder <- read.csv("data/gapminder-FiveYearData.csv")`,

in which case you have to have the file pre-downloaded to that folder. The file is available at https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv . However for MacOSX users, simply adding the link into the address bar results sometimes in the file opening in the browser (not sure why this happens at times). It is possible to save the file from the browser via the File menu clicking "save as", but this seems to be an unnecessary amount of hassel for the students.

Alternative two is a "direct read in":
`gapminder <- read.csv("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv")`

This works perfectly (given that the link still exists). However, in other scenarios where the data file or files are massive. Re-running the R-script results in unnecessary re-downloading from site.

**Solution:**
One option that might be better, is to teach the students the `download.file()` function:
`download.file("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv", "data/gapminder-FiveYearData.csv")` 

 By using this function the file can be downloaded to the project folder. Once there the file can be read in using the `read.csv()` function. By this method the student have learned both the `download.file()` and the `read.csv()` function.

**Comment by cwmohr** [comment]
By the way the link to https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv is down. See #173

**Comment by tomwright01** [comment]
I think the link should be:
https://swcarpentry.github.io/r-novice-gapminder/_episodes_rmd/data/gapminder-FiveYearData.csv

However, I can't make this work either.

I think I like the `download.file()` option, however we need to solve where to store data files.

**Comment by gvwilson** [comment]
OK, I think we need @fmichonneau on this one:
1.  The source of the data is in `_episodes_rmd/data/*.csv` so that the R code in `_episodes_rmd` can read it using `data/whatever.csv` (the "natural" path).
2.  But `_episodes_rmd/*` isn't copied into `_site` when Jekyll builds the web version of the material.
3.  And there's no way for us to force that with an extra command in the Makefile, because GitHub only runs Jekyll plain and simple.

**Comment by tomwright01** [comment]
I'm thinking we should have a central repo to store data files from all lessons. This would facilitate re-using data files in different lessons as well as making it easier to modify existing lessons to use new data.

**Comment by cwmohr** [comment]
For R there is also the possibility of getting the gapminder data via CRAN, by typing`install.packages("gapminder")` in R. However should this file be updated or removed from CRAN then it could be a problem for the lessons.

**Comment by tomwright01** [comment]
I did a little research into the gapminder data used in the lesson and I think it's actually a merge and subset of several original data sources. 
I don't really like the idea of sourcing external data for lessons. As @cwmohr points out there is too much opportunity for changes beyond our control.

**Comment by fmichonneau** [comment]
I tried to implement something to make the content of the data/ folder available from the main website but it was more complicated than what we had time for. I was exploring how to copy the content of _episodes_rmd/data into _episodes/data but that leads to duplicated copies, potential conflicts, and confusion to lesson contributors.

It is not as convenient but I think the easiest for now is simply to link to the file using the GitHub URL i.e. https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder-FiveYearData.csv

**Comment by naupaka** [comment]
For workshops I generally just give participants a dropbox URL to download the gapminder.csv file before we get started with it. It's a short URL, so easy to write on a whiteboard or post to the etherpad for people to download. Seems to work well. I think it's a key thing to teach people (at least in biology) since most of them will be working with their own data files from spreadsheets.

Shouldn't be an issue for building the lessons since they are knitted locally using the makefile. All of that said, the direct read-in from the URL should definitely have its link updated with the URL @fmichonneau gave in his comment.

**Comment by gvwilson** [comment]
Any resolution?

**Comment by naupaka** [comment]
Not that I know of, but I vote for @fmichonneau's solution with the GitHub URL. Seems most straightforward and doesn't require another external dependency.

**Comment by gvwilson** [comment]
:+1: to a GitHub URL - please use `{{site.github.repository_url}}/whatever/whatever` in the source.

**Comment by ashander** [comment]
Should the dataset be downloaded in `setup.md`? If it's not, the [reference to the data path during the episode 01](https://github.com/swcarpentry/r-novice-gapminder/blame/gh-pages/_episodes_rmd/01-rstudio-intro.Rmd#L39) is confusing.

Perhaps the simplest thing is to change the latter to a link to gapminder website?

**Comment by naupaka** [comment]
@ashander that seems like an easy fix

**Comment by ashander** [comment]
Note that #204 is proposing a fix for this (although not the small issue I mention above, I'll put in a quick PR for that now)

**Comment by naupaka** [comment]
This issue has been resolved by #204 and #205
