### ISSUE TITLE
bad link (gapminder)

### ISSUE THREAD

**Issue by cwmohr** [swcarpentry/r-novice-gapminder#173]
In section 5 data structures part 2 [http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/], the gapminder file hyperlink is down: https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv

The file is however accessible via https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv

However this needs to updated on the webpage.

**Comment by lmsimp** [comment]
Hi @cwmohr, @gvwilson I have addressed in the above issue in this [pull request](https://github.com/swcarpentry/r-novice-gapminder/pull/204) as part of my SWC checkout part I and also issue #187 related to the above.

**Comment by naupaka** [comment]
Closed by #204
