### ISSUE TITLE
Use ggplot example in the dplyr lesson?

### ISSUE THREAD

**Issue by davemcg** [swcarpentry/r-novice-gapminder#174]
#85  (Instructor training)

I thought it would be a nice touch to use dplyr to demonstrate how a plot made in the ggplot lesson earlier can be done with %>%, removing several intermediate files.

In the ggplot lesson, near the end, facets are used to break the GDP by country (just starting with A and Z).

```
#http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/
library("ggplot2")
library("gapminder")
starts.with <- substr(gapminder$country, start = 1, stop = 1)
az.countries <- gapminder[starts.with %in% c("A", "Z"), ]
ggplot(data = az.countries, aes(x = year, y = lifeExp, color=continent)) +
  geom_line() + facet_wrap( ~ country)
```

This can be done without creating 'starts.with' and 'az.countries' with dplyr's filter function. I was thinking this small section could be added to the dplyr lesson

```
# http://swcarpentry.github.io/r-novice-gapminder/13-dplyr/
# https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes_rmd/13-dplyr.Rmd
gapminder %>% 
   filter(grepl('^A|^Z',country)) %>%  
   ggplot(aes(x = year, y = lifeExp, color=continent)) + 
   geom_line() + 
   facet_wrap( ~ country)
```

**Comment by lazappi** [comment]
I agree that this makes sense and would help to bring together some parts of the course.

I would make a small change and use the `mutate` function instead of `grepl`:

```{r}
gapminder %>% 
   mutate(startsWith = substr(country, start = 1, stop = 1)) %>% 
   filter(startsWith %in% c("A", "Z")) %>%
   ggplot(aes(x = year, y = lifeExp, color=continent)) + 
   geom_line() + 
   facet_wrap( ~ country)
```

I think that this better matches the original method and is more "dplyry". Also I'm not sure if the students have been introduced to `grep` before now?

I would be happy to make a pull request if people agree this is a good idea.

**Comment by naupaka** [comment]
So the idea would be to add this as an example to the end of the dplyr lesson? I agree that the version @lazappi proposed is more consistent with what we cover - much easier to not have to explain `grepl()` and regular expressions for this example.

Could also skip the extra mutate step to simplify even further:

```r
gapminder %>% 
	filter(substr(country, start = 1, stop = 1) %in% c("A", "Z")) %>%
	ggplot(aes(x = year, y = lifeExp, color = continent)) + 
	geom_line() + 
	facet_wrap( ~ country)
```

**Comment by lazappi** [comment]
Good catch, I hadn't thought of that. I saw it just as a note at the end of the lesson that they instructor could point out if they had time, rather than a new section or exercise.
