### ISSUE TITLE
Add screenshot at Introduction to RStudio

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#177]
> Basic layout
> 
> When you first open RStudio, you will be greeted by three panels:
> - The interactive R console (entire left)
> - Environment/History (tabbed in upper right)
> - Files/Plots/Packages/Help/Viewer (tabbed in lower right)
> 
> Once you open files, such as R scripts, an editor panel will also open in the top left.

can be improved by add some screenshots.

**Comment by naupaka** [comment]
Closed by #235
