### ISSUE TITLE
Update topic timings

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#19]
The header material for each topic file includes the expected amount of time each lesson should take. Most of them are the default: 15 minutes. @hdashnow can you update each of the topics with realistic times? You've had to most experience running this lesson material.

**Comment by hdashnow** [comment]
Sure thing. 

The timings I would put up are the times that we realistically do the lessons in. For some cases we deliberately don't do the whole lesson. In particular, we only direct students to do the first couple of challenges and then let the ones how are ahead continue on to try the rest by themselves. 

Is there an easy way to put comments in there to explain this? Or should I try to estimate how long it would take if we actually did the whole thing?

**Comment by sritchie73** [comment]
It might be good to explicitly explain for new instructors, but apparently it's standard practice to skip sections and challenges in the other Software Carpentry lessons (I wasn't aware of this the first time I ran the shell lessons, which is why it took 5 hours, cc: @gvwilson ).

**Comment by hdashnow** [comment]
Here are my very rough estimates. You'll notice that there is over 8 hours on content here (which is fairly consistent with how much we usually cover in reality). I think I'd better open an issue about that!

| Lesson        | Approx. Time (mins) |
|------------------------------|----|
| 01-rstudio-intro.Rmd         | 45 |
| 02-project-intro.Rmd         | 30 |
| 03-seeking-help.Rmd          | 15 |
| 04-data-structures-part1.Rmd | 45 |
| 05-data-structures-part2.Rmd | 45 |
| 06-data-subsetting.Rmd       | 45 |
| 07-functions.Rmd             | 45 |
| 08-plot-ggplot2.Rmd          | 70 |
| 09-vectorisation.Rmd         | 30 |
| 10-control-flow.Rmd          | 45 |
| 11-writing-data.Rmd          | 20 |
| 12-plyr.Rmd                  | 45 |
| 13-wrap-up.Rmd               | 15 |

I'm adding these timings to Scott's PR #24

**Comment by naupaka** [comment]
Closed via PR #29
