### ISSUE TITLE
Toy dataset on 04-data-structures-part1

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#191]
What about reword

> One of R’s most powerful features is its ability to deal with tabular data - like what you might already have in a spreadsheet or a CSV. Let’s start by making a toy dataset in your data/ directory, called feline-data.csv:

with

> One of R’s most powerful features is its ability to deal with tabular data - like what you might already have in a spreadsheet or a CSV. On RStudio's menu bar select File -> New File and write
> 
> ...
> 
> on the new file. After you type our toy dataset, save it under your data/ directory with the name feline-data.csv.

?

**Comment by naupaka** [comment]
I think the instructor can point this out, no? And depending on the context, the file could be made with `nano` or Notepad++ or whatever else...

**Comment by naupaka** [comment]
Closing this since I can see how different contexts would want to handle the creation of this file differently.
