### ISSUE TITLE
L suffix

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#192]
Can we move the note

> Note the L suffix to insist that a number is an integer.

to be a comment like

> ```
> typeof(1L)  # The L suffix is used to insist that a number is an integer since by default R use float numbers.
> ```

**Comment by naupaka** [comment]
Which lesson/line number?

**Comment by rgaiacs** [comment]
> Which lesson/line number?

`_episodes_rmd/04-data-structures-part1.Rmd`
