### ISSUE TITLE
Toy dataset after revert change

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#193]
On

> In order to successfully use our data in R, we need to understand what the basic
> data structures are, and how they behave. For now, let's remove that extra line
> from our cats data and reload it, while we investigate this behavior further:
> 
> feline-data.csv:
> 
> ```
> coat,weight,likes_string
> calico,2.1,1
> black,5.0,0
> tabby,3.2,1
> ```

can we use

> ``` r, eval=FALSE
> file.show("data/feline-data_v2.csv")
> ```

?

**Comment by naupaka** [comment]
Either way seems fine to me. `file.show()` is interactive vs programmatic, so that might be one reason not to use it, but it does make the dataset easier to view.

**Comment by naupaka** [comment]
Closing this for now, because I think using functions requiring interactivity are in general to be discouraged if possible.
