### ISSUE TITLE
Use "combine function" instead of "concatenate function"

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#194]
On 04-data-structures-part1 we find

> You can also make vectors with explicit contents with the concatenate function:

and I would like to use "combine function" instead of "concatenate function" 
since the official documentation use the word combine,

> This is a generic function which combines its arguments.

**Comment by naupaka** [comment]
Sounds reasonable. A PR to fix would be welcome.
