### ISSUE TITLE
Failed example

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#196]
> You can also read in files from the Internet by replacing the file paths with a web address. For example,
>
> ~~~
> gapminder <- read.csv("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv")
> ~~~

because the [file doesn't exist](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/data).

**Comment by naupaka** [comment]
Should work now because of the fixes added by PR #204
