### ISSUE TITLE
Drop "square brackets operator is a function" statement

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#198]
I don't think this belongs to the novice lesson since it will raise questions.

**Comment by naupaka** [comment]
Which line number and episode is that?

**Comment by rgaiacs** [comment]
> Which line number and episode is that?

`_episodes_rmd/06-data-subsetting.Rmd`

**Comment by lwjohnst86** [comment]
Curious why this wouldn't belong? Everything action that happens in R is a function, so would it not be appropriate to say this to novices?

**Comment by naupaka** [comment]
I think I am going to close this issue since this syntax is used throughout the whole lesson. I think if particular instructors prefer to teach it differently, they can do so on the fly, but I think in general since it is correct to refer to these as functions, I'd hesitate to change it.
