### ISSUE TITLE
Keep development in gh-pages branch or move it to master?

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#2]
Currently all of the content (from the [COMBINE repo](https://github.com/COMBINE-Australia/r-novice-gapminder/)) is on the gh-pages branch. Should we keep it there, and delete master, or occasionally merge back to master, or...?

**Comment by karawoo** [comment]
Doesn't it need to be on gh-pages in order to show up at http://swcarpentry.github.io/r-novice-gapminder/? If so, maybe delete master to reduce confusion, making gh-pages the main branch.

**Comment by hdashnow** [comment]
+1 @karawoo

**Comment by naupaka** [comment]
I don't have permissions to delete master or to switch gh-pages to default; we might have to ask @gvwilson to do it. I am +1 for this as well. Is there any reason to keep master around for anything else? What is standard SWC practice these days?

**Comment by karawoo** [comment]
Looks like r-novice-inflammation just has gh-pages, no master. I don't see any reason to keep it around.

**Comment by tomwright01** [comment]
I'm not supportive of this. Using gh-pages as the 'main' development branch means that all the generated *.html pages need to be included. As all these pages are often touched by `make preview` this leads to cluttered logfiles.

As I understand it the current process for r-novice-inflammation is for PR's to only include .Rmd files, the maintainer is then responsible for merging the PR's and generating the *.md and *.html files. Perhaps @jdblischak could comment how this workflow is working out, with particular reference to how many contributors manage to follow the instructions correctly (I know I didn't).

I would prefer that a master branch is used for development, only *.md pages need be included in this. The package maintainers task would then be to merge PR's with master, create and checkout a new gh-pages branch, `make preview`, push the new gh-pages branch. This has the advantage of keeping source files and auto-generated files separate.

**Comment by jdblischak** [comment]
You can see the previous discussion on committing html files [here][lesson-template]. It comes down to a tradeoff between keeping the source code clean and making it easy for people to contribute.

Currently for r-novice-inflammation, contributors are instructed to send PRs to the gh-pages branch with only the Rmd file edited (though they are encouraged to build the html locally to view their changes). Then after a substantial number of changes have been made, I build the html pages. Thus all development happens on the gh-pages branch.

The alternative is to have all PRs sent to the master branch and only include generated files in the gh-pages branch. This works well when all contributors are comfortable with Git. r-novice-inflammation receives many PRs that are created by direct editing in GitHub, and having a more complicated development workflow is going to discourage these instructors from contributing.

[lesson-template]: https://github.com/swcarpentry/lesson-template/issues/159

**Comment by fmichonneau** [comment]
+1 for having a single gh-pages branch. It's important that all repositories in SWC follow the same organization to facilitate their management (e.g., CSS styling)

**Comment by hdashnow** [comment]
In our workshops, the only html page that we've ever actually needed was index.html. All others were rendered directly from markdown by GitHub. So committing html at all was actually unnecessary in many cases. We only committed html because they were already present in the repo.

**Comment by tomwright01** [comment]
Seems like gh-pages is the way to go. 
I created a PR #6 to add this information.

I agree with @naupaka we need someone with admin rights to change the default branch and delete the master branch.

**Comment by naupaka** [comment]
Paging @gvwilson - when you get a chance can you remove the master branch from this repo? I believe we have come to a consensus on that decision.

**Comment by gvwilson** [comment]
Done.

**Comment by naupaka** [comment]
Thanks!
