### ISSUE TITLE
Challenges and the materials in general should tell a story about analysing the gapminder dataset

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-gapminder#20]
When editing the materials and challenges, I think it's useful to keep in mind how they relate back to the central thread of the gapminder data and the kind of analysis we can do with it.

Discuss.

**Comment by orchid00** [comment]
I agree with Harriet, I actually have adapted many challenges when I taught this lesson

**Comment by gvwilson** [comment]
PRs sharing those adapted challenges would be very welcome.

**Comment by orchid00** [comment]
I'll work on that

**Comment by gvwilson** [comment]
@orchid00 can you please PR and we'll get @hdashnow to review?

**Comment by hdashnow** [comment]
@orchid00 I get a lot of notifications from r-novice-gapminder and don't always read them all, so please ping me outside GitHub if you'd like me to look at something :)

**Comment by naupaka** [comment]
@orchid00 I'm going to close this for now because there hasn't been any activity for a while, but if you get a minute to PR those changes you mentioned I'd be happy to review it.
