### ISSUE TITLE
Skip or remove elements by name

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#201]
The solution that we give to students is

```
x[-which(names(x) == "a")]
```

but

```
x[-(names(x) == "a")]
```

will work.

I understand that we use the `which` function because it will construct the solution that we present before to the students, i.e., `x[-"1"]`, but I wonder if would be better to first introduce sub-setting through logical and after that show how to skip or remove elements by name.

**Comment by naupaka** [comment]
Which episode and line number is this on, @rgaiacs?

**Comment by bbolker** [comment]
This may be resolved by https://github.com/swcarpentry/r-novice-gapminder/pull/290 ?

**Comment by naupaka** [comment]
Resolved by #290
