### ISSUE TITLE
Clarify CONTRIBUTING location: Rmd + md or Rmd only

### ISSUE THREAD

**Issue by ashander** [swcarpentry/r-novice-gapminder#206]
In #205 I only edited the Rmd, whereas in #204 @lmsimp edited both the Rmd and md. 

I may have missed it, but I don't think CONTRIBUTING.md documents which of these is preferred for this repo.

**Comment by naupaka** [comment]
We'd like just the `Rmd`. A quick PR to clarify that would be most welcome.

**Comment by fmichonneau** [comment]
It looks like it got lost during the transition to the new lesson template, but for the inflammation lesson, for a little while, there was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) that included this information and others. I think it's harder to ignore than the CONTRIBUTING file.

**Comment by gvwilson** [comment]
Apologies for nuking it - if it's generally applicable, can you please 
submit in the `styles` repo?

**Comment by naupaka** [comment]
This issue is resolved by #207. I will open a new issue concerning the PR template.
