### ISSUE TITLE
Use symbolic link to data directory

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#213]
We suppose to keep data sets at https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/data but we are storing data at https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd/data. Can we replace `data` directory with a symbolic link to `_episodes_rmd/data`?

**Comment by naupaka** [comment]
I'm going to say that symbolic links are probably a bad idea in a mixed-platform environment. @fmichonneau is working on a solution to the location of the data files. Closing this...
