### ISSUE TITLE
gapminder_wide.csv is not linked for download

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#219]
The lesson uses https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes_rmd/data/gapminder_wide.csv but there is no link to download it.

**Comment by anenadic** [comment]
Also in _extras/guide and elsewhere it is expecting this file to be in the top level data directory rather than _episodes_rmd/data:

[gapminder-data-wide]: https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/data/gapminder_wide.csv

**Comment by naupaka** [comment]
Bad link fixed by 9d85f5c50c. And I don't think the lessons themselves use gapminder-wide anymore, unless I'm mistaken. The lessons now include direct download of the gapminder dataset. See PR #204.
