### ISSUE TITLE
Add more easy challenges

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-gapminder#22]
In many of the lessons, the first challenge jumps straight into asking participants to go beyond what was just demonstrated and integrating ideas from other lessons. 

I propose making sure there is at least one challenge for each major learning milestone that just revises the topic. This challenge should only reinforce what was just demonstrated, and then the later challenges can slowly expand on this and ask the students to use critical thinking, draw from past topics, do some research etc. The difficult of the challenges should ramp up gradually.

Also keep in mind using the gapminder dataset as a theme throughout challenges where appropriate: #20

Here's an example of a lesson that I think has this problem (although many of them do, maybe others would like to mention specific cases):
http://swcarpentry.github.io/r-novice-gapminder/07-functions.html

I actually tried to fix this one in the last workshop by pulling in some inflammation expamples, but it's still not quite right.

**Comment by hdashnow** [comment]
Also, challenge 1 for 10-control-flow.html is another particularly hard one (that looks easy if you don't actually try it!). Mostly because they don't yet know about %in%

**Comment by naupaka** [comment]
I'd like to close this issue. We don't really need more challenges at this point, and it would be useful to direct PR contributions to other outstanding issues. Thoughts @tomwright01?
