### ISSUE TITLE
Curiosity question: Why not use travis for building site?

### ISSUE THREAD

**Issue by lwjohnst86** [swcarpentry/r-novice-gapminder#222]
I recently have been developing my own sites using R Markdown files as the pages and I have been emulating the approach used for the R4DS book: https://github.com/hadley/r4ds. Hadley uses travis to build the site. I'm curious, would that be an option for SWC to ease the difficulty that novice/newcomers have with contributing?

**Comment by andreabedini** [comment]
@tomwright01 @naupaka if I do `make lesson-rmd` I end up with different files than what's in the repo. Some are trivial and expected changes like

```
diff --git a/_episodes/02-project-intro.md b/_episodes/02-project-intro.md
index 85746a4..be8c7a1 100644
--- a/_episodes/02-project-intro.md
+++ b/_episodes/02-project-intro.md
@@ -202,7 +202,7 @@ Now we have a good directory structure we will now place/save the data file in t
 > > 
 > > 
 > > ~~~
-> > -rw-r--r--  1 naupaka  staff    80K Jul 19 12:32 data/gapminder-FiveYearData.csv
+> > -rw-r--r--  1 andrea  staff    80K 31 Oct 10:23 data/gapminder-FiveYearData.csv
 > > ~~~
 > > {: .output}
 > > The file size is 80K.
```

But other differences are substantial:

```
diff --git a/_episodes/08-plot-ggplot2.md b/_episodes/08-plot-ggplot2.md
index 87522d5..65af05e 100644
--- a/_episodes/08-plot-ggplot2.md
+++ b/_episodes/08-plot-ggplot2.md
@@ -198,6 +198,11 @@ global plot options in `ggplot` to the `geom_line` layer so it no longer applies
 to the points. Now we can clearly see that the points are drawn on top of the
 lines.
 
+> ## Tip: Setting an aesthetic to a value instead of a mapping
+>
+> So far, we've seen how to use an aesthetic (such as **color**) as a *mapping* to a variable in the data. For example, when we use `geom_line(aes(color=continent))`, ggplot will give a different color to each continent. But what if we want to change the colour of all lines to blue? You may think that `geom_line(aes(color="blue"))` should work, but it doesn't. Since we don't want to create a mapping to a specific variable, we simply move the color specification outside of the `aes()` function, like this: `geom_line(color="blue")`.
+{: .callout}
+
 > ## Challenge 3
 >
 > Switch the order of the point and line layers from the previous example. What
@@ -239,7 +244,7 @@ ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, color=continent)) +
 Currently it's hard to see the relationship between the points due to some strong
 outliers in GDP per capita. We can change the scale of units on the x axis using
 the *scale* functions. These control the mapping between the data values and
-visual values of an aesthetic. We can also modify the transparency  of the
+visual values of an aesthetic. We can also modify the transparency of the
 points, using the *alpha* function, which is especially helpful when you have
 a large amount of data which is very clustered.
 
@@ -259,6 +264,11 @@ of 1,000 is now 3 on the y axis, a value of 10,000 corresponds to 4 on the y
 axis and so on. This makes it easier to visualize the spread of data on the
 x-axis.
 
+> ## Tip Reminder: Setting an aesthetic to a value instead of a mapping
+>
+> Notice that we used `geom_point(alpha = 0.5)`. As the previous tip mentioned, using a setting outside of the `aes()` function will cause this value to be used for all points, which is what we want in this case. But just like any other aesthetic setting, *alpha* can also be mapped to a variable in the data. For example, we can give a different transparency to each continent with `geom_point(aes(alpha = continent))`.
+{: .callout}
+
 We can fit a simple relationship to the data by adding another layer,
 `geom_smooth`:
 ```

did someone forgot to do `make lesson-rmd` before pushing? Or I am misunderstanding the way lessons are generated? Is it documented anywhere?

Thanks

**Comment by naupaka** [comment]
So the way it generally works is people submit PRs containing changes to the Rmd files, and these changes are reviewed and merged if they are appropriate. Then once every few weeks or so I pull down these changes and rebuild the markdown and push back up to GH. The reason for the differences you see is that I just merged a PR a few days ago and haven't rebuilt the site yet. The idea is that we don't want things to change too often because people are using these materials to teach and we don't want them to have printed out one set and then have the online version they work through with students the next day have something quite different. So I try not to rebuild constantly, and only usually do so after a number of changes have been added in. This is the way I've been doing it for the last several years, but could be convinced to change to, e.g. Travis if the other maintainers agree and feel strongly...

Contributors don't ever need to rebuild the site themselves, unless they want to preview their changes locally. We ask that people only submit the Rmd files in PRs, and not the generated md files. We have a set of materials on how lessons are built available [here](https://swcarpentry.github.io/lesson-example/). Hope that helps clarify...

**Comment by naupaka** [comment]
I will defer to @gvwilson on the Travis question. AFAIK we haven't ever really discussed it?

**Comment by andreabedini** [comment]
it really helps, thanks @naupaka! it could be a good idea having a development website rendered for contributions and a _release_ website for official releases. But as @gvwilson knows, I should stop suggesting things I have no time to work on! ;-)

**Comment by naupaka** [comment]
Well folks can always build locally, as you did, and then view the rendered site locally. In that case, it would be up to date, since the merged changes in the `Rmd` are usually several weeks ahead of the rest of the site for the reasons above.

**Comment by andreabedini** [comment]
@naupaka yes but contributors need to be able to cross-check each other's work. Another advantage of having the in-development version rendered online is that there's many more eyes checking for mistakes.

**Comment by naupaka** [comment]
This is hopefully the idea for the reviews on PRs, but I take your point. Again I'll defer to @gvwilson on a development version. That's above my pay grade.

**Comment by gvwilson** [comment]
We've discussed Travis (@rgaiacs can comment here), and I think that a 
'development' branch connected to Travis would be useful - the trick 
would be to get it to display on GitHub Pages, but that's easier now 
that you can pick display branches.  The hard part is maintenance: we'd 
all like to believe that you can "just set it up", but if we're going to 
do this, we need someone to commit to maintaining it for a year at a time.

**Comment by andreabedini** [comment]
> The hard part is maintenance: we'd
> all like to believe that you can "just set it up", but if we're going to
> do this, we need someone to commit to maintaining it for a year at a time

@gvwilson just to be clear, here you mean maintain the travis build script (or in general the "system") right?

**Comment by naupaka** [comment]
Closing for now - looks like Travis can't do what we want yet...

**Comment by andreabedini** [comment]
@naupaka what makes you say that?

**Comment by naupaka** [comment]
See the discussion [here](https://github.com/datacarpentry/R-ecology-lesson/issues/154).
