### ISSUE TITLE
Move statistics/dplyr/etc up sooner in lesson ordering?

### ISSUE THREAD

**Issue by lwjohnst86** [swcarpentry/r-novice-gapminder#223]
I recently taught an R workshop where I covered the first half of the R session. One thing I felt was that given most learners who come to the R workshops want to learn to do statistics and data analysis, would it make sense to bring in more statistics/dplyr/etc sooner in the lesson ordering? It's not until well into the second half of the lesson that these are covered and yet for most learners, this is the real meat of what they will likely use and want to learn. What is everyone's opinion of interspersing the statistics/dplyr/etc with the data types/data frames/subsetting/etc? That first half is a real slog to get through...

**Comment by naupaka** [comment]
Thanks for the suggestion, and in general I agree with you that motivation is key for keeping learners engaged. Generally SWC workshops don't explicitly include statistics per se. But as an instructor, you should feel free to add in additional material for particular workshops and to rearrange the materials in this repo as you and the attendees prefer. 

The order we have them in is just a general suggestion but you certainly don't have to follow them to the letter. Personally I have started some workshops by showing a fully functional workflow, from raw data through to a nice html or docx output, and then motivate the lessons by them being pieces of what folks need to learn to get to the final product. I'm going to close this for now, but you should certainly feel free to reorder lessons for workshops you teach. I think making big changes in the 'official' ordering would mean a lot of re-smoothing in terms of what terms and concepts were introduced when, and etc, and this is likely more work than folks want to do at the moment...
