### ISSUE TITLE
07-control flow-set.seed consistency issue

### ISSUE THREAD

**Issue by r-lange** [swcarpentry/r-novice-gapminder#226]
In the control flow lesson when introducing the if statements it is stated that we'll use the set.seed function so everyone will pseudo randomly sample the same number.
However, in the code chunk that follows set.seed is never used although it is mentioned again in the tip following the code chunk.
Can the set.seed(10) be added to the code chunk for consistency?

**Comment by naupaka** [comment]
`set.seed()` is used on line 24 of that lesson (up near the top, and not echoed in the rendered version). Do you mean you'd prefer if it were moved down into the chunk after it is mentioned (and echoed)? That makes sense to me. Would you be willing to submit a PR with that change?

**Comment by r-lange** [comment]
Hi, 
Thanks for pointing out that set.seed(10) is used in line 24. However, as it is then explicitly mentioned in line 67(?) I believe it should be in the code chunk following the statement.
I'll update the file and will submit a PR. Thanks.

**Comment by naupaka** [comment]
Closed by #227
