### ISSUE TITLE
dplyr episode: incomplete solution for challenge 2

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-gapminder#230]
the solution gives the answer to the first part of the question but not the second (min and max values).

**Comment by liz-is** [comment]
I'm happy to add a solution for this as part of completing instructor training. Would it be better to provide a solution that uses `arrange()` from dplyr, which has not been introduced in the lesson, or that uses `which.max()/which.min()` and subsetting the data frame, or would it be good to have both of these types of solutions? 

`arrange()` is the most dplyr-like way to do this but adds a function that learners won't have seen previously so I don't know if it's the best solution in this case.

**Comment by liz-is** [comment]
For now I've added solutions using both approaches.

**Comment by naupaka** [comment]
Hi @liz-is I've just added comments to your PR #236 that should clarify what you've asked here.

**Comment by naupaka** [comment]
Closed by #236
