### ISSUE TITLE
tidyr episode: confusing challenge 1?

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-gapminder#232]
In challenge 1, we ask learners whether the gapminder format is in wide, long, or some intermediate form. If it's useful to talk about this concept to illustrate the utility of tidyr, it seems that it would be at least equally important to add to the answer that it's in the tidy format. It seems like it's a good opportunity to emphasize this concept again.

**Comment by naupaka** [comment]
I agree. The tidier the better. A PR to make this change would be welcome.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
