### ISSUE TITLE
dplyr vs data.table

### ISSUE THREAD

**Issue by simonthelwall** [swcarpentry/r-novice-gapminder#234]
More of a question than an issue. You favour dplyr over data.table. can you explain reasons why? 

I personally favour dplyr, but wondered if there were dictactic reasons.

**Comment by naupaka** [comment]
I think dplyr is more commonly used, works well with magrittr pipes, and the syntax is overall simpler in my opinion. It also plays nicely with the rest of the tidyverse, including ggplot, which we use in these lesson for plotting. data.table is great and very fast for large data sets, but its syntax is more SQL-like than R-like, so I think for beginners it's probably a bit of a stretch to get used to. Back several years ago, @sckott and I made a data.table lesson for our instructor checkout, but I have no idea where it ended up (we pitched it as intermediate-level).  Hope that helps. I'm going to close this issue for now.
