### ISSUE TITLE
Reference page title rendering improperly

### ISSUE THREAD

**Issue by noamross** [swcarpentry/r-novice-gapminder#239]
I'm not sure if this is an issue here or in the lesson template, but the title on the reference page renders oddly:

<img width="1142" alt="screen shot 2017-01-09 at 11 10 51 am" src="https://cloud.githubusercontent.com/assets/571752/21773245/4ec9a612-d65c-11e6-9cf6-71be133724d4.png">

(https://swcarpentry.github.io/r-novice-gapminder/reference/)

This does not appear to be the case in any of the other lessons.

**Comment by naupaka** [comment]
That is a good catch. I think this is a problem with the templates in the styles repo and not with the files in this lesson. I don't see a quick fix, but I'm not a template guru either. Maybe I'm missing something @gvwilson @fmichonneau?

**Comment by fmichonneau** [comment]
I haven't had a chance to test it, but I'm wondering if having the curly braces inside the link in a header isn't confusing the markdown parser to render the link.
