### ISSUE TITLE
Other topics that might be worth mentioning in the wrap-up

### ISSUE THREAD

**Issue by khughitt** [swcarpentry/r-novice-gapminder#242]
A few other topics that come to find for "software best practices" and might be worth mentioning in the wrap-up, at least for students to consider as a "next step" for learning:

1. Testing (unit testing, coverage, CI)
2. Software development approaches (TDD, Agile, pair-programming, etc.)
3. Containers (Docker, virtualenv)
4. Documentation generation (doxygen, sphinx)
5. Code reviews
6. Code reuse
7. Debugging
8. Profiling

Obviously, some of these are more advanced topics and the students will have a ways to go before they get there, but it still could be useful to at least put these on their radars, and point them in the direction of other articles/resources they could use to learn more about the topics.

Finally, one topic which overlaps some with "modularity", but is especially relevant IMO for scientific software development is _generalizability_. Very often, you will write some code for one particular analysis/dataset, and then later on realize you want to use it on a different dataset.

If some thought it put in early on about some of the likely types of datasets that it may be useful to analyze down the road, then dataset-specific features (e.g. annotations for a specific organism in genomics analyses) can be abstracted out and encoded into a analysis-specific configuration file (Rmd, YAML, etc.) which can then be easily modified to work with a different dataset later on.

**Comment by bbolker** [comment]
Most of these topics seem **way** beyond the scope of this set of lessons, which are super-basic ... except for 1, 4, 7, and 8, I'd be afraid to mention them just because they're such giant cans of worms ...

**Comment by khughitt** [comment]
That's fair! Perhaps some of the points can be worked into future lessons if they ever come about.
