### ISSUE TITLE
Variable Name Challenge 1 Intro To R and R Studio

### ISSUE THREAD

**Issue by jordwil** [swcarpentry/r-novice-gapminder#244]
I would recommend including the reasoning for the answers that would not work as variables.
For instance:

_age - We can only start variable names with letters or dots not followed by a number.

min-length - This contains a dash "-" character that can't be used when naming a variable. We can only use letters, numbers, dots, and underline "_" characters.

2widths -  We can't start a variable name with a number. 

I'd also recommend adding a question about a reserved word:

if - If is a special case called a reserved word. We use it for control structures that will be discussed at a later date.

**Comment by naupaka** [comment]
Sure, sounds good @jordwil. Want to submit the improved challenge and challenge answer as a pull request?

**Comment by naupaka** [comment]
Potentially addressed by #245

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
