### ISSUE TITLE
Pull in lesson-example CONTRIBUTING.md and LAYOUT.md

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#25]
This information has been updated since the repository has started. Key information includes R markdown usage. Pull from https://github.com/swcarpentry/lesson-example

**Comment by aammd** [comment]
Agree that we need this.

**Comment by aammd** [comment]
@jdblischak  mentioned over in #17  that 

> CONTRIBUTING.md is part of the core lesson-template repo. New changes to the lesson template are merged from this repo into downstream lesson repos like this one. Thus making changes to this file creates the risk of merge conflicts. 

I read this as meaning we need to treat the CONTRIBUTING.md over in lesson-template as the master copy, and use git to bring recent versions of those files over here, into the gapminder lesson. AM I understanding that correctly?
