### ISSUE TITLE
Move while loop to a callout?

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-gapminder#27]
This might be a contentious suggestion... but what about removing while loops from the core lesson, and just mentioning them in a callout? I think while loops are the least useful for beginners. It almost seems like they are just in there for completeness. 

I suggest removing the while loop part of the lesson, and put in a call out with links to extra readings for people who are interested.

Thoughts?

**Comment by SamPenrose** [comment]
+1

**Comment by karawoo** [comment]
I totally support this.

**Comment by naupaka** [comment]
Closed by #38
