### ISSUE TITLE
Seeking Help Module

### ISSUE THREAD

**Issue by hkronenb** [swcarpentry/r-novice-gapminder#272]
Earlier today I participated in a live coding demo session led by Erin Becker using this module and my group came up with a couple of suggestions for improvements. 
1. The first thing that looks like example code is not actually code. I put this as a comment in my demo but I think additionally it would be good to just have a little more explanation: "This is the basic format for how you would ask for help for a function in R" 
2. It is a little odd that "dput" is what we use as an example maybe it would make more sense if we asked for help on something we had already use or will use in the next section. 
3. Maybe instead of focusing on using help for those two challenge questions in the module it would be better to integrate asking R for help throughout all the modules. That encourages students to make a habit of using the help function in R.

**Comment by naupaka** [comment]
I agree - I think one and two would be easy fixes and I'd be happy to review a PR with those changes. The third one is also a good idea, but would be a good bit more work.

**Comment by ErinBecker** [comment]
@naupaka - One easy way to integrate suggestion 3 would be to add a callout to learners about using the help function a couple of times throughout the lessons. It could also be added as a tip to instructors in the instructor notes. What do you think?

**Comment by naupaka** [comment]
Sure, I am definitely on board with more reminders to check help scattered throughout the lessons. Just seems like a big project to do it consistently and thoughtfully across all lessons and I didn't want to request that it all had to be done in one PR.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
