### ISSUE TITLE
Introduction to R and RStudio: Objectives

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/r-novice-gapminder#273]
Hi.  I would like to offer a suggestion to modify the objectives of the first episode in the lesson.  I was taught that learning objectives should be specific and measurable, avoiding generalities such as “understand” or “know.”   They should be written in the form of completing the sentence beginning with “The learner will be able to...”  I suggest the objectives be changed as follows.

To gain familiarity with the various panes in the RStudio IDE
--Describe the purpose and use of each pane in the RStudio IDE

To gain familiarity with the buttons, short cuts and options in the RStudio IDE
--Locate buttons and options in the RStudio IDE

To understand variables and how to assign to them
--Define a variable
--Assign data to a variable

To be able to manage your workspace in an interactive R session
--Manage a workspace in an interactive R session

To be able to use mathematical and comparison operations
--Use mathematical and comparison operators

To be able to call functions
--Call functions

Introduction to package management
--Manage packages

Let me know what you think.

**Comment by naupaka** [comment]
Hi @kekoziar I agree with you 100% that these should be reworded. The other episodes all need touch-up too. I'd be happy to review a pull request with these changes.

**Comment by kekoziar** [comment]
Thanks for the feedback, @naupaka.  I am reading through the lesson with the intention of teaching it within the next year, and am making notes as I go along.  I'll start initiating pull requests with changes to objectives, along with some slight grammatical corrections.
