### ISSUE TITLE
seeking help

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/r-novice-gapminder#276]
Submitted via email for instructor checkout ---

Notes on Contribution to R
“Seeking help” section
These contributions are needed in the ‘seeking help’ section
•	In R studio, in order to set your working directory, go to session, click on set working directory and choose directory where you have your data apart from the ‘setwd()’  command
•	If your computer or laptop switch off during your work using R studio and you have been saving the scripts in the R script, all you have to do is 

o	Open R studio
o	Click on file, a drop-down will come up, click on recent file (the folder you have been working with will be there, click on it and all the scripts will return)

**Comment by hkronenb** [comment]
Would it potentially make more sense to put the setwd() command in the "Project Management with R Studio" section. I could actually see both going in that section but particularly setwd() because it has tips about putting files in directories and saving data in certain directories.

**Comment by naupaka** [comment]
I think general best-practice these days is to use RStudio projects to keep paths set properly, as opposed to setting the path itself with `setwd()` via console or GUI. Certainly seems to be easiest approach IME, especially for beginners. 

I agree that setting paths seems like a better fit for the Project Management section.

**Comment by bbolker** [comment]
I would vote for including the `setwd()` stuff somewhere. I would prefer not to unnecessarily lock the lessons into one particular approach (i.e. using RStudio projects), and changing working directories is an issue that is *definitely* going to come up in practice, no matter how much you try to avoid it by using projects.

**Comment by naupaka** [comment]
I definitely agree with that sentiment, @hkronenb @bbolker. Probably would fit best in Project Management episode. I'd be happy to review a PR adding this content to that episode.

**Comment by naupaka** [comment]
See also discussion on #332

**Comment by jcoliver** [comment]
In my workshop experiences, `setwd` often ends up in headaches (because it happened somewhere, and it takes a while for instructor or helper to figure out why the files aren't being found). The one benefit is that this affords an "opportunity" to teach `getwd`.

Is there a way to introduce `setwd` explicitly, early on, and explain what it does (and the implications)? I would love to propose a solution, but I avoid it myself. Some analogous issues arise with `attach`.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
