### ISSUE TITLE
Convert non-topic Markdown files to Rmarkdown?

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#28]
Following the discussion in Issue #17, I propose we convert the non-topic markdown files (e.g. LAYOUT.md, index.md, CONTRIBUTING.md, etc.) to R markdown files. That way we can add "*.md" to the .gitignore, to simplify the process for future contributors (who should then only ever edit the .Rmd files).

**Comment by naupaka** [comment]
I think if we make them into Rmd then we also need to knit them before jekyll will process them, which doesn't seem right and may not work with the makefile as is, plus it will make pulling future changes from the main lesson template repo more complicated since those files will stay as `foo.md`.

**Comment by sritchie73** [comment]
Good point. This is a bad idea.

**Comment by aammd** [comment]
seems like it's OK to close this one?
