### ISSUE TITLE
Using backticks rather than quotes for special functions

### ISSUE THREAD

**Issue by webbedfeet** [swcarpentry/r-novice-gapminder#280]
Hello,

I would like to suggest an improvement to  the "Seeking Help" episode ([03-seeking-help.md](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes/03-seeking-help.md)). 

For the special functions you suggest ?"+", for example. Can I suggest changing or at least showing the option of using backticks, i.e.,      @@###?\`+\`. I personally like the distinction of reserving backticks for function specifications to avoid confusion with strings. I understand that the markdown might be a bit trickier to write, but for a new learner keeping functions separate from strings might be a good idea

Abhijit

**Comment by naupaka** [comment]
Hi @webbedfeet thanks for the suggestion. I think you are right to pick up on the fact that this is a bit confusing, and on how the not-so-obvious difference between quoted strings vs quoted infix functions. 

My personal preference would be to just take it out altogether, and just demonstrate the use of the `?` for help on a normal function, like `?plot`. IMO, using backticks for infix operators seems a little in the weeds for so early in the material.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
