### ISSUE TITLE
Split-Apply-Combine figures

### ISSUE THREAD

**Issue by damianrt** [swcarpentry/r-novice-gapminder#287]
Looking at the Split-Apply-Combine lecture I noticed a few things in the images that could be improved

For the first image (splitapply.png), the combine step appears to have an error. Assuming the calculation being shown is the mean, the result for group A should be 3 (at the end).  Also it might help to add labels to associate each column with the appropriate step (split, apply, and combine) 

The second image/table could also be improved by adding labels to indicate that the two dimensions of the table correspond to the input and output data types for each function.  Although it could be read either way, with rows = input and columns = output or visa versa, labels would save students the effort to make this connection .

**Comment by naupaka** [comment]
The first error you point out (2 should be 3) is addressed in #288, which I'm in the process of reviewing now. Once that gets merged in, then I'd be happy to take a look at a PR with the labels added if you'd like.

**Comment by damianrt** [comment]
Pull request submitted ([#289](https://github.com/swcarpentry/r-novice-gapminder/pull/289))

**Comment by naupaka** [comment]
Thanks, I take a look at it soon.
