### ISSUE TITLE
typeof() 

### ISSUE THREAD

**Issue by bbolker** [swcarpentry/r-novice-gapminder#294]
This is a fairly major philosophical question, but: is it really worth leading with `typeof()` in the data structures lesson, or would it be better to lead with `class()` and possibly mention `typeof()` later on (in passing, or in a tip/callout box)?

Arguments **for** `typeof()`:

- systematic
- will appeal to computer scientists and people who like to know how it all works "under the hood"
- limited number of possibilities

Arguments **against** `typeof()` (and in favo(u)r of `class`):

- `typeof()` adds to confusion over factors
- class is explicitly a *logical* description of an object's type, not its underlying properties

Some more discussion [here](https://stats.stackexchange.com/questions/3212/mode-class-and-type-of-r-objects) and [here](https://stackoverflow.com/questions/6258004/types-and-classes-of-variables) (including "mode", which lumps integer and double together as `"numeric"` but `mode(factor)` is still `"numeric"` ...

While we're at it, I would vote for leaving out the "complex" type, or mentioning it in a callout ...

**Comment by naupaka** [comment]
I am happy to have it either way. Preference @noamross @karawoo @aammd @tomwright01 ?

**Comment by karawoo** [comment]
Yeah, I don't feel that strongly on this one. But 👍 to glossing over "complex".

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
