### ISSUE TITLE
To tibble or not to tibble

### ISSUE THREAD

**Issue by munrosa** [swcarpentry/r-novice-gapminder#297]
In Lesson 13, when dplyr is introduced, tibbles also begin to show up in the code output, but aren't directly discussed in the lesson. It might be worthwhile to show the output of some of the dplyr results. For example, gdp_bycontinents_byyear is a tibble, but it isn't shown or discussed. It's natural for people to want to look at the output to see if they achieved the desired result, since someone is going to look at these results and see that they are tibbles it would be helpful for the instructors to have a brief (1 sentence) explanation of tibbles in the lesson, so that they are prepared to make a quick explanation and not veer off on a tangent. Something along the lines of "tibbles are the tidyverse version of data frames" would be good, with a link out to a more detailed description, such as 
https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html

**Comment by naupaka** [comment]
I agree a sentence or two the first time that type of output appears would be useful. Basically something along the lines of: 'tibbles are a superset of data frames that give them some additional useful properties/features"

**Comment by naupaka** [comment]
Closed by #303
