### ISSUE TITLE
URLs for contributing in /blob/gh-pages/CONTRIBUTING.md

### ISSUE THREAD

**Issue by adsteen** [swcarpentry/r-novice-gapminder#298]
in `/blob/gh-pages/CONTRIBUTING.md` lines 48-50, the URLs given to work in for people who want to change the lesson are [https://github.com/swcarpentry/FIXME](https://github.com/swcarpentry/FIXME) and [https://swcarpentry.github.io/FIXME](https://swcarpentry.github.io/FIXME). These both give a 404 Not Found error.

**Comment by naupaka** [comment]
Looks like this would be an easy thing to fix with a PR. See the equivalent fix over at r-inflammation: https://github.com/swcarpentry/r-novice-inflammation/pull/291

**Comment by naupaka** [comment]
Resolves by #299
