### ISSUE TITLE
Should packrat content be included or removed?

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#3]
Via discussion in #1 it seems like people want to take it out, especially for novice materials.

**Comment by hdashnow** [comment]
I suggest replacing packrat with the manual creation of a few folders e.g. data, scripts and explaining why it's useful to keep your raw data untouched.
Maybe some discussion of keeping your scripts in version control using R-studio Git integration at that point too (assuming this is run as day 2 or a workshop that included Git on day 1).

**Comment by JohnRMoreau** [comment]
If we keep the project management content, then perhaps we might consider moving that lesson to later in the sequence. Right now, jumping from arithmetic and basic functions to managing project feels like a huge leap. If I'm a brand-new novice learner and I've just gotten the hang of calling a function, I don't yet even understand what it means to have a project in R. At this point, I can't even imagine what that looks like or why I, the novice learner, should care. 
The lesson could still be quite useful later in a workshop. Sometimes you (okay, I) don't understand why I need to do seemingly mundane housekeeping until I've made a right mess of things. If we let students clutter up their work spaces\environments just a little, they might be able to connect that experience with the need for project management.

**Comment by naupaka** [comment]
Packrat content was removed via changes made in PR #15, and ProjectTemplate content moved into sidebar section. Closing this for now.
