### ISSUE TITLE
Use of first person narrative in Lessons 2, 14, and 15

### ISSUE THREAD

**Issue by rlbarter** [swcarpentry/r-novice-gapminder#302]
There is frequent use of the first person narrative in Lessons 2, 14 and 15. For example in Lesson 2, the author often writes "_I find it useful to..._". 
Similar occurences also take place once in Lesson 14 "_I usually prefer my data in this intermediate format..._", and 4 times in Lesson 15 "_When I was first starting out, I’d write an R script..._" 

In the other lessons there is no use of first person pronouns to describe the author of the lesson, making the readability a little bit inconsistent. 

A suggestion is that instead of saying in first person that "I find it useful to store these scripts in a separate folder", it is more consistent with the other lessons to say something like "It can be helpful to store these scripts in a second folder".

**Comment by naupaka** [comment]
That seems reasonable. Would you be willing to submit a pull request updating those episodes to be consistent with the rest of the materials?

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
