### ISSUE TITLE
Unclear instructions for contributing to R lessons

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#304]
I can't seem to find a clear simple set of instructions on how to contribute to the R lessons. As I recall they used to be in contributing.md, but perhaps that was modified at some point so R-specific things (like only modify the Rmd files) are not there. This should be fixed.

**Comment by naupaka** [comment]
Yeah I think the trick is that the contributing.md comes from the styles repo, which is across all lessons, and the R lessons have some particularities that are distinct. This will also be the case if/when python development shifts to jupyter notebooks from markdown.

**Comment by jcoliver** [comment]
A great visualization is available in #342 . Maybe we could add a START_HERE.md with information like this that is relatively repo-specific (for now)?
