### ISSUE TITLE
Spell check?

### ISSUE THREAD

**Issue by SamPenrose** [swcarpentry/r-novice-gapminder#31]
I would be happy to do a global spell check run on the Rmd files. If this is a good idea, let me know when origin/gh-pages is ready for a PR with lots of small changes.

**Comment by hdashnow** [comment]
Great idea! I apologise in advance for all the spelling errors I have introduced from working in vim...

Might want to do one now-ish, and then another at the end of the sprint to catch all the brand new errors.

**Comment by SamPenrose** [comment]
OK. I'll do one as soon as someone merges PR #30 ;-) .
