### ISSUE TITLE
Link works but is a fail

### ISSUE THREAD

**Issue by GenieJx** [swcarpentry/r-novice-gapminder#319]
Please delete the text below before submitting your contribution. 

On the page for R data frames (http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/), a link for a cat age calculator is provided (https://www.proplan.com/cats/cat-age-calculator) that does not return a cat age. I suggest another link: (https://www.purina.co.uk/cats/key-life-stages/ageing/cats-age-in-human-years)

**Comment by tylerkelly13** [comment]
Good spot, I've created a pull request to make the suggested change.

**Comment by GenieJx** [comment]
Cool- thanks!
