### ISSUE TITLE
Including Link to Gapminder data in Setup or Extras

### ISSUE THREAD

**Issue by cmaimone** [swcarpentry/r-novice-gapminder#329]
It would be very useful to have a link to the gapminder data for download included on the Setup section of the course site, or, if you don't want people downloading it beforehand, in at least the Extras section.  Currently, this data is first downloaded during a Challenge in Episode 2, which an instructor may or may not actually do.  

Everytime I go through this material, I have to search to find the link to the data, which sometimes I send to people to download ahead of time if there may be internet connection issues.

I'm happy to submit a PR adding the link the Extras section if this change is OK to make.

**Comment by naupaka** [comment]
Definitely would be great to add this to the Extras section. PR for that would be most welcome.

**Comment by cengel** [comment]
This issue is still open, but I see that links to gapminder data seem to be in the Extras section under "Pulling in Data". One has to scroll down, so perhaps not that easy to find.

**Comment by naupaka** [comment]
Thanks for pointing that out @cengel. I think it's probably fine to have it in the Extras, but I also think it's time to remove the bit about 

```
git remote add data https://github.com/resbaz/r-novice-gapminder-files
git pull data master
```

which is from the antecedent material that became these lessons. Would be better to have the materials be pulled directly from a carpentries repo.

**Comment by jcoliver** [comment]
Would it be possible to also have a good old fashioned URL, too? Even if it was shortened (like a tinyurl, oh, hey, look, there's one here: http://tinyurl.com/gapminder-five-year-csv), in case folks don't want to go the Git route...

**Comment by raynamharris** [comment]
@jcoliver How would you instruct the user to get the data from <http://tinyurl.com/gapminder-five-year-csv> into R? Copy, paste, save, read? Or with something like:

```
library(data.table)
gapminder <- fread('http://tinyurl.com/gapminder-five-year-csv')
head(gapminder)
```

**Comment by jcoliver** [comment]
@raynamharris I'll usually have folks download the file by entering the URL into a browser window (and doing "Save as..." if not automatically prompted to save the file), but

    download.file(url = "http://tinyurl.com/gapminder-five-year-csv", destfile = "data/gapminder-FiveYearData.csv")
    gapminder <- read.csv(file = "data/gapminder-FiveYearData.csv")

should work, too.

**Comment by wallacelab** [comment]
I would recommend adding to this section a note that the gapminder data can be loaded using `library(gapminder)`. (See also issue #481.)

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
