### ISSUE TITLE
Inconsistency in # of functions in text in 13: dplyr

### ISSUE THREAD

**Issue by cmaimone** [swcarpentry/r-novice-gapminder#331]
Part 13: dplyr, says "we're going to cover 6 of the most commonly used functions..." and then only lists 5 functions.  Either arrange should be added as the 6th, or the sentence should be edited to say 5 functions.  I can make a PR, but I don't know whether arrange was intentionally excluded, or if this is just an omission.

**Comment by naupaka** [comment]
Thanks for catching that, and sorry for the delayed response. Seems like a typo. I think the easiest for now would be change 6 to 5. `arrange()` is handy, but not *always* used like most of the others, so perhaps we could get away without having it in there now. A PR to fix that would be welcome.

I think if anything, these lessons often err on the side of too much content, and could use more focus, so no reason to add more in here.

**Comment by cmaimone** [comment]
Do you want changes made to the Rmd or md file?

**Comment by naupaka** [comment]
Just the Rmd, please. I render those to md when we rebuild the site, so any changes to md will get overwritten. Thanks!

**Comment by anuj2054** [comment]
Is there anything left in this issue ?

**Comment by naupaka** [comment]
Yes, this still needs fixed - I just checked.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
