### ISSUE TITLE
Defining vectors

### ISSUE THREAD

**Issue by anideaofhappiness** [swcarpentry/r-novice-gapminder#334]
Being mainly acquainted with the physics definition of vector (magnitude + direction), the introduction of Vectorization in Lesson 1 confused me, as it seems to assume a common understanding of what a vector is in this context that did not match my understanding. Vectors in the R environment _are_ defined later in Lesson 4. I would suggest either moving the definition up, or adding a phrase like, "functions can have vectors, or ordered lists of things, as values", or, "vectors (which we'll discuss more in a later lesson)" to Lesson 1.

**Comment by naupaka** [comment]
I have had this same comment made at a number of workshops, and always by a physicist! 

I think it would be good to add a clarifying phrase to the first mention of vectors. I'd be happy to review a pull request if you want to give it a go.

**Comment by jcoliver** [comment]
Fixed by PR #347
