### ISSUE TITLE
Can we delete the xx-*-.md files?

### ISSUE THREAD

**Issue by SamPenrose** [swcarpentry/r-novice-gapminder#35]
Are we done with e.g. 01-rstudio-intro.md now that we have 01-rstudio-intro.Rmd?

**Comment by jdblischak** [comment]
The last time this was discussed, the majority of R instructors prefered to keep the intermediate markdown files:

https://github.com/swcarpentry/r-novice-inflammation/pull/38

**Comment by SamPenrose** [comment]
Ah, I did not realize the function they served. Thanks for clarifying.
