### ISSUE TITLE
Exploring Data Frames: Removing Columns

### ISSUE THREAD

**Issue by JamieMcDevittIrwin** [swcarpentry/r-novice-gapminder#351]
In the Exploring Data Frames lesson, I think it would be useful to add a section called: Removing Columns after the Removing Rows section.  I think it would help the students understand the difference between handling rows and columns, particularly the example: cats[-4,] because they will get to see the opposite example with a column and really drive home where you mean row or column in []. I also think it can be helpful in real life research, if you want to clean metadata by only including factors you will analyze or if you merge two datasets and there are duplicate columns. I also don’t think it would add that much time to the exercise.

**Comment by jcoliver** [comment]
Thanks @JamieMcDevittIrwin ! Sounds like a short section that could immediately follow the Removing Rows section. It could even show _two_ ways of removing columns: by index and by name. Want to submit a PR on the .Rmd file?

**Comment by JamieMcDevittIrwin** [comment]
Yes I can! Sorry for my late response, I'll try to do this within the next week.

**Comment by JamieMcDevittIrwin** [comment]
I submitted the pull request. Thank you!

**Comment by jcoliver** [comment]
Resolved by #362
