### ISSUE TITLE
Measurable objectives in Creating Publication-Quality Graphics episode

### ISSUE THREAD

**Issue by sashasaurus** [swcarpentry/r-novice-gapminder#353]
I have a suggestion for making the following learning objective from 'Creating Publication-Quality Graphics' a little less abstract:  

> To understand the basic grammar of graphics, including the aesthetics and geometry layers, adding statistics, transforming scales, and coloring or panelling by groups

We could use more specific, measurable verbs such as:  

Students will be able to...
- apply aesthetic, geometry, statistical layers to a ggplot plot, 
- manipulate the aesthetics of a plot using different colors and shapes, 
- improve data visualization through transforming scales and paneling by group

**Comment by jcoliver** [comment]
Thanks, @sashasaurus . Great idea - want to submit a PR with changes to the .Rmd file?

**Comment by sashasaurus** [comment]
Will do, thanks.

**Comment by mawds** [comment]
Thanks for the PR!
