### ISSUE TITLE
Pilotting the new GitHub labels

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-gapminder#355]
@mawds @jcoliver @tomwright01 @naupaka 

I added to the repository the proposed set of GitHub labels that we're planning to use across all repositories for the Carpentries. We are in a piloting phase and we want to start using them to see if adjustments are needed before we deploy them everywhere. We are going to test them first in a few repositories including this one until the end of the month. The goal is make it easier for people to contribute to the lessons by identifying more clearly which issues can be worked on, and the type of work that needs to be done, and to make it easier for you as a maintainer to sort through the issues and pull requests you receive.

It would be great if you could split among yourselves the issues that are currently in the repository and assign at least 2 labels for each: one in the "status" category, and in the "type" category. Depending on the context, you may also want to add the "bug-bbq", the "good first issue" or the "high-priority" labels.

Ideally, we'd like to remove the legacy labels by the end of the month as well, so issues with these old labels should be re-assigned new labels.

I'd like your feedback on how well these labels capture the type of issues that are currently in the repository, or that you have received in the past. If you feel that some labels don't capture the nature of the issue, or if the meaning of the labels is too unclear to make a call, I'd really like to hear about it.

The definition of the labels is available in this proposal: https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit

Feel free to ping me on Slack, by email or here if you have any questions or with your comments/feedback.

Thank you for your help with this!

**Comment by jcoliver** [comment]
@fmichonneau @mawds @tomwright01 @naupaka 
I ran through and added new labels for the ten most recent issues. I'm still getting used to the taxonomy and the visual impact (soooooo many colors), but would be interested to hear other folks' opinions.

**Comment by naupaka** [comment]
I added labels on the rest. I agree it is a lot of colors, but will be nice to be able to filter on them, I think. What's the difference between "looking for contributor" and "help wanted"?

**Comment by fmichonneau** [comment]
Thanks for assigning the prototype labels to the issues! 

@naupaka "looking for contributor" is meant to be a general call to the community to start working on addressing the issue. The maintainers have reviewed the issue, it is valid, and should be addressed. The "help-wanted" label signals that someone as started to work on this, but additional feedback/input is needed from the community to fully address the issue. Does this distinction make sense to you?

What are your suggestions to improve the labels?

**Comment by naupaka** [comment]
@fmichonneau makes sense to me. I might consider renaming help-wanted to 'outside-expertise-needed' or something similar, so that they are not so easy to confuse.

**Comment by katrinleinweber** [comment]
Using a non-standard name removes the `... issues need help` shortcut from our organisation's repo overview page. Compare those hyperlinks on https://github.com/swcarpentry for example. Do we have a way to bend that link towards a non-standard label?

If not: is that immediate benefit worth less than a possibly better name? Please consider: [naming things is hard](https://duckduckgo.com/?q=%22naming+things+is+hard%22), thus trying to invent new names risks going down a rabbit hole.

**Comment by fmichonneau** [comment]
@katrinleinweber we opted for `help wanted` to ensure we could take advantage of this new GitHub UI feature.

**Comment by katrinleinweber** [comment]
I [know](https://github.com/carpentries/handbook/pull/169/commits/51c666abfb4daece6b7cedf8d385467475f9c1d3#diff-0096de1093cbda882c5ab5960bdec831R2), but I observe that the `status:` part still effects that we can't "take advantage".

[![grafik](https://user-images.githubusercontent.com/9948149/38601030-8e0b757c-3d66-11e8-877c-cbd1c055fbdb.png)](https://github.com/swcarpentry/r-novice-gapminder/issues?q=label%3A%22good+first+issue%22+is%3Aissue+is%3Aopen) 

compared to [about a dozen issues with `status:help-wanted`](https://github.com/swcarpentry/r-novice-gapminder/issues?utf8=%E2%9C%93&q=label%3A%22status%3Ahelp-wanted%22+is%3Aissue+is%3Aopen).

**Comment by fmichonneau** [comment]
Note that r-novice-gapminder hasn't been transferred to the revised set of labels, it uses the initlal set. I'll work on the transition after the Bug BBQ. The newer version uses GitHub's "good first issue".

**Comment by katrinleinweber** [comment]
That's exactly what I meant with this https://github.com/carpentries/lesson-infrastructure/issues/1#issuecomment-380362120

About "revised" & "inital": both mean some version of [handbook/.../github_labels.csv](https://github.com/carpentries/handbook/commits/master/data/github_labels.csv), I presume? `r-novice-gapminder` uses a mixture of labels (already). Otherwise, the screenshot wouldn't have been possible ;-)
