### ISSUE TITLE
Introduce tidyverse earlier

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#365]
Continuing from #364 
Briefly: There is some discussion about introducing at least of some the material from later episodes (e.g. 13-dplyr and 14-tidyr) earlier in the schedule. A number of functions, such as `read_csv()` may impart a lower cognitive load for new learners. Thanks to @maurolepore for raising this point.

I am inclined to continue with base R in the early episodes, and allow tidyverse exploration for later points of the workshop, acknowledging that this means that many workshops may not even get to that material. While there is a considerable amount of functionality offered in tidyverse, and there is growing adoption of those packages, I think many novices would benefit from sticking to base R. Should a specific workshop desire a focus on more tidy-type offerings, the [first lesson plan in the instructor notes](http://swcarpentry.github.io/r-novice-gapminder/guide/) provides one way to do this.

But as @naupaka says, there are other opinions. It would be great to hear them, too.

**Comment by ateucher** [comment]
I think this issue is also tied up with the question of what level of experience is expected of the learners? My understanding is that originally SWC was targeted at scientists who already write quite a lot of code, but want to learn better _programming_ techniques (iteration and flow control, small, testable, composable functions etc). If that is the case then I think the focus on base R is appropriate. However my sense is that more and more SWC is teaching R/python to complete novices... and in that case I think the tidyverse-first approach is superior.

**Comment by maurolepore** [comment]
@philippbayer that sounds like a great plan!

RE: 

> but also needs an intro to readr to download and read the data in the first place. 

Have you thought of using the point-and-click interface for now?

![image](https://user-images.githubusercontent.com/5856545/47795592-304b2a80-dcf9-11e8-9d38-a35da6256f3b.png)

**Comment by philippbayer** [comment]
@maurolepore Thanks for the tip, I never used that button - that will reduce some of the cognitive load!

**Comment by philippbayer** [comment]
I've made some changes in my fork, maybe someone else can use this:

Intro to basic R (basic maths, exp(), comparisons) - 20 min
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/01-rstudio-intro.md

Rstudio  - 10 min
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/02-project-intro.md

Finding help - 10 min
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/03-seeking-help.md

Data structures in tidyverse (tibbles) - 1 hour?
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/04-data-structures-part1.md

Manipulating data structures the old school way (deleting, adding
columns etc) - 1 hour?
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/05-data-structures-part2.md

Effectively using tidyverse (mostly dplyr ) - 1 hour?
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/08-dplyr.md

Plotting in ggplot2 and connecting ggplot2 with dplyr - 30 min
https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/13-plot-ggplot2.md

Originally, ggplot2 is lesson 8 and dplyr is lesson 13, I switched their
places. At the end of the dplyr lesson there was a 'connect ggplot2
and dplyr' piece which I've now moved over to the end of lesson 13.

**Comment by naupaka** [comment]
@philippbayer thanks for adding this here! You may also want to contribute this order and timings to the `_extras/guide.md` as a PR.

Relatedly, I think it is time to have a serious reconsideration of the order and flow of the lessons to catch them up to modern best practices. @jcoliver @mawds maybe for the next semi-annual release? Potentially should have the tidyverse vs base R discussion in curriculum committee.

**Comment by philippbayer** [comment]
I'm in favor of switching to tidyverse - if you look at my lesson for [04-data-structures-part1.md]( https://github.com/philippbayer/r-novice-gapminder/blob/gh-pages/_episodes/04-data-structures-part1.md), I changed the data-frames to tibbles and removed matrices etc., which allowed me to mostly delete stuff that was just annoying to discuss (for example, I could delete all references to stringsAsFactors)

**Comment by mawds** [comment]
@naupaka - I agree.   Probably also worth speaking with the curriculum committee about how this lesson fits with the other R lesson (http://swcarpentry.github.io/r-novice-inflammation)? 

As the focus of the other lesson is more "regular" programming  and this is more data-analysis then I think having this lesson tidyverse focussed and that base R focussed makes a lot of sense.

**Comment by mawds** [comment]
See also issue #442

**Comment by jcoliver** [comment]
I would be interested in seeing a plan for (1) what tidyverse functions are included and (2) where they would end up. I worry a little bit about providing an introduction to R that skips some pretty fundamental things [1]. But having some rearrangement so the amazing tools of dplyr and ggplot are covered earlier makes sense to me.

[1] Recognizing that we don't teach things just because they are "fundamental", but because they are important for early wins and later successes. For example, I think the repeated practice with `data.frames` is important, but I may be a Luddite.

**Comment by philippbayer** [comment]
Hello again, I found these 'alternative' lessons from the University of Manchester which do mostly what I wanted to do in my 'experimental' fork:

https://uomresearchit.github.io/r-tidyverse-intro/

**Comment by mawds** [comment]
Yes - those are the lessons I mentioned in my post April last year (though it looks like I didn't link to them - d'oh! ).  The focus of the course I (used to - am no longer at UoM) run was much more data analysis focused than the official lesson (and also had less time), hence the adaptation.

**Comment by jcoliver** [comment]
Issue is largely addressed with alternative lesson plans provided in the [Instructor Notes](http://swcarpentry.github.io/r-novice-gapminder/guide/).
