### ISSUE TITLE
Duplicate Challenge Numbering in "Function Explained"

### ISSUE THREAD

**Issue by EnigMATHic** [swcarpentry/r-novice-gapminder#368]
There are two sections called "Challenge 3" in the Function Explained module.  Easy fix: update the numbering!

Thanks
Elizabeth

**Comment by jcoliver** [comment]
Thanks, @EnigMATHic ! Want to submit a PR with changes to the .Rmd file?

**Comment by mzc9** [comment]
Hi,

Newb here.  If no one is working on this, may I take a stab at it?

**Comment by jcoliver** [comment]
Yes, @mzc9 ! Please do!

**Comment by mzc9** [comment]
Hi,
I created a PR, but notice that /.Rhistory is also included.  Should I remove that?

**Comment by jcoliver** [comment]
Challenge numbering problem resolved.
