### ISSUE TITLE
missing release notes

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder#373]
I see that this lesson has bee officially published three times in Zenodo
- [June 2016](https://zenodo.org/record/57520)
- [Feb 2016](https://zenodo.org/record/278224)
- [Aug 2017](https://zenodo.org/record/838770)

However, this GitHub repository has [0 releases](https://github.com/swcarpentry/r-novice-gapminder/releases).

I'm not sure you can go back in time and create a release, but I think it could be useful to start a NEWS.md that describes some of this history.

**Comment by jcoliver** [comment]
Resolved by June 2019 release: https://github.com/swcarpentry/r-novice-gapminder/releases
