### ISSUE TITLE
Explaining debugging in "Function Explained"? 

### ISSUE THREAD

**Issue by KlausVigo** [swcarpentry/r-novice-gapminder#378]
The lesson "Function Explained" gives a lot of nice advice how to write functions and avoid bugs. Unfortunately if I write a function I will sooner or later have to debug it. I think it  would be nice to explain shortly strategies to debug and what tools are available in R / RStudio. 

Brown & Murdoch (2016) define the following 5 steps to fix a bug:
1. Recognize that there is a bug.
2. Make the bug reproducible.
3. Identify the the cause of the error.
4. Fix the bug and test your new code.
5. search for similar errors 

I think it is worth just mentioning or referencing the functions `traceback()` and  `browser()`.  `traceback()` to identify where a bug has happened. And `browser()` sets a breakpoint in your code. I can inspect variables and see if they are valid etc. and step through the function. 
`traceback()` may be called automatically inside RStudio if a function crashes and there is a button for setting breakpoints, i.e. call `browser()`. But it is still worth while explaining how/when to use these functions/buttons. 

### References 
Braun WJ, Murdoch DJ (2016) A first course in statistical programming with R, 2nd edition, Cambridge University Press

**Comment by mawds** [comment]
It's a good point.   We all end up debugging our code at some point, and knowing how to use a debugger is a useful skill.

That said, there's already a lot of material in the episode (and in the lesson as a whole), so I'm reluctant to add more *taught* material to it.     Perhaps a callout offering brief advice on debugging and signposting the user towards, e.g. https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio would work?

**Comment by KlausVigo** [comment]
Hi @mawds 
that seems a good idea. It would probably best fit into the Tip `Testing and documenting` section of the lesson, which is so far very short and without example or exercise. I am not sure if the `Test a function` objective is achieved so far and knowing how to debug will definitely help towards this goal. 
I agree this lesson contains a lot (too many?) of important but often somehow unrelated concepts/material and has to miss many other. As an example it explains default values of arguments shortly, but not the `...` arguments. Knowing both is important for using - not even writing - a function and necessary(!) to understand the the help page of a function (and could have been introduced as early as in `Seeking Help`).

**Comment by mawds** [comment]
Are you happy to submit a pull request making the changes to the `Testing and documenting` section? (perhaps rename it `Testing, debugging and documenting` too?)

on "`...`"; you're probably best to open a new issue on this, so it doesn't get lost when this issue gets closed after the pull request is merged.

**Comment by BeccaBMaster** [comment]
Would it be valuable to split this lesson into two?  One lesson which covers what functions are, how they work, and breaks down things like default values and optional values then a separate/follow up lesson which covers how to start with writing functions including debugging?  The introduction covers mathematical functions; that may be a good spot to bridge to more complicated (multiple argument) functions.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
