### ISSUE TITLE
"ProjectTemplate" Tip is confusing and unneccessary for novice R learners

### ISSUE THREAD

**Issue by IdoBar** [swcarpentry/r-novice-gapminder#379]
Though it's been discussed previously in a few issues and pull requests (#154, #3, #15), I would like to ask again for the `ProjectTemplate` "Tip" to be completely removed from this lesson because, as mentioned before me, it causes confusion to novice R learners and raises questions like "Why do we need `bin` and `docs` folders?" and "What do I do now with all this complex folder structure?". 
All these sidetracks and drifts the lesson's flow away from the other (more relevant at that stage) introductory material.
I think that keeping a clean and ordered project structure is important, but at the very basic level, using RStudio's "New Project" menu option and manually creating `data` and `plots/output` folders is sufficient for most users and not complicating things unnecessarily.

Thanks, Ido

**Comment by jcoliver** [comment]
Thanks, @IdoBar , this is a great point. In my experience as an instructor, I have always skipped this part, as I found it distracting. The creation of `data` and `output` folders can be challenging enough for some of the participants. 

The question, though, is should we actually remove this part of the lesson? The current Instructor Training process empowers workshop instructors to adapt material to fit the audience, so it's perfectly OK to skip this section during a workshop. But I'm interested to know how other instructors feel - is this _ever_ used in a workshop?

**Comment by mawds** [comment]
I agree that it feels like it's in the wrong place.

+1 to moving it to the end of the episode, (or to the "writing better software" episode?)

**Comment by naupaka** [comment]
I also am +1 for moving it elsewhere. Agreed that it's too much too soon for an intro lesson.

**Comment by IdoBar** [comment]
@jcoliver Yes, will do it shortly.
Thanks, Ido

**Comment by mawds** [comment]
That's great - thanks for the pull requests.  I've merged them into the lesson.
(the changes won't be visible on the rendered pages until they're next rebuilt)
