### ISSUE TITLE
human.age (Exploring Data Frames - Challenge 1)

### ISSUE THREAD

**Issue by damianiji** [swcarpentry/r-novice-gapminder#383]
Hi, Folks! New instructor trainee Damian Romero here.

While practicing teaching the Exploring Data Frames part, I ran into the `human.age` variable in Challenge 1, which I think might be confusing for new learners that might think `.age` is a function since its next to `as.factor`. What do you think about sticking with an underscore as in `human_age`?
Cheers from Arizona!

**Comment by naupaka** [comment]
Yes, I agree! And that way it also follows our general preference for snake_case. I'd be happy to review a PR making that change.
