### ISSUE TITLE
adding more information on "seeking help"

### ISSUE THREAD

**Issue by p1981thompson** [swcarpentry/r-novice-gapminder#386]
I wonder if the section "seeking help" could be improved for beginners by including that ?? can be refined including "title", "keywords, "alias", or "concept", i.e. title??plot. Often we have an idea of the function or even partially remember some of the name, but cannot remember the complete name, so "title" would refine the list of results substantially and make it easier for beginners. 
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by naupaka** [comment]
That sounds useful! I didn't know about that trick. I'd be happy to review a PR adding that into the seeking help lesson.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
