### ISSUE TITLE
.gitignore does not have ignore for .Rhistory

### ISSUE THREAD

**Issue by mzc9** [swcarpentry/r-novice-gapminder#392]
or anything pertaining to R.  Appears it is mostly python related.

Should I create a PR and add it?

**Comment by naupaka** [comment]
Yep, good idea.

**Comment by naupaka** [comment]
I think the issue might be that it is actually pulled in from the styles repository, which is constant across all lessons. Is that true @rgaiacs ?

**Comment by rgaiacs** [comment]
Could you send a pull request to https://github.com/swcarpentry/styles/blob/gh-pages/.gitignore. Thanks in advance.

**Comment by mzc9** [comment]
Getting a 403 when I try to send a PR

**Comment by mzc9** [comment]
Don't have permission.  Getting a 403.

Followed the same procedure as before for creating a PR.  Should I have
done something different?

**Comment by naupaka** [comment]
How did you do it last time/this time?

**Comment by mzc9** [comment]
- cloned repo on local computer
In the terminal,
  - created a branch
 - checked out branch
Made the change via a text editor
Back in the terminal
 - git add
 - git commit -m "msg of Issue #"
- git push  --> required my github ID and password
Voila

**Comment by naupaka** [comment]
Did you fork before cloning?

**Comment by naupaka** [comment]
The gitignore change is in a different repository -- it's in the styles repository https://github.com/swcarpentry/styles, which has the styles for all of the lessons.

**Comment by mzc9** [comment]
Ah!  Got it!
Thank you.

**Comment by naupaka** [comment]
Added here: https://github.com/swcarpentry/styles/pull/286

Thanks @mzc9!
