### ISSUE TITLE
Adding explanation

### ISSUE THREAD

**Issue by ahulsekemp** [swcarpentry/r-novice-gapminder#397]
Hi new train the trainer attendee and have run into the following: 

nrow(cats) is used to investigate cats, it would follow that you could use the same command to investigate the other variable age. In this case you'll get a NULL answer as it does not work on the age vector. It may be helpful to add this and an explanation for the student to explain why this is the case. 

Cheers!

**Comment by zyqfrog10** [comment]
Good idea. nrow() is a function operating on a data frame while age is a vector. That's why you use length() to check the size of age.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
