### ISSUE TITLE
Gapminder 5-year data missing

### ISSUE THREAD

**Issue by maglet** [swcarpentry/r-novice-gapminder#399]
I tried to load the gapminder data from the URL in the tutorial (https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv) and i got an error saying the file was not found. 

Looking in the data folder in the repo, it appears that only the wide data table is there.  Can someone add the long data back?

- Tobin

**Comment by jcoliver** [comment]
Thanks, Tobin @maglet ! Working on it #400 . In the meantime, you can get the gapminder data from: https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv
