### ISSUE TITLE
Should we include plotting focused primarily on ggplot or base graphics?

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#4]
Discussion in #1 seems to indicate that many students like learning ggplot, and if they have no prior experience with base R plotting then it is not so hard to pick up. However, it also make be too much to cover along with everything else and novices will run into cases where it is helpful to understand some of how base graphics work as well. How should we focus the lessons?

**Comment by tomwright01** [comment]
I although I started with base graphics and am still discovering how to do things in ggplot I like the idea of teaching with it. My vote is to keep it in for the moment and perhaps re-consider once we have more experience teaching it.

**Comment by hdashnow** [comment]
I've noticed that the students seem to have a much better experience learning ggplot right from the start. The main thing that motivates students here is that they can get to publication quality graphics with far fewer lines of code and understanding using ggplot, compared with base.

**Comment by aammd** [comment]
my vote is for **ggplot2** all the way.

**Comment by naupaka** [comment]
Looks like we have settled on ggplot. PR #92 removed the last bit of base R plotting. I'm closing this.
