### ISSUE TITLE
Add motivational slides

### ISSUE THREAD

**Issue by aammd** [swcarpentry/r-novice-gapminder#40]
We ought to have a short [Motivational slideshow](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/LAYOUT.md#motivational-slides) that we can use at the start of a lesson. from the LAYOUT.md : 

> Every lesson must include a short slide deck in motivation.md suitable for a short presentation (3 minutes or less) that the instructor can use to explain to learners how knowing the subject will help them. 

I was thinking that #37 would make really great material for such a thing. The original authors could work on that, or if people agree we can merge that in and someone else can make it into slides 
cc @hdashnow @SamPenrose

**Comment by SamPenrose** [comment]
I am working on this today.

**Comment by naupaka** [comment]
It looks like #37 and #45 have been merged and so can we close this issue?

**Comment by aammd** [comment]
Indeed! closing.
