### ISSUE TITLE
introduction of `ggsave` command missing?

### ISSUE THREAD

**Issue by cengel** [swcarpentry/r-novice-gapminder#401]
In http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/11-writing-data/, the following reference is made at the beginning the episode:

> You have already seen how to save the most recent plot you create in ggplot2, using the command ggsave. As a refresher:

> `ggsave("My_most_recent_plot.pdf")`

I don't seem to be able to find where else `ggsave` is explained before this episode. Two options: 

* reword this section and introduce `ggsave` in the "Writing Data" episode 
* add mention of `ggsave` at the end of the "Creating Publication-Quality Graphics" chapter (8-plot-ggplot2.Rmd). 

I am happy to create a PR but wanted to make sure I am not missing anything and also see if there are any preferences as of where it should go.

**Comment by naupaka** [comment]
Good catch! I think it would be better to add in at the end of episode 8 (the ggplot chapter). That keeps the primary focus on writing data in episode 11. PR definitely welcome.

**Comment by mawds** [comment]
I'll close this, since it was fixed in #403
