### ISSUE TITLE
[Data Structures] Use the “sep” parameter of the read.csv() function

### ISSUE THREAD

**Issue by mariakotouza** [swcarpentry/r-novice-gapminder#404]
At the beginning of the episode "Data Structures" you teach how to read tabular files:

> The read.csv function is used for reading in tabular data stored in a text file where the columns of data are delimited by commas (csv = comma separated values). Tabs are also commonly used to separated columns - if your data are in this format you can use the function read.delim. If the columns in your data are delimited by a character other than commas or tabs, you can use the more general and flexible read.table function.

The read.csv() function can be used to read any kind of tabular files and not only comma separated files, by setting the “sep” parameter equal to the delimiter of the file. I find it very useful to use only the read.csv() function for reading this kind of data instead of trying to remember a different function for each delimiter.  

So, for example, if we had the file feline-cat.txt and the columns were separated by tabs, we could use the following command:

cats <- read.csv(file = "data/feline-data.txt", sep="\t")

**Comment by jcoliver** [comment]
Thanks @mariakotouza ! This is a good point about the flexibility of `read.csv`. I'm not sure we need to introduce a discussion of this functionality at this point in the lesson, as learners have not had much exposure to function parameters. But it warrants further discussion. Thoughts, @mawds and @naupaka ?

**Comment by naupaka** [comment]
My personal opinion is that even though you can override the defaults of `read.csv()`, which is itself just `read.table()` with different defaults, it makes the code a little more readable/intuitive to not have `read.csv()` read in `tsv` files.

**Comment by jcoliver** [comment]
We are making significant revisions to episodes 4 and 5 given recent changes introduced by R 4.0. Please feel free to re-open if warranted.
