### ISSUE TITLE
access problems with url

### ISSUE THREAD

**Issue by nairps** [swcarpentry/r-novice-gapminder#406]
The url for 'base plotting system' (https://www.statmethods.net/graphs/) from the subsection 'Creating Publication-Quality Graphics' (https://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/08-plot-ggplot2/) is not accessible.

working url: https://www.statmethods.net/graphs/index.html

**Comment by jcoliver** [comment]
Thanks, @nairps ! Want to submit a PR with the fix?

**Comment by naupaka** [comment]
Fixed by #409
