### ISSUE TITLE
data file gapminder-FiveYearData.csv missing

### ISSUE THREAD

**Issue by mkuzak** [swcarpentry/r-novice-gapminder#407]
'gapminder-FiveYearData.csv' is reference in the lesson (version 2016.06) but is not available in the lesson.
I have found a relevant dataset [here](https://github.com/resbaz/r-novice-gapminder-files/blob/master/data/gapminder-FiveYearData.csv). I can make a pull request fixing this, but I don't know how to get it to the release version.

**Comment by jcoliver** [comment]
Thanks @mkuzak This was also brought up in #399 and ideally resolved in #400 , once that gets pushed to production.

**Comment by mkuzak** [comment]
thank you, I missed that.
