### ISSUE TITLE
Suggest to change title to dataset

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-gapminder#410]
Hi!

This is a minimal change that makes sense and won't affect the teaching structure.
I suggest to change the name `gapminder-FiveYearData.csv`  to `gapminder-data.csv` 
Why?
- For instance there are more than 5 years in the dataset, hence the name is misleading
- Second, having name conventions is good practice for beginners. We can avoid the use of capitalization when not using CamelTitles 

Change should be addressed here:
https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/data

Thanks!

**Comment by jcoliver** [comment]
Thanks, @orchid00 ! This is a good point. The file name is a bit of a legacy from the previous source. Since we now include this file on this repository, I don't know of a reason to change the name to something simpler (dashes _or_ camel case, but probably not both). Thoughts @naupaka & @mawds ?

**Comment by naupaka** [comment]
If we are changing the name I suggest changing it to `gapminder_data.csv`. That way it matches the general tidyverse style recommendation for snake case when possible. I agree no reason to keep `FiveYearData` in there.

**Comment by orchid00** [comment]
yay, done!

**Comment by orchid00** [comment]
Before closing this issue, I suggest all the links referencing the data set should be checked.
particularly 
the instructor guide
http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/guide/

**Comment by jcoliver** [comment]
Good point, @orchid00 . Want to update the PR? The file corresponding to the instructors guide is `_extras/guide.md`.

**Comment by orchid00** [comment]
I could do that.
But first my [PR](https://github.com/swcarpentry/r-novice-gapminder/pull/411) seems to be still on waiting list and I rely on this to teach a workshop on Monday-Tuesday. 

All next week I will be busy to work on the guide.

**Comment by orchid00** [comment]
This is nor for checkout

**Comment by orchid00** [comment]
Thanks @jcoliver , 

this is not for checkout

**Comment by naupaka** [comment]
Thanks @orchid00 !!!

**Comment by naupaka** [comment]
See also #411

**Comment by naupaka** [comment]
Closed by #416 and #411
