### ISSUE TITLE
Tip: Running segments of your code

### ISSUE THREAD

**Issue by denironyx** [swcarpentry/r-novice-gapminder#412]
The keyboard shortcuts to run the current line for windows is **ctrl** and **Enter** not **ctrl** and **Return** . **ctrl** and **Return** is the keyboard shortcut for Mac computers. 

https://datacarpentry.org/r-intro-geospatial/01-rstudio-intro/index.html

Thanks!

**Comment by jcoliver** [comment]
Thanks, @denironyx . Would you submit a PR with this change?
