### ISSUE TITLE
Adding the rm() function to the workshop material

### ISSUE THREAD

**Issue by denironyx** [swcarpentry/r-novice-gapminder#413]
I think, the knowledge of how to remove object value from variable should be introduce to the workshop materials. 

**rm()** or **remove**
remove and rm can be used to remove objects. These can be specified successively as character strings, or in the character vector list , or through a combination of both. All objects thus specified will be removed. If envir is NULL then the currently active environment is searched first.

To remove everything in the memory environment of the Rstudio and R, you can say: **rm(list = ls())**

**Comment by jcoliver** [comment]
Thanks for the suggestions, @denironyx ; this is covered in the first episode under the "Managing Your Environment" section: [http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/01-rstudio-intro/#managing-your-environment](http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/01-rstudio-intro/#managing-your-environment).
