### ISSUE TITLE
Tip: Running segments of your code

### ISSUE THREAD

**Issue by denironyx** [swcarpentry/r-novice-gapminder#414]
Hi,

I have been working with the Rmarkdown for some time now. While taking a look at the R for reproducible scientific analysis. 

I happened to realize that some tips were not included in the course materials http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/15-knitr-markdown/.

Tips like, to load new code chunk. The keyboard shortcut **Ctrl + Alt + I** for windows OS  and OS X: **Cmd + Option + I**. 

Thanks

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
