### ISSUE TITLE
Add numbering to episodes

### ISSUE THREAD

**Issue by unode** [swcarpentry/r-novice-gapminder#419]
This is a minor improvement but useful when referring to different episodes of the same lesson.

Most other lessons now make use of numbered episodes. For instance in [UNIX Shell](http://swcarpentry.github.io/shell-novice/) the number preceeds the episode name.

Could this be added to this lesson? Both for usability and consistency with other lessons.

**Comment by jcoliver** [comment]
Thanks for the suggestion, @unode . Do you mean the episodes should be numbered in the schedule? The corresponding episode files are all prefixed with such a number, although this does not show up in the schedule on the lesson home page.

**Comment by unode** [comment]
### Yes, precisely.

#### In http://swcarpentry.github.io/shell-novice/ one sees:
![screenshot_2018-08-28_18-21-52_495485511](https://user-images.githubusercontent.com/122319/44736352-49640f00-aaef-11e8-8034-ae350d07020e.png)

#### Whereas in http://swcarpentry.github.io/r-novice-gapminder/ we have:
![screenshot_2018-08-28_18-21-41_128187155](https://user-images.githubusercontent.com/122319/44736355-4e28c300-aaef-11e8-89c0-8b6b801bad9a.png)

----

#### Additionally wondering if these numbers would also be useful in the drop-down menu at:
![screenshot_2018-08-28_18-25-21_913663132](https://user-images.githubusercontent.com/122319/44736532-c98a7480-aaef-11e8-8c3f-5e11eb535897.png)

#### but this was not in scope of the initial suggestion above.

No other lesson has numbers in the drop-down menu either so in terms of consistency they would have to be adjusted too.

**Comment by jcoliver** [comment]
Resolved.
