### ISSUE TITLE
Update MAKEFILE to check knitr version

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#42]
`make preview` will only compile the code blocks in the challenges and callouts correctly if knitr is version 1.10.12 or higher. Currently, this requires installing from github: (devtools::install_github("yihui/knitr")).

I've written an R script that will throw an error if the knitr version is too low (`tools/check_knitr_version.R`) in Pull Request #41 , but I wasn't able to successfully incorporate it into the Makefile to prevent future contributors from clobbering the code block rendering.

**Comment by sritchie73** [comment]
Thoughts on this approach @jdblischak ? Does r-novice-inflammation have code blocks in any of its challenges?

**Comment by aammd** [comment]
Moving this discussion over to the lesson-template repo. Hopefully we will be able to change the One True Makefile to support this behaviour, and then I will include those changes here.

**Comment by jdblischak** [comment]
I think this issue can be closed now that the following PR has been incorporated into the lesson-template:

https://github.com/swcarpentry/lesson-template/pull/271

**Comment by naupaka** [comment]
Yup. Good call.
