### ISSUE TITLE
Clarify that "invalid factor level: NA generated" is a warning and not an error, and that rbind () is still executed

### ISSUE THREAD

**Issue by budell** [swcarpentry/r-novice-gapminder#420]
---
Hi I am a new Instructor trainee and I have been working in the "Working with data frames lesson" (lesson 5). The lesson has the participant use rbind to merge a new row to a dataframe, however, the input for coat variable is not one of the factor levels, which throws a warning and generates an NA value:

newRow <- list("tortoiseshell", 3.3, TRUE, 9)
cats <- rbind(cats, newRow)

Warning in `[<-.factor`(`*tmp*`, ri, value = "tortoiseshell"): invalid
factor level, NA generated 

The lesson then goes on the explain the warning was generated because tortoiseshell was not a pre-defined level in coat, and next shows the participant how to add levels.  However, due to the red text and the lack of explanation that the warning was not an error, it is easy to miss that rbind() was still executed and an NA was put in place of the undefined factor level. I think it would be easy to point this out here, which can be demonstrated by printing cats.  

Instead, the lesson then goes on to explain more about factors, using the str function, and converting factors to characters before "cats" is printed out we the learner sees there is an extra row which they are instructed to remove.  As I worked through this, it was not clear at first where the extra row had come from.  

---

**Comment by jcoliver** [comment]
Thanks @budell and welcome! A good point about skipping over the ramifications of the `rbind` call. The lesson does show that extra row, but this occurs after the description of factors and level. We'd be interested to see what a revised version might look like. Care to submit a PR?
