### ISSUE TITLE
to update the path of gapminder/gapminder_wide dataset

### ISSUE THREAD

**Issue by StanleyYang01** [swcarpentry/r-novice-gapminder#423]
1. In the **Exploring Data Frames** chapter (http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/05-data-structures-part2/), the web path for downloading gapminder is NOT correct. 

Original Path: 
gapminder <- read.csv("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder-FiveYearData.csv")

To be updated to: 
gapminder <- read.csv("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder_data.csv")

2. In the **Dataframe Manipulation with tidyr** chapter (http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/14-tidyr/), it would be nice to add a weblink for downloading the gapminder_wide.csv file in addition to the local path: gap_wide <- read.csv("data/gapminder_wide.csv", stringsAsFactors = FALSE)

To be added: 
gap_wide <- read.csv("https://swcarpentry.github.io/r-novice-gapminder/data/gapminder_wide.csv")

**Comment by naupaka** [comment]
Fixed by #424 

Sorry for the hassle @StanleyYang01
