### ISSUE TITLE
Since rendered pages are pointing to 2016.06 release, new filenames in code won't update

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#425]
I put the old named files back into the repo (see 6f5dd6f031014a861d28bfe9c0124228387313bc) so that the links will keep working. When the next lesson release happens, then the new links will all work as well, and we can delete the old files (FiveYearData). 

cc @jcoliver @orchid00 @fmichonneau

**Comment by orchid00** [comment]
Thanks @naupaka , Seems like a good solution.

Just curious, when is the next lesson release?

**Comment by naupaka** [comment]
I am pretty sure the pages should be pointing to 2017.08 at least. Not sure where the glitch is. Maybe @rgaiacs knows?

**Comment by rgaiacs** [comment]
> Not sure where the glitch is.

I didn't work on the feature to rendering pages point to YYYY.MM release. Sorry that I can't help much.

**Comment by naupaka** [comment]
I think now it's working? 

http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html is the new version

**Comment by jcoliver** [comment]
Appears resolved.
