### ISSUE TITLE
Add R Markdown work flow to 01-rstudio-intro

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#427]
http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html has

> There are two main ways one can work within RStudio.
>
> 1. Test and play within the interactive R console then copy code into a .R file to run later.
> 2. Start writing in an .R file and use RStudio’s short cut keys for the Run command to push the current line, selected lines or modified lines to the interactive R console.

What about add R Markdown work flow? I know that it is a variant of the R script workflow but for beginners might worth mention it.

**Comment by jcoliver** [comment]
Thanks for the suggestions, @rgaiacs . I worry a little about adding to the cognitive load of our audience at this point. The nuanced difference between point #2 (R scripts) and an R Markdown workflow, which proceeds much the same way (write R code, push the current line, selected lines, modified lines, current block, selected blocks, or modified blocks to the interactive R console) might be unnecessarily distracting at this point. But I'd still be interested to know what point #3 would look like...

**Comment by carmelwoods** [comment]
@rgaiacs I had the same thought when I was preparing to teach this lesson. But now that I've taught it a couple of times, I can see how it's better to delay the introduction of R Markdown to the later section [Producing reports with knitr](http://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html). I think one or two new concepts at a time is all people can handle.

**Comment by mawds** [comment]
I agree with @carmelwoods  and @jcoliver - I think it adds too much cognitive load at the start of the course 

(especially if users save their notebooks in a subdirectory off the project directory - which the "good enough practices for scientific computing in http://swcarpentry.github.io/r-novice-gapminder/02-project-intro/index.html implies they should. The `.Rmd` file takes its location as its working directory, which can be confusing).

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
