### ISSUE TITLE
Mac Command key

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#428]
http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html says

```
hit <kbd>Ctrl</kbd>+<kbd>Return</kbd> in Windows or Linux or <kbd>⌘</kbd>+<kbd>Return</kbd> on OS X.
```

but http://carpentries.github.io/lesson-example/06-style-guide/index.html recommends to say

```
hit <kbd>Ctrl</kbd>+<kbd>Return</kbd> in Windows or Linux or <kbd>Command</kbd>+<kbd>Return</kbd> on OS X.
```

The reasons why I decided to use `<kbd>Command</kbd>` instead of `<kbd>⌘</kbd>` are (1) text to speak might better read the word instead of the symbol and (2) type the word doesn't require knowledge of how to insert special characters.

**Comment by jcoliver** [comment]
Good idea. Is there potential for confusion/conflict with non-English keyboards, though? Is there a way to keep the key name and the symbol?

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
