### ISSUE TITLE
Replace OS X with macOS

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#429]
http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html says

> on OS X

but Apple re-branded their OS to macOS, see https://en.wikipedia.org/wiki/MacOS.

**Comment by jcoliver** [comment]
But would anyone who has a pre-Sierra Mac be confused by this? Is OS X El Capitan now called macOS El Capitan?

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
