### ISSUE TITLE
Example improvement suggestion for 04-data-structures-part1

### ISSUE THREAD

**Issue by selcant** [swcarpentry/r-novice-gapminder#432]
Hi, 
The example in 'Data Structures' under 'Data Types' that uses the file "data/feline-data_v2.csv" is confusing. Since the error is due to the change of the column's class from numeric to factor rather then the change in data type from double to integer. The explanation under the example also highlights the coercion of double to integer rather than numeric to factor. When the file is read, not all the elements of the column are numeric hence R forces them to be strings which are further converted to factors --this can be prevented by using stringsAsFactors=F in read.csv. Hence, the example and its explanation seems to be misleading. It can be updated and moved after the 'Vectors and Type Coercion' subsection and used to introduce the 'class' function and factor/numeric data types/classes. It can act as a transition to the 'Factors' subsection which comes next.

**Comment by carmelwoods** [comment]
@selcant  I agree that section is confusing, so when I taught it I replaced it with the following, but I like your idea too.
`cats$age <- c(2,5, 'unknown')`
`typeof(cats$age)`
`cats$age + 2 `

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
