### ISSUE TITLE
link to wrong version of the data

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/r-novice-gapminder#433]
Dear friends,
in your document with url

https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/index.html

in sentencec"Download the gapminder data from here." you have bad link to file.
Your link is pointed to wide format of data

https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_wide.csv

but you ment long data:

https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv

Best wishes
Marek Pomp

**Comment by jcoliver** [comment]
Thanks, @ErinBecker . Should be addressed by #434

**Comment by ErinBecker** [comment]
Wow! Fast response! Thanks @jcoliver

**Comment by naupaka** [comment]
Good catch
