### ISSUE TITLE
Exploring Data Frames - Challenge 1

### ISSUE THREAD

**Issue by Khojanator** [swcarpentry/r-novice-gapminder#439]
Hey, this is Ahsan Ali Khoja from Oct 10/11 EST trainee workshop.

Question 1 in challenge 1 seems a little ambiguous. What is the vector human_age representing? Is the question referring to human age in cat years? Shouldn't we divide by 7 instead of multiplying by 7? (of course, it depends on how you define this vector). I've posted the link below:

https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/_episodes_rmd/05-data-structures-part2.Rmd#challenge-1

**Comment by jcoliver** [comment]
Good point, @Khojanator . Perhaps this challenge would be improved by restating the first line:
> Let's imagine that 1 cat year is equivalent to 7 human years.

**Comment by Khojanator** [comment]
That should solve the problem! I'll go ahead and suggest this change.
