### ISSUE TITLE
Introduce summary() to inspect gapminder dataset in lesson 05-data-structures-part2

### ISSUE THREAD

**Issue by DiogoVeiga** [swcarpentry/r-novice-gapminder#445]
Currently the lesson uses `str()`  to inspect the structure of data frames. Another quite useful function is `summary()`, which permits one to understand both structure and data contents of a given data frame. Moreover, `summary()` is a generic implemented by several classes in R (i.e. linear models). 

For instance, `summary(gapminder)` describes the number of measurements per country and continent, as well as min, max and averages for numeric columns of the data frame. 

Thus, I suggest introducing summary() along with str() to inspect gapminder in order to provide a better description of the dataset for learners. A better grasp of this dataset will also facilitate the interpretation of the graphics generated in the ggplot2 lesson.

```r
str(gapminder)
summary(gapminder)
```
Alternatively, this function could be introduced within Challenge 5, to allow students to interpret the output of `summary(gapminder)`.

**Comment by naupaka** [comment]
Thanks! No rush. Happy to help out if you get stuck or have questions.

**Comment by anuj2054** [comment]
This issue has been solved in https://github.com/swcarpentry/r-novice-gapminder/pull/455 and should be closed

**Comment by naupaka** [comment]
Thanks @anuj2054 !
