### ISSUE TITLE
Suggestion to use alternative data for 08-Creating Publication-Quality Graphics with ggplot2 to avoid plotting genocides

### ISSUE THREAD

**Issue by BarshisLab** [swcarpentry/r-novice-gapminder#456]
Hi Folks,
    During a recent workshop I noticed that gapminder dataset used for some of the R lessons had the unfortunate result of plotting life expectancy vs. year by country, highlighting three of the lowest values in Cambodia in 1977 and in Rwanda in 1992 and 1997. 

![](http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-lifeExp-line-1.png)

I know these are real data and the gapminder dataset is used a lot throughout this entire lesson, but I thought it was worth considering whether we want to avoid explicitly highlighting such traumatic world events as the Cambodian Kmer Rouge (1975 - 1979) and Rwandan (1990s) genocides.

Especially as the carpentries expands its workshops across the African continent, it might be worth considering using a different aspect of the gapminder dataset for these lessons or a different dataset altogether to avoid potential triggers of past traumatic events.

I don't want to sound overly politically correct here, but think it may be worth considering just avoiding data that highlight such traumatic world events to make the curriculum as motivating, inclusive, and apolitical as possible. It looks like the actual gapminder r library only includes this data, so this would require a big effort to re-write the lessons using a different dataset. Alternative suggestions would one of the many default datasets included in the basic R installation (accessible using the `data()` command). Maybe this could be an iterative, collective effort to swap out individual commands/portions of the lesson bit by bit.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
