### ISSUE TITLE
write.csv wrapper for write.table

### ISSUE THREAD

**Issue by jpiaskowski** [swcarpentry/r-novice-gapminder#457]
For the section on [writing files](https://swcarpentry.github.io/r-novice-gapminder/11-writing-data/index.html), is it worth mentioning that wrappers exist to simplify options - like write.csv()?

**Comment by jcoliver** [comment]
Given the brevity of this section, and that we _only_ use a .csv file, perhaps we could switch over to `write.csv` entirely? The `read.table` function mentioned in this episode (11) hasn't been used since episode 4; additionally, the most recent (in episode order) read-in function is actually `read.csv` (episode 5).

**Comment by jpiaskowski** [comment]
I think there is value in introducing write.table (many users likely work with .txt files), but also indicating that wrappers like write.csv() exist and why someone might want to use that.

**Comment by ajax-2018** [comment]
R for Reproducible Scientific Analysis; Section 11: Writing Data

I think that the end of the "Writing Data" subsection (between the line "That looks better!" and challenge 2) would be a good place to mention the existence of wrappers for write.table. 

Something as simple as:
"As with the read.table function, write.table has the wrapper write.csv to simplify writing data in CSV format."

Then an alternative write.csv solution could be added to challenge 2
``write.csv(  gapminder[gapminder$year > 1990, ], file = "cleaned-data/gapminder-after1990.csv", quote = FALSE, row.names = FALSE)``

**Comment by jpiaskowski** [comment]
okay, submitted....I think. I probably need a Software Carpentry lesson on proper use of Git!
