### ISSUE TITLE
':' operator

### ISSUE THREAD

**Issue by jpiaskowski** [swcarpentry/r-novice-gapminder#458]
':' operator for a sequence operator is first used in section 4, then formally introduced in section 6. Should this be the case or should it be explained in section 4?

**Comment by jcoliver** [comment]
What do you think, @naupaka & @mawds ? I'm fine leaving a formal explanation for section 6...

**Comment by naupaka** [comment]
I think it's probably a simple enough thing that the explanation can wait a few sections. I also imagine many instructors explain it a bit in their own words when they first show it.

**Comment by mawds** [comment]
I think it's fine as it is.  I tend to demo it with a couple of examples when I first introduce it.  Most learners seem to get the idea of it pretty quickly.   

As we're in agreement I'l close the issue.
