### ISSUE TITLE
ambiguous wording for while statement tip

### ISSUE THREAD

**Issue by jpiaskowski** [swcarpentry/r-novice-gapminder#459]
A tip in section 07 on while loops reads:

`You have to be particularly careful that you don’t end up in an infinite loop because your condition is never met.`

Should this read:

`You have to be particularly careful that you don’t end up in an infinite loop because your condition is always met (and hence never terminates).`

?

**Comment by jcoliver** [comment]
This entire Tip section on `while` loops could use a revision. It is currently a bit challenging from the start. i.e. if a condition evaluates as `TRUE`, does that mean the condition is met or not met? From the pseudocode, it seems if the condition in the `while()` command evaluates as `TRUE`, the condition controlling while loop execution is _not_ met. Using different words (like "statement" in the pseudocode?) might clear things up.

**Comment by jpiaskowski** [comment]
Are you asking for clarification from me or from an actual content manager? Since it's an entry-conditioned control statement, whenever a while statement evaluates to TRUE, the condition is met and the expression will be evaluated.
