### ISSUE TITLE
Section 7, Challenge 4 & 5 suggestions

### ISSUE THREAD

**Issue by jpiaskowski** [swcarpentry/r-novice-gapminder#460]
Challenges 4 & 5 are very difficult because the solutions expect four functions not previously introduced:

with()
subset()
mean()
cat()

The use of 'subset' is particularly confusing since the previous section is titled "Subsetting", yet does not introduce subset() at all. Is this intended for advanced users? I am skeptical that true R novices will be able to complete these exercises.

Here is the original solution:

`
for( iContinent in unique(gapminder$continent) ){
   tmp <- mean(subset(gapminder, continent==iContinent)$lifeExp)
   cat("Average Life Expectancy in", iContinent, "is", tmp, "\n")
   rm(tmp)
}
`

I think it can be completed using existing knowledge and only introducing mean() and cat() as hints. 

`
for( iContinent in unique(gapminder$continent) ){
  tmp <- gapminder[gapminder$continent == iContinent, ]
  cat(iContinent, mean(tmp$lifeExp, na.rm = TRUE), "\n")
  rm(tmp)
`

I would introduce na.rm = T since users are quite likely to eventually be tripped up by NA handling. 
I would also consider introducing cat in the very first section of the workshop as a "Hello World" incantation:

`
cat("Hello World")
`

**Comment by jcoliver** [comment]
Great points, @jpiaskowski . Updating challenges 4 & 5 with solutions that do not involve `subset` and `with` sounds like a good idea.

**Comment by jpiaskowski** [comment]
okay, I'll prep another pull request for this.

**Comment by jcoliver** [comment]
Addressed in #472
