### ISSUE TITLE
Clarification of difference between count() and n() in dplyr lesson

### ISSUE THREAD

**Issue by ka-west** [swcarpentry/r-novice-gapminder#470]
Hi everyone! Happy to be joining the swcarpentry community :)

At a workshop I was teaching recently, there was some confusion about the difference between functions `count()` and `n()`. From the `dplyr` lesson:

*"...if we wanted to check the number of countries included in the dataset for the year 2002, we can use the `count()` function. It takes the name of one or more columns that contain the groups we are interested in..."*

*"If we need to use the number of observations in calculations, the `n()` function is useful."*

I was thinking it might be worth mentioning that `n()` does not call `group_by()` before counting observations as `count()` does. Thoughts?

**Comment by jcoliver** [comment]
Thanks, @ka-west . I agree more explanation of `n()` is warranted. I'm not sure that we need to go into details about explicit and implicit use of `group_by()`, but we would welcome a pull request.

**Comment by ka-west** [comment]
@jcoliver just submitted a pull request, hope I did it right!
