### ISSUE TITLE
Specify `mapping` in the ggplot2 episode?

### ISSUE THREAD

**Issue by ha0ye** [swcarpentry/r-novice-gapminder#473]
I like the approach of the data carpentry R ecology lesson where the `mapping` named argument is explicitly specified for ggplot2. This assists with distinguishing the different layers and maybe also with explaining what's occurring under the hood (rather than a "magical" `aes()` function).

**Comment by mawds** [comment]
It's a good point, and would, I think make it clearer what the "point" of `aes()` is, especially at the start of the episode.  I know I emphasise that `aes()` is a "mapping" when I'm teaching it, and I think this would make it clearer.

**Comment by naupaka** [comment]
I agree with this too. When people are learnings, it's always helpful to be explicit at first with the naming of arguments.

**Comment by jcoliver** [comment]
Resolved with #492
