### ISSUE TITLE
Begin transition to Travis builds of the repo instead of maintainer to GH Jekyll

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#476]
@mawds @jcoliver 

We are one of the last holdouts using the old system of rendering the Rmd to md. The new system uses Travis to watch master, render any new commits to md and html and push to gh-pages for hosting. To get ready for that, we'll have to merge or close all existing PRs, which is going to be a bit of a task, but I think we need to do it at some point soon so this repo is on the same page as the others. Plus then we won't have to manually re-make the md after merging changes.

From @fmichonneau:

> The catches are that the documentation on the repo needs to be updated to reflect the changes in the names of the branches, that master is now the default, etc... Because open PRs are open against gh-pages, they'll also all need to be closed/merged before the change happen otherwise they'll have to be rebased against master which I think is a little tricky

**Comment by mawds** [comment]
How do you want to divide them up between us? I took a look at the two oldest PRs and they seem to be so far diverged from the current lesson I think we might have to just close them.  I merged the third oldest, whose conflicts were easier to fix.

What's the timescale for getting them all done?

**Comment by naupaka** [comment]
Good question. Might be easiest to schedule an hour conference call sometime for the three of us and just work through them in sequence. No particular rush to get them handled, I was thinking perhaps in the next month or two?

**Comment by mawds** [comment]
Sounds like a plan - I'll email you a few good dates/times

**Comment by naupaka** [comment]
@fmichonneau We've closed all the PRs, and I think we're ready to move this to Travis!!

**Comment by fmichonneau** [comment]
you're all set!

Default branch is now 'master', 'gh-pages' is an orphan branch managed by Travis-CI.

I'll let you:

- [ ] add the travis badge
- [ ] update the documentation (where relevant).
