### ISSUE TITLE
Remove feline-data_v2.csv

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#479]
Per #471, consider removing all references to the cats version 2 data.

**Comment by anuj2054** [comment]
Maybe just adding this code in the section where it asks us to download the file might help. 
Or I can go ahead and delete the whole section.

```
cats <- data.frame(coat = c("calico", "black", "tabby","white"), 
                    weight = c(2.1, 5.0,3.2,2.1 or 2.2), 
                    likes_string = c(1, 0, 1,1))
write.csv(x = cats, file = "data/feline-data_v2.csv", row.names = FALSE)
```

**Comment by dkcoxie** [comment]
Taught this lesson for the first time and found the feline_v2.csv reference very confusing. I think it should removed. If a 'badly' behaved data frame is included, I think it would fit better as an example in an example in 02-project-intro, as something that can be downloaded, changed in a text editor, and then loaded into R to demonstrate the how best practices of project organization/data analysis can help them avoid errors/issues.

**Comment by jcoliver** [comment]
We are making significant revisions to episodes 4 and 5 due to changes introduced by R 4.0. Please feel free to re-open as warranted.

**Comment by ericward** [comment]
This still seems not to have been addressed?
