### ISSUE TITLE
Improve prerequisites

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#48]
We have

> Have attended the Shell and Git sessions.

as prerequisites and I think that we can

- [ ] reword the Shell requisite to something like "understand the concepts of files and directories (including the working directory)",
- [ ] drop the Git requisite since learners will only need it at https://swcarpentry.github.io/r-novice-gapminder/02-project-intro.html.

**Comment by karawoo** [comment]
I agree. The workshops I've done have always started teaching R before teaching git, and often before teaching the shell. I'd even be fine with dropping the requirement that they understand directories and just be prepared to lead learners through these concepts at some point during the R lesson.

**Comment by BernhardKonrad** [comment]
+1

**Comment by jrnold** [comment]
Git is also referenced in the instructor's guide as the easiest way for attendees to get the data.
