### ISSUE TITLE
dplyr::arrange referenced in challenge section without being introduced

### ISSUE THREAD

**Issue by anuj2054** [swcarpentry/r-novice-gapminder#482]
The `dplyr::arrange` function is being asked to be used by the students for a challenge. The students are only given a hint to use `arrange`.

I think even with `arrange` being introduced in the text earlier, this could count as an advanced challenge to a student who is just being introduced to `dplyr`.

I think time can be conserved in this episode by removing or shortening the section on `count` or `n` ; but rather introducing `arrange` as one of the last six `dplyr` operations.`

If the board agrees on this, I can try to put in the stuff for `arrange` in the text.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
