### ISSUE TITLE
Change theme code in ggplot episode from removing axis labels to simply rotating them

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#484]
I don't think we should ever encourage folks to make plots without x axis labels, which is what happens in this example. 

https://github.com/swcarpentry/r-novice-gapminder/blob/f3d5c959a39de2b4d9d9f6927523e8a969427004/_episodes_rmd/08-plot-ggplot2.Rmd#L352

I propose that we replace the code to remove labels and tick marks 

```r
theme(axis.text.x=element_blank(), axis.ticks.x=element_blank())
```

with code to make the labels vertical (so they don't overlap)

```r
theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

**Comment by ksamuk** [comment]
Hi! I agree with this wholehearted and created a pull request to address this here. https://github.com/ksamuk/r-novice-gapminder/pull/1#issue-267941128 

Thanks!

**Comment by naupaka** [comment]
@ksamuk thanks! Can you submit the PR against the master branch in this repository? It looks like the PR is on your fork.

**Comment by ksamuk** [comment]
My bad, I redone here: https://github.com/swcarpentry/r-novice-gapminder/pull/493
