### ISSUE TITLE
Start preparing for June 18th lesson release

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#485]
It's been a while - probably time to do a formal release. Before June 18th, we should: (via @ErinBecker) "check and confirm that all code blocks, exercises, and solutions working as expected. [We] *do not* need to resolve all existing Issues and PRs before releasing [the] lesson".

**Comment by jcoliver** [comment]
@naupaka @mawds An April meeting to disucs this? Or perhaps a collaborative document (here or on Google) to divide and conquer tasks?

**Comment by naupaka** [comment]
Good idea. Perhaps both.

**Comment by naupaka** [comment]
Superseded by #496
