### ISSUE TITLE
Need to update contributing.md to reflect new master branch Travis system

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#488]
Because the current version is now out of date. cc @mawds @jcoliver

**Comment by mawds** [comment]
Should this be an issue for the styles repository?  That still shows `gh-pages` in it's [CONTRIBUTING.md](https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/CONTRIBUTING.md)

**Comment by naupaka** [comment]
Good question. @fmichonneau @rgaiacs ?

**Comment by rgaiacs** [comment]
@naupaka and @mawds Thanks for the issue. As far as I know, The Carpentries never make the migration to use `master` instead of `gh-pages`. This was because of the extra step in settings required to have the lesson built by GitHub Pages.

I believe that @fmichonneau was investigating ways to use Travis CI to make the build of the lesson but I'm not aware of progress on it. Sorry.

**Comment by fmichonneau** [comment]
You can edit the file in your repository.

The CONTRIBUTING file in the styles is actually not part of the template that gets updated with new releases. It's only part of the files that populate the repo when first creating the lesson.

**Comment by naupaka** [comment]
Thanks @fmichonneau. I can get to this in a couple days.

**Comment by fjuniorr** [comment]
I've submitted PR #539 to fix this. However, for me, the confusion came from following the [guide](https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#option-2---use-a-command-line-interface-with-git) mentioned in the [The Carpentries Handbook](https://docs.carpentries.org/topic_folders/maintainers/contributing.html) for novice contributors.

Not really sure in how to best clarify this.

**Comment by naupaka** [comment]
I have reopened this to keep the thread, it seems like we need to deal with the Carpentries Handbook issue. @fmichonneau how would you like us to move forward on this? Can we just add some additional detail to the handbook?

**Comment by fmichonneau** [comment]
>  Can we just add some additional detail to the handbook?

That would be great if someone could do a PR to update the info on the handbook for R-based lessons.
