### ISSUE TITLE
Plot example as soon as possible

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#49]
## Summary

Something that I love about Software Carpentry lesson the first time that I read it is to mention plots as soon as possible and I think this will be a great improve to R Gapminder lesson.

## Description

Add a "motivational" topic before `01-rstudio-intro.md`. Something like: "At `data/gapminder-FiveYearData.csv` you will find some information about many countries. Get the population of X and create a plot of it using `plot(c(P1, P2, P3, ..., PN)`. Congrats, you just wrote your first R code and create a plot with it. Can you plot the population of Y? And the population for all the countries in less than one minute? In the next chapters you will learn a few things about R and at the end you will be capable to create a plot for each country in less than one minute."

**Comment by jeremycg** [comment]
plus one for this, the lesson is a little lacking in motivational examples - the learners as are thinking why are they learning about data types, but not how to graph yet.

**Comment by BernhardKonrad** [comment]
+1. This would also add a "story" to the lesson, which is currently missing until very late.

**Comment by tomwright01** [comment]
Closed by #132 
Thanks
