### ISSUE TITLE
Episode 15 (knitr) challenges are missing solutions

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#500]
Need to add solutions to the challenges in episode 15

**Comment by mawds** [comment]
needed for issue #496

**Comment by jcoliver** [comment]
Formatting Rmarkdown so it ends up rendered as markdown requires some contortions using some fairly specific back-ticking. An example of this can be found at [https://github.com/jcoliver/learn-r/blob/gh-pages/005-intro-knitr.Rmd](https://github.com/jcoliver/learn-r/blob/gh-pages/005-intro-knitr.Rmd).

**Comment by naupaka** [comment]
See also #515 #516

**Comment by naupaka** [comment]
and #518

**Comment by naupaka** [comment]
@kbroman's solution for the win! Now sure how the magic wizardry was figured out but the incantation works. https://gist.github.com/kbroman/ca560b967b0b7a08a3b2
