### ISSUE TITLE
correcting grammatical and punctuation errors

### ISSUE THREAD

**Issue by ChristineRWells** [swcarpentry/r-novice-gapminder#508]
There is a word missing from a sentence and a period where there should be a comma

http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html 

In the solution to challenge 3, it reads:  "The solution here presents one form using nested functions. i.e. a function passed as an argument to another function. "  I believe the word "of" is missing between "form" and "using".  Also, the period after the word "functions" should be a comma.

**Comment by jcoliver** [comment]
Thanks, @ChristineRWells . The entirety of the Solution to Challenge 3 could probably be revised for clarity. Want to take a try editing the Rmd file and submit a pull request?

**Comment by ChristineRWells** [comment]
I am very new to this, and I am not sure exactly what to do (I understand it only in theory).  I fear making some sort of error that would take someone a long time to correct - I certainly do not want to create additional work for anyone.

**Comment by jcoliver** [comment]
No worries. We welcome contributions at any level. If you're up for it, there is a great tutorial on using Git and GitHub for updating lessons at [https://gcapes.github.io/swc-pr-tutorial/](https://gcapes.github.io/swc-pr-tutorial/).

**Comment by ChristineRWells** [comment]
Greetings,

I will try to do this tomorrow.  ☺

Best,

Christine Wells, Ph.D.
UCLA Statistical Consulting Group
https://stats.idre.ucla.edu<https://stats.idre.ucla.edu/>

UCLA researchers are welcome and invited to walk-in consulting.
4919 Math Sciences

Walk-in Consulting Hours:
Monday, Tuesday 10 a.m. to 12 noon; Wednesday, Thursday 1 to 3 p.m.
See https://stats.idre.ucla.edu/ucla/policies/#WalkIn for details
