### ISSUE TITLE
Error in 05-data-structures-part2

### ISSUE THREAD

**Issue by jeremycg** [swcarpentry/r-novice-gapminder#51]
The exercise where we get learners to rbind to an existing dataframe is wrong.
```
df <- data.frame(id = c('a', 'b', 'c', 'd', 'e', 'f'), x = 1:6, y = c(214:219))
df
````

```
df <- rbind(df, list("g", 11, 42))
```

Should give an error and the following:
```
class(df$id)
```
Should give us "factor" but instead has "character" in the .md and .html versions.

this is used to motivate the use of stringsAsFactors = FALSE, which seems to already have been on before this code was run.

I'd submit a pull request, but the .Rmd is correct, just the parsing of it is wrong. 

Maybe whoever built the lessons from html has this globally enabled?

**Comment by jeremycg** [comment]
The above was lines 78-79.

The same issue occurs at lines 430 to 479 with more explicit discussion.

**Comment by aammd** [comment]
Thank you, Jeremy! I'll look into that

**Comment by jeremycg** [comment]
Sorry to keep adding - I just taught this lesson yesterday, and the challenge 1 has the same problem.

The solution given is wrong, as we haven't yet set stringasfactors to false, so the answer will give an error:
```
my_df <-data.frame(firstname = "John", lastname="Doe", age = 42) 
rbind(my_df, list("doe","jane",38))
Warning messages:
1: In `[<-.factor`(`*tmp*`, ri, value = "doe") :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, ri, value = "jane") :
  invalid factor level, NA generated
```

If we want to fix it, we can use the trick introduced above, with as.character, but as we havent covered subsetting, the $ threw learners off.

```
my_df <-data.frame(firstname = "John", lastname="Doe", age = 42) 
my_df$firstname <- as.character(my_df$firstname)
my_df$lastname <- as.character(my_df$lastname)
rbind(my_df, list("doe","jane",34))
```

I'd suggest moving the stringsasfactors part before this excercise, introducing the strinsaffactors argument to dataframe or removing the challenge. I wont submit a pull request, as it's the same issue as above, and its easier to fix all at once.

**Comment by aammd** [comment]
good catch, Jeremy! 
Incidentally, we are always open to any and all pull requests :persevere:

**Comment by sritchie73** [comment]
Sorry, this is probably my fault, as I have `options(stringsAsFactors=FALSE)` in my .Rprofile which will have affected the lesson building.

Perhaps we should create a .Rprofile in the repo directory to overwrite any custom settings a lesson builder might have?

**Comment by naupaka** [comment]
I think recent changes to the data structure lessons have obviated this problem. I'm closing this for now.
