### ISSUE TITLE
Exploring Data Frames: Factor

### ISSUE THREAD

**Issue by GitGeneral1** [swcarpentry/r-novice-gapminder#520]
This submission is related to the “[Exploring Data Frames](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html)” episode.  An objective of the episode is to understand what a factor is.

Although the order of the factor has no specific meaning in the given example, the order of factor is often meaningful.  For example, the levels “low,” “medium,” and “high” in describing the purchasing power of a household.  It could also be helpful to point out that R sorts the levels of a factor alphabetically by default (e.g. “high”, “low,” “medium”), which may not align with the ordering of the factor’s underlying value or meaning.

**Comment by jcoliver** [comment]
Good point, @GitGeneral1 . This might be good material for an optional challenge.

**Comment by jcoliver** [comment]
We are making significant changes to episodes 4 and 5 given the changes introduced in R 4.0. Please feel free to re-open if warranted.
