### ISSUE TITLE
Gapminder Formjacking threat

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/r-novice-gapminder#521]
According to [Symantec](https://safeweb.norton.com/report/show?url=https://www.gapminder.org/&ulang=en), gapminder.org is currently compromised and contains several formjacking threats.  This lesson should probably have any direct links removed until the threats can be resolved.

**Comment by jcoliver** [comment]
Thanks for the heads up, @kekoziar . Thoughts @naupaka ?

**Comment by naupaka** [comment]
Looks like the only link is in the README. Seems like we could switch it out to https://en.wikipedia.org/wiki/Gapminder_Foundation easily enough. @kekoziar care to submit a PR with the change?

**Comment by jcoliver** [comment]
There's a link in episode 01, too, in the Motivation section.

**Comment by kekoziar** [comment]
@naupaka Yes, I'll submit a PR with the fix.  Thanks!

**Comment by naupaka** [comment]
@kekoziar can you adjust the PR to be against the master branch? We merge to master and then Travis CI renders and pushed to gh-pages, so any changes to gh-pages will be overwritten.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
