### ISSUE TITLE
Code highlighting - low contrast and hard to read

### ISSUE THREAD

**Issue by yochannah** [swcarpentry/r-novice-gapminder#522]
I'm not sure if this is the right place to raise this issue - it might need to be on a lesson template somewhere instead(?) so please let me know if I should raise it elsewhere. 

![image](https://user-images.githubusercontent.com/9271438/59509751-d410d180-8ea9-11e9-98aa-d8a1139bb38d.png)

The combination of very thin font + grey background + purple in R code highlighting is just low enough contrast I'm finding it hard to read. This might be specific to how it renders on my machine/browser combo (Ubuntu + FireFox). Adjusting the code highliting theme to a slightly thicker font or darker colour might make the content more accessible.

As an example, changing the colour from a medium dark purple `#6e5494` to the slightly darker purple `#360084` makes things much clearer.

![image](https://user-images.githubusercontent.com/9271438/59510094-be4fdc00-8eaa-11e9-8c89-f20c64df7e46.png)

(context: I have visual impairment that is mostly, but not perfectly, fixed by glasses. Others with more significant visual impairment might suffer from this more noticably).

**Comment by fmichonneau** [comment]
thanks for bringing this up @yochannah, I reported the issue in the styles repo (carpentries/styles#411), and we'll address this there.
