### ISSUE TITLE
contributing.md not correct

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/r-novice-gapminder#527]
`contributing.md` states 
> The published copy of the lesson is in the `gh-pages` branch of the repository (so that GitHub will regenerate it automatically). Please create all branches from that, and merge the master repository's `gh-pages` branch into your `gh-pages` branch before starting work. Please do not work directly in your `gh-pages` branch, since that will make it difficult for you to work on other  
contributions.

but, that doesn't seem to be the case nor workflow for this repository. `contributing.md` should be updated to reflect the workflow of this repository.

**Comment by jcoliver** [comment]
Thanks, @kekoziar . The contributing.md file comes from the Carpentries [style](https://github.com/carpentries/styles) repository (I'm pretty sure), and this should be addressed with the next release (theoretically).

**Comment by jcoliver** [comment]
Closing this issue as it duplicates #488
