### ISSUE TITLE
Binder button for README?

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/r-novice-gapminder#528]
Any interest in adding [Binder](https://mybinder.org/) button to the README file which when clicked would open a cloud environment with all software installed for learners to work through the lessons? If so I would be happy to open a PR.

I just finish contributing a similar PR to the [Python](https://github.com/swcarpentry/python-novice-gapminder) lessons.  The approach we ended up taking was to create an orphan branch called `binder` into which I added the data files as well as necessary configuration files. I then opened a second PR to add the binder button link to the README on `gh-pages` branch.

The resulting Binder repository for this lesson would provide an RStudio server interface with the data and required R packages already installed.

**Comment by jcoliver** [comment]
That would be pretty great, @davidrpugh .

**Comment by davidrpugh** [comment]
@jcoliver Cool! If you can create an orphaned (i.e., empty) branch called `binder` in this repo then I will open a PR against that branch to add the required files. I will then open a second PR to add the binder button to the README.md on the `gh-pages` branch.

**Comment by jcoliver** [comment]
`binder` branch created, @davidrpugh . Note that we have switched to `master` branch, so please open PRs against that one, not the `gh-pages` branch.

**Comment by davidrpugh** [comment]
@jcoliver Thanks for creating the branch but it doens't look like the branch was orphaned. when it was created. The `binder` branch should start with a blank slate and it only needs to contain the data files and a couple of binder configuration files it is not necessary for the `binder` branch to have all of the lesson materials.

Options would be to delete the `binder` branch and the recreate it passing the `--orphan` flag or my first commit to this branch will remove all the files except the data directory. Just let me know...

**Comment by jcoliver** [comment]
@davidrpugh right, my bad. Let me try it again, the right way...

**Comment by jcoliver** [comment]
@davidrpugh OK, I deleted the branch and created an orphan `binder`. It just has a README that can be overwritten.

**Comment by jcoliver** [comment]
Addressed in #532 and #534
