### ISSUE TITLE
Update CITATION

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#530]
Given the new release (https://doi.org/10.5281/zenodo.3265164), the citation should be updated, too.

**Comment by naupaka** [comment]
Instructions here

- Add your Zenodo DOI badge to your README file

1. Find your lesson on The Carpentries community in Zenodo
2. Click the DOI badge located in the right-hand info bar
3. Copy the Markdown code into the top of your README.md file

- Update your CITATION file 

1. On your lesson's Zenodo page, copy the "Cite As" information from the right-hand info bar 
2. Paste into your CITATION file
