### ISSUE TITLE
How to keep gh-pages up to date in my fork?

### ISSUE THREAD

**Issue by davidrpugh** [swcarpentry/r-novice-gapminder#537]
I am maintaining a fork of these lessons and would like to understand how to keep the `gh-pages` branch in sync with `gh-pages` in this repo. Looks like the `gh-pages` is being auto built by Travis and development is going on in `master`. Do I just need to enable Travis for my fork of the repo?

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
