### ISSUE TITLE
Suggestion to add a gentler introduction for ggplot2

### ISSUE THREAD

**Issue by wallacelab** [swcarpentry/r-novice-gapminder#542]
The current [ggplot2 lesson](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html) feels like it starts very abruptly, going from nothing to using ggplot(), aes(), and geom_point() all in a single line of code. That seems like a bit much for a first experience. (I learned ggplot2 ~6 months ago through this very lesson, and I felt very lost until I could go back through a second or third time.)

It seems like a little expansion of the introduction would help with this. The lesson currently has these lines:

> ggplot2 is built on the grammar of graphics, the idea that any plot can be expressed from the same set of components: a data set, a coordinate system, and a set of geoms–the visual representation of data points.
> 
> The key to understanding ggplot2 is thinking about a figure in layers. This idea may be familiar to you if you have used image editing programs like Photoshop, Illustrator, or Inkscape.

I suggest expanding/altering it into something more like

> ggplot2 is built on the grammar of graphics, the idea that any plot can be expressed from the same set of components. These components are a data set, mapping aesthetics, and layers of graphics.
> - **Data sets** are the data that you, the user, provide.
> - **Mapping aesthetics** are what connect the data to the graphics. They tell ggplot2 how to use different parts of your data to affect how the graph looks (such as by changing what is plotted on the X or Y axis, or if parts of the plot should have different sizes or colors based on your data).
> - **Layers** are the actual graphical output from ggplot2. Layers determine what kind(s) of plot are shown (scatterplot, histogram, etc.), the coordinate system used (rectangular, polar, etc.), and other important aspects of the plot. The idea of layers of graphics may be familiar to you if you have used image editing programs like Photoshop, Illustrator, or Inkscape.

When teaching I like diagramming these out, but I don't know if that belongs in the official lesson itself. Same for pointing out these three components in the first code example.

The reasons I suggest replacing "coordinate system" with "mapping aesthetics" are because
- The word "coordinate" is never used again in the lesson, whereas "mapping" shows up 25 times and "aesthetic" 16 times 
- None of the examples actually change the coordinate system. (The closest is adjusting the scale with `+ scale_x_log10()` )
- The base ggplot() command seems to function more like a "layer 0" than a coordinate system. (This may be due to an incorrect mental map on my part, but it behaves like the base layer on which everything else is placed.)
- This would make clearer what aes() is actually doing (mentioned briefly in issue #473)

**Comment by jcoliver** [comment]
Great points, @wallacelab . I like the explanations for the different parts of a stripped-down `ggplot` call. One challenge I faced when learning `ggplot` syntax (because, let's be honest, the struggle is real) is that reading the descriptions didn't mean much until I had typed in the code (usually incorrectly). Perhaps the explanatory language you are suggesting could come _after_ the first call (or calls) to `ggplot`?

**Comment by wallacelab** [comment]
@jcoliver Thanks. I think it makes more sense to present the overview first, then show the learners how each part of the command fits into it. This lesson was my first training in ggplot, and though I can't speak for others, that big chunk of code at the beginning was a turn-off because it looked really complex and uninterpretable. When teaching, I've found it's actually useful to skip the first plot in the lesson and go to where it starts building the graphic up bit by bit, starting from an empty ggplot() command and then adding data, mapping, and finally a geom.

I went ahead and forked the lesson so I can add some edits for consideration.

**Comment by ed-lau** [comment]
I would suggest removing or replacing the geom_line() points in the current sections. While I understand the intention of showing that ggplots can be built by layers and that one set of data/aes can be mapped to different geoms, I think many will find the current line plots to be visually overwhelming. 

In my opinion they are also not good data exploration plots - you probably wouldn't expect to find a plot like that in many reports or expect the readers to be able to easily interpret them. Second potential point of confusion is that the section immediately after switches back from a lifeExp vs. year plot back to lifeExp vs gdpPercap plots.

I suggest the transformations and statistics section could follow the first section up to Challenge 1. After that we can use the same lifeExp vs. gdpPercap plot to introducing panel faceting. It is probably also a more intuitive introduction to grouping than the color aes.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/8249469/63187023-ba5b4a00-c012-11e9-891a-75b1236b8d9a.png">

And changing the aes and geom can follow after this, e.g.,:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/8249469/63187096-e1198080-c012-11e9-919d-5a42d1213a9e.png">

I find this flow to be more natural but would love to hear what you think.

**Comment by jcoliver** [comment]
Closing in favor of the discussion on #552
