### ISSUE TITLE
Specificity of learning objectives for data structures lesson

### ISSUE THREAD

**Issue by pab2163** [swcarpentry/r-novice-gapminder#543]
The learning objectives from the [data structures lesson ](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html
) are little bit broad, and could be made a bit more specific (i.e. what can students *do* after completing the lesson) 

Here are some possible alternatives:
-be able to create and work with the 5 main types of data
-develop comfort with creating and modifying vectors, lists, matrices, and data frames
-understand the roles vectors, factors, and lists play within data frames
-be able to look up information directly in R about the about the type, class, and structure of an object

**Comment by jcoliver** [comment]
Thanks, @pab2163 . I think there could be a larger effort to review learning objects for _all_ lessons. At the very least, making them congruent with one another would be a good idea. For example, compare those from the [functions lesson](http://swcarpentry.github.io/r-novice-gapminder/10-functions/index.html):

+ Define a function that takes arguments.
+ Return a value from a function.
+ Check argument conditions with stopifnot() in functions.
+ Test a function.
+ Set default values for function arguments.
+ Explain why we should divide programs into small, single-purpose functions.

to the [data structures lesson](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html):

+ To be aware of the different types of data.
+ To begin exploring data frames, and understand how they are related to vectors, factors and lists.
+ To be able to ask questions from R about the type, class, and structure of an object.

The functions lesson objectives do a better job of fitting with Bloom's taxonomy; we should probably strive for such alignment in all lesson learning objectives.

**Comment by katherinesimeon** [comment]
I agree that objectives from all lessons could be reviewed and refreshed. While many of the lessons have specific and achievable objectives, the objectives could be re-structured/ordered to: 

1. Better parallel with the structure of the lesson
2. In line with Bloom's Taxonomy, scaffold from lower-order (knowledge, comprehension, & application) to higher-order (analysis, synthesis, & evaluation) thinking as applicable.   

For instance, building on the improved learning objectives that @pab2163 wrote for the [data structures lesson](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html):  

- Recognize 5 different data types.   
- Identify different data types & structures using `typeof()` and `class()`.  
- Discuss how vectors, factors, and lists relate to data frames.  
- Practice creating and modifying vectors, lists, matrices, and data frames.  
  
The order of these objectives start with lower-order knowledge & comprehension-based objectives (recognize and identify) and then ask students to apply knowledge as they learn. This roughly parallels the structure of the lesson as well.  
  
For the lesson on [subsetting data](http://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/index.html), the objectives are specific but could be slightly modified to to parallel the order of topics in the lesson:  
   
- Practice accessing individual and multiple elements of a given data set by indices, name, and logical operations.  
- Practice skipping and removing elements from a data set.  
- Compare subsetting for different types of data structures: vectors, factors, matrices, lists, and data frames.  
 
I'm happy to be part of the re-review for learning objectives. Please let me know if there is a way to help!

**Comment by jcoliver** [comment]
Thanks, @katherinesimeon and @pab2163 ! I think for now submitting PRs with suggested revisions would be the place to start. Most of the lessons have learning objects with the right spirit, they just need a little love to align with Bloom's taxonomy and the order of the lesson.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
