### ISSUE TITLE
Explanation for relationship between matrices and data frames in data structures lesson

### ISSUE THREAD

**Issue by pab2163** [swcarpentry/r-novice-gapminder#544]
In the [data structures lesson](http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html), it feels as though the matrix information at the end is a bit of an afterthought, it is not clear exactly how they relate to lists, vectors, and data frames. 

We could add a little bit of information especially on what differentiates matrices and dataframes, and what they might be used for.

**Comment by herczegrobert** [comment]
What about [Advanced R](http://adv-r.had.co.nz/Data-structures.html) suggestions:

R’s base data structures can be organised by their dimensionality (1d, 2d, or nd) and whether they’re homogeneous (all contents must be of the same type) or heterogeneous (the contents can be of different types). Matrices have to be homogeneous while data frames can be heterogeneous.

**Comment by seacatkim** [comment]
I submitted a pull request changing the matrix description to the following as per your suggestion @herczegrobert 

"Last but not least is the matrix. Similar to data frames, matrices are two dimensional with rows and columns. A data frame can combine columns of different data types such as integers, factors, logical etc. while matrices are homogenous only containing a single data type for the whole matrix.

We can declare a matrix full of zeros:"

**Comment by jcoliver** [comment]
Addressed by #546 .
