### ISSUE TITLE
Seeking Help episode 04: add an example of the usage of dput function

### ISSUE THREAD

**Issue by AndresBeita** [swcarpentry/r-novice-gapminder#545]
At the end of episode 04: Seeking Help, the lesson suggests the use of the function dput, but there is not much more about it. For me, as it is now, it feels a little bit abstract and not straightforward to understand. 

In the Data Carpentry lesson on Data Analysis and Visualization in R for Ecologists, Chapter 1: Before we start, section Asking for help, they already solved this problem providing an example on the usage of the dput function:

dput(head(iris)) # iris is an example data frame that comes with R and head() is a function that returns the first part of the data frame

I think that giving an example will not require much more time of teaching and will help the learners to better interiorize the purpose of the function.  I suggest adding the example presented before or something similar.

**Comment by jcoliver** [comment]
Good point, @AndresBeita . I wonder though, if the `dput` section should just be removed. The output of `dput(head(iris))`:
```
structure(list(Sepal.Length = c(5.1, 4.9, 4.7, 4.6, 5, 5.4), 
    Sepal.Width = c(3.5, 3, 3.2, 3.1, 3.6, 3.9), Petal.Length = c(1.4, 
    1.4, 1.3, 1.5, 1.4, 1.7), Petal.Width = c(0.2, 0.2, 0.2, 
    0.2, 0.2, 0.4), Species = structure(c(1L, 1L, 1L, 1L, 1L, 
    1L), .Label = c("setosa", "versicolor", "virginica"), class = "factor")), row.names = c(NA, 6L), class = "data.frame")
```
may not be recognizable by most of the learners at this point in the lesson.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
