### ISSUE TITLE
Include qplot() in ggplot lesson?

### ISSUE THREAD

**Issue by wallacelab** [swcarpentry/r-novice-gapminder#553]
I'm debating whether it makes sense to include a short section on the qplot() function at the start/end of the ggplot() section. qplot() function is a very fast and easy way to plot graphs, and may be all many learners need (especially at first). For example, the following code using full ggplot syntax

`ggplot(gapminder, mapping=aes(x=gdpPercap, y=lifeExp)) + geom_point()`

can be rentered with qplot() as

`qplot(x=gdpPercap, y=lifeExp, data=gapminder, geom="point")`

which uses only 1 function call instead of 3 and follows more typical R syntax.

As far as I can tell the two ways are functionally equivalent, so that you can continue to add layers to the qplot() command if you want. 

The biggest problem is that adding this would probably require shortening some other section of the lesson. (Though if it's at the end, probably less than if it's at the beginning because it would just be "here's this useful shortcut.") I'm not sure what I would cut, as everything there seems pretty important. So I'm asking for people's input:
- Would having a section on qplot() be a useful/important addition to the lesson?
- If so, what other section might be shortened to make room for it?

Thanks.

**Comment by jrmuirhead** [comment]
Although I recognize that reducing the number of function calls has value, my sense is that is would not be a useful addition to the lesson as there are some key differences from the full ggplot syntax and some time would have to be spent on these differences. 
Mainly, 

1. `qplot` defaults to geom_point if both x, and y, and geom_histogram is either x or y are provided whereas ggplot has no default geom if the geom is unspecified. That is, 
`qplot(x=gdpPercap, y=lifeExp, data=gapminder)` will return a scatterplot.

1. There would need to be an explanation of why aesthetics in ggplot are mapped to variables inside of `aes()`, but not for qplot.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
