### ISSUE TITLE
Install gapminder package and load library

### ISSUE THREAD

**Issue by jtallantumich** [swcarpentry/r-novice-gapminder#559]
It seems helpful to me to have learners see that data can be stored in a package and easily loaded as a library. Consider adding to alternatives section. 
-jtallant

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by jtallantumich** [comment]
https://github.com/swcarpentry/r-novice-gapminder/compare/master...jtallantumich:patch-1

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
