### ISSUE TITLE
write.csv in Episode 4: Data structures(https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html)

### ISSUE THREAD

**Issue by MariaYR** [swcarpentry/r-novice-gapminder#560]
Hi, this comment is about the write.csv line in the very first part of the episode:  https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html. While doing my teaching demo, the instructor noted the write.csv portion was skipping ahead, but that's the actual order of the lesson. So I wondered if maye it just wasn't confusing overall.  I  do think its confusing for novices, in terms of real-world applicaiton, because I don't think there would be cause to export a dummy data set in r (or maybe I've just never encountered it). It might make more sense to move this to the very end of the episode, as a side note for folx?

**Comment by jcoliver** [comment]
I think the focus of the first part of this episode is to highlight how R works with tabular data. Creating a small data set, then writing and reading the data provides an accessible introduction to common data file formats used with R.

**Comment by jcoliver** [comment]
We are working on significant revisions to episodes 4 and 5 due to changes introduced in R 4.0. Feel free to re-open as warranted.
