### ISSUE TITLE
Exploring Data Frames episode: add a tip on the usage and the meaning of %in% operator

### ISSUE THREAD

**Issue by monahton** [swcarpentry/r-novice-gapminder#561]
This submission is related to the "Exploring Data Frames" episode [http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html).

In the "Removing columns" section, the following commands were used:
`drop <- names(cats) %in% c("age")`
`cats[,!drop]`

However, this is the first time the "%in%" operator is used without any clarifications about its usage and what does it do or its meaning. This might create a confusion for students during the execution of this command. 

I think it would be better to add a tip here about the meaning of this operator or guide the students on searching for help for this operator. 
(I would like to also note here that in the following episode "Subsetting data", there is actually a tip about this operator at the beginning of the lesson but I think it is misplaced as this operator was not actually used in the section in which this tip is placed but later explained in details). 
So I think it could be also possible to replace this tip from the "Subsetting Data" episode to "Exploring Data Frames" episode.

**Comment by jcoliver** [comment]
Good point, @monahton . Copying the tip from the Subsetting Data episode would be good (probably best to leave the tip in it's original location, too, since the `%in%` operator could use some reinforcement).

**Comment by wrightrc** [comment]
Should this issue now be marked resolved? Just looking for a good first issue for my checkout.

I can also submit at PR adding [a link](https://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/#Subsetting-through-other-logical-operations) to the "Subsetting through other logical operations" section and mention there will be more on the %in% logical operator later.

**Comment by jcoliver** [comment]
Fixed in #567 and #649
