### ISSUE TITLE
Inclusion of ifelse() function in Control Flow

### ISSUE THREAD

**Issue by atheobold** [swcarpentry/r-novice-gapminder#562]
In the Control Flow lesson, the current content solely addresses conditional statements that can handle a scalar input. I believe adding in R's built-in `ifelse()` function would be great, especially after the warning messages associated with Challenge 1. I have rarely, if ever, encountered an R user employing the `any()` or `all()` functions. Thus, I believe that this Tip could potentially be eliminated in favor of the `ifelse()` addition.

**Comment by jcoliver** [comment]
Thanks, @atheobold . I think an additional tip around `ifelse()` is warranted; I'm less inclined to remove the `any()` tip, as an R user who employs the `any()` function. ;)

**Comment by atheobold** [comment]
I am happy to add the `ifelse()` section, and preserve the `any()` function for all to appreciate!
