### ISSUE TITLE
Use pivot_longer() and pivot_wider() instead of gather() and spread()

### ISSUE THREAD

**Issue by matt-dray** [swcarpentry/r-novice-gapminder#570]
Lesson: [Dataframe Manipulation with tidyr](http://swcarpentry.github.io/r-novice-gapminder/14-tidyr/index.html).

Suggestion: replace `spread()` and `gather()` with [`pivot_longer()` and `pivot_wider()`](https://tidyr.tidyverse.org/articles/pivot.html). 

Reason: these new, more intuitive functions are intended to be the de facto approach to making data 'longer' and 'wider' [as of {tidyr} version 1.0.0](https://www.tidyverse.org/articles/2019/09/tidyr-1-0-0/) (though `gather()` and `spread()` continue to work).

**Comment by matt-dray** [comment]
I've had a look at doing this in [a branch of a fork of the repo](https://github.com/matt-dray/r-novice-gapminder/blob/tidyr-pivot-functions/_episodes_rmd/14-tidyr.Rmd) (link valid at time of posting).

Looks like outputs from the pivot functions differ from `gather()` and `spread()`: they have tibble class as well as `data.frame` and are ordered differently. This means some of the figures need updating as well as the text.

For example, consider the `gap_long` object from the ['From wide to long format with gather()'](http://swcarpentry.github.io/r-novice-gapminder/14-tidyr/index.html#from-wide-to-long-format-with-gather) section, which was created using `gather()`. `str(gap_long)` gives:

```
'data.frame':	5112 obs. of  4 variables:
 $ continent   : chr  "Africa" "Africa" "Africa" "Africa" ...
 $ country     : chr  "Algeria" "Angola" "Benin" "Botswana" ...
 $ obstype_year: chr  "pop_1952" "pop_1952" "pop_1952" "pop_1952" ...
 $ obs_values  : num  9279525 4232095 1738315 442308 4469979 ...
```

If the same code is re-run with `pivot_longer()` instead of `gather()`, the output of `str(gap_long)` looks like this:

```
Classes 'tbl_df', 'tbl' and 'data.frame':    5112 obs. of  4 variables:
$ continent   : chr  "Africa" "Africa" "Africa" "Africa" ...
$ country     : chr  "Algeria" "Algeria" "Algeria" "Algeria" ...
$ obstype_year: chr  "pop_1952" "pop_1957" "pop_1962" "pop_1967" ...
$ obs_values  : num  9279525 10270856 11000948 12760499 14760787 ...
```

So `pivot_longer()` yielded the tibble class and was ordered by continent-country.

**Comment by jcoliver** [comment]
Hmmm...interesting. Any reason why the ordering in the output is different between `gather` (continent, obstype_year, _country_) and `pivot_longer` (continent, _country_, obstype_year)?

**Comment by katrinleinweber** [comment]
Related: https://github.com/datacarpentry/r-socialsci/issues/104
