### ISSUE TITLE
File missing in lesson 4 of R for reproducible scientific analyses

### ISSUE THREAD

**Issue by SaraTomiolo** [swcarpentry/r-novice-gapminder#572]
Hi, I am going through the lesson number 4 of [R for reproducible scientific analyses](https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html). In the section of data types there is a prompt to load the file "feline-data_v2.csv" from the data folder, but that file does not exist.
It seems that the file may have been modified from the original "feline-data.csv" but there is no indication in the prior parts of the lesson of that happening.

**Comment by SaraTomiolo** [comment]
Hi, I have tried to look at the R Markdown file of the lesson. I think the easiest way to fix this would be to provide the user with a link (as is done for gapminder) to download this "feline-data_v2.csv" data set. Unfortunately I am not advanced enough to understand how to fix this. Sorry!

**Comment by mstrimas** [comment]
Based on this older [issue](https://github.com/swcarpentry/r-novice-gapminder/issues/479) and [PR](https://github.com/swcarpentry/r-novice-gapminder/pull/533), it seems the intention is to actually remove this example altogether. Could be worth closing this issue so other trainees going through checkout process don't accidentally try to address this issue incorrectly.

**Comment by mstrimas** [comment]
FWIW I think the entire feline v2 example is confusing and out of place. I agree that removing the whole thing would be an improvement. The section on Type Conversion seems to cover similar concepts in a less confusing fashion.

**Comment by jcoliver** [comment]
Closing, as issue #479 supersedes.
