### ISSUE TITLE
Missing solution?

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/r-novice-gapminder#575]
On the Gapminder R notes, page 5. Exploring Data Frames, the solution to challenge 1, part 3 appears incomplete. I can't see how to get my `human_age` vector from integers 1..4 back into the actual numeric values.

**Comment by jcoliver** [comment]
Thanks, @mattgillucl . The solution to part 3 of challenge one should probably explicitly mention the use of the `as.character` function.
