### ISSUE TITLE
Weird data item

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/r-novice-gapminder#579]
On [this page](https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html) there is an entry to the `cats` data file which says 

> tabby,2.3 or 2.4,1

Is that a typo? What is the “or” doing there?

And the `Oh no, our weights aren’t the double type anymore!` doesn’t make sense, as it isn’t an integer.

Am I missing something here?

**Comment by jcoliver** [comment]
This is designed to create a problem when reading in the file. Because there is a non-numeric character (or four, really: " or ") in the weight column, R reads it in as a factor. And calling `typeof` on a factor returns "integer".
