### ISSUE TITLE
Missing solution text

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/r-novice-gapminder#580]
On [this page](https://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html), _R for Reproducible Scientific Analysis -Creating Publication-Quality Graphics with ggplot2_, the text in the Solution for Challenge 2 is the same as the question text. 

I think there should be some more explanation of the `aes` function.

**Comment by jcoliver** [comment]
Yes, the text in the solution should be updated to be an explanation of the solution, not just a repetition of the challenge.
