### ISSUE TITLE
Unclear diagrams

### ISSUE THREAD

**Issue by mattgillucl** [swcarpentry/r-novice-gapminder#581]
On the page [_R for Reproducible Scientific Analysis - Dataframe Manipulation with dplyr_](https://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html), there is a diagram with the heading `gapminder %>% group_by(a)`.

In the diagram, it is unclear whether or not the top two arrows cross. Please change this diagram to make it clear.

**Comment by mattgillucl** [comment]
PS The next diagram below this one has the same problem.

**Comment by jcoliver** [comment]
I agree. The arrows should be re-drawn and potentially re-colored to improve utility of these graphics.

**Comment by jrmuirhead** [comment]
I've submitted a pull request changing the R code to generate the figures. One question I had @jcoliver , are the png versions in the fig directory generated as part of the TravisCI checks, or will I have to update the png files as well?

**Comment by jcoliver** [comment]
Code updated (#631 ) and png regenerated (#644 ).
