### ISSUE TITLE
Creating Publication-Quality Graphics with ggplot2 - Challenge 5

### ISSUE THREAD

**Issue by simonezuffa** [swcarpentry/r-novice-gapminder#582]
I suggest to modify challenge 5 in the introduction to ggplot2.
You should ask to generate box plots instead of density plots. I believe this could be more relevant to the majority of the readers and also you can point out that continents has to be a factor.

`ggplot(data = gapminder, mapping = aes(x = continent, y = lifeExp, fill = continent)) +
geom_boxplot + facet_wrap( ~ year)`

**Comment by jcoliver** [comment]
Intriguing idea, @simonezuffa . There's a little messiness with the axis, but fixing them could be part of the challenge. Want to submit a PR?
![challenge-5-boxplot-example](https://user-images.githubusercontent.com/1939813/68810272-fe1e1980-062a-11ea-8be2-e1c4e6fe98f2.png)

**Comment by simonezuffa** [comment]
Thanks @jcoliver . Just submitted a PR

**Comment by jcoliver** [comment]
Fixed by #588
