### ISSUE TITLE
gif to explain pipelines with Mario

### ISSUE THREAD

**Issue by DanielleQuinn** [swcarpentry/r-novice-gapminder#592]
I'm not certain where this should go (perhaps in instructor notes?) but I wanted to share a gif I've created that uses Mario to demonstrate how pipes work in R; I've found it to be an effective visualization, though obviously more so for students who are generally familiar with Mario!

https://github.com/DanielleQuinn/what_are_pipes/blob/master/mymario.gif

**Comment by jcoliver** [comment]
Nice, @DanielleQuinn ! I think the Instructor Notes would the the appropriate place to link to the gif. There seems like a lot of unnecessary whitespace at the bottom of the animation (over half the vertical space is unused). Is there any way to remove that?

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
