### ISSUE TITLE
Revise language around pivot_longer and pivot_wider

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#594]
The change to tidyr's `pivot_longer` and `pivot_wider` (from `gather` and `spread`, respectively) prompts a review of the language describing the use of these functions. The previous functions had verbs to describe their action (i.e. "gather" and "spread"), which were at least somewhat intuitive to understand. The verb for the new functions, "pivot", does not provide the same accessibility to a novice in understanding what is happening. After all, `pivot_longer` and `pivot_wider` are doing the opposite things to data, so using the same verb to describe their actions can be confusing. Consider revising the language of Episode 14, replacing the verb "pivot" with better description of what the two functions are actually doing.

**Comment by stephhazlitt** [comment]
Hi @jcoliver. I am looking for an open issue to fulfill my instructor training checkout requirement ([_Submit a Small Contribution to One of Our Lessons_](https://carpentries.github.io/instructor-training/checkout/)). I would be happy to make an attempt at this issue &mdash; would adding a very short introduction paragraph to the `tidyr::pivot_*` functions after `## Challenge 1` and before `## From wide to long format with gather()` be a start here? IMO the developers behind `tidyr` have worked hard on writing clear and useful documentation on what these functions do, so I would be inclined to use the [same descriptions](https://tidyr.tidyverse.org/articles/pivot.html)? Thoughts? Other suggestions or changes you had in mind? Or other issues you would prefer someone tackled?

**Comment by jcoliver** [comment]
Hi @stephhazlitt . That sounds like a great addition to the lesson. We would like to avoid duplicating the tidyr documentation, but a description of what these two functions do that is appropriate for a novice audience would be great. A place to start would be to look at the first respective sentences under the **Longer** and **Wider** headings.
