### ISSUE TITLE
minor suggestions [received by email]

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/r-novice-gapminder#598]
**Intro to R & RStudio episode:**
Need to unify if it is an .R file or a .R file
To me, the amount of information in the help pane deserves a bigger mention when introducing the different panes. A comment referring to help pages would not be out of place when mathematical functions are mentioned (sin/cos/tan etc).
Is there a reason that the tools tab in RStudio is not mentioned as an option to install packages as well as the command line?

**Project management episode:**
how do we open a project in RStudio - seems to be missing? Is it worthwhile adding in a screenshot and discussion?
how many R(Studio) sessions can someone have open at once? (importance of keeping track of projects)

**Comment by jcoliver** [comment]
Thanks for passing these suggestions along, @ErinBecker ! I've atomized them into separate issues #599 and #600 .
