### ISSUE TITLE
Add information about opening projects in RStudio

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#600]
Additional information regarding how to open a project in RStudio (i.e. navigation to and selection of a .Rproj file) could be included.

Originally mentioned as part of #598

**Comment by boshek** [comment]
👋 @jcoliver . I am looking to fulfill the contribution part of my carpentries training. I think I could submit as a PR some text about opening RStudio projects, at a high level what they mean and why you can multiple ones open. I was thinking I could submit it here:

https://github.com/swcarpentry/r-novice-gapminder/blob/3eb44e593049300a2e4b6797032b06624e56e92d/_episodes_rmd/02-project-intro.Rmd#L51-L53

What do you think?

**Comment by jcoliver** [comment]
Thanks, @boshek . That's a good place to briefly mention the utility of multiple projects (atomization et al.). I could also see adding a Challenge or a Tip at the end of the episode that closes the project, then opens it again via the .Rproj file.

And while you're mucking around in episode 2, the challenge enumeration could use some attention: the first challenge is unnumbered, and the one labeled "Challenge 1" is actually the second challenge.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
