### ISSUE TITLE
Consistent code styling

### ISSUE THREAD

**Issue by mstrimas** [swcarpentry/r-novice-gapminder#604]
I see a lot of inconsistency in style of R code within the lessons. Mostly inconsistent use of spacing (e.g. `sample(1:10, size=5)` vs. `sample(1:10, size = 5)`), naming (`var_name` vs. `varName`), single vs. double quotes, etc. I find it distracting and feel like it doesn't encourage best practices, although I'm admittedly especially uptight about this stuff. If there's any interest, I'd be happy to run through all the lessons and submit a PR making them all conform to the [Tidyverse style guide](https://style.tidyverse.org/).

**Comment by jcoliver** [comment]
Thanks, @mstrimas . #548 and #589 deal with some of this. I'd suggest holding off for now until those two PRs finish review.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
