### ISSUE TITLE
Challenges 4b and 5 in http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html has different style

### ISSUE THREAD

**Issue by steltenpower** [swcarpentry/r-novice-gapminder#611]
Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by jcoliver** [comment]
Challenge 4b and 5 in the ggplot episode are not rendered as desired. This is likely due to empty lines in solution sections immediately preceding the code block (lines 288 & 401). Deleting those lines should fix the discrepancy.

**Comment by mariadelmarq** [comment]
@steltenpower @jcoliver this seems to have made the problem worse in that the solutions have now disappeared... I've re-added those lines and made the spacing consistent with the other challenges, but how can I check what the rendering will look like with my changes?

**Comment by jcoliver** [comment]
Thanks, @mariadelmarq
