### ISSUE TITLE
Episode 2 Challenge 4: Shell solution has "R" label.

### ISSUE THREAD

**Issue by shervinsahba** [swcarpentry/r-novice-gapminder#613]
The solution for Challenge 4 requires the commands to be written in a shell terminal, as stated. But the generated solution labels the commands with "R". It should say "Shell". It's not a big deal, but it's briefly confusing, since users just learned ls() in R as well.

**Comment by jcoliver** [comment]
Thanks, @shervinsahba . This is a known issue (#535 ), requiring some updates outside the scope of this repository.
