### ISSUE TITLE
Typos in "R for Reproducible Scientific Analysis" lesson, in "Introduction to R and RStudio" episode

### ISSUE THREAD

**Issue by KNortheastern** [swcarpentry/r-novice-gapminder#615]
As the title says, in the "R for Reproducible Scientific Analysis" lesson, in the "Introduction to R and RStudio" episode [(link here)](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html) there are 3 typos.

- In the section header "Work flow within RStudio", I believe that workflow should be one word (this is open for debate though if folks feel more strongly about grammar).

- In the "Tip: Cancelling commands" text box, in the line "If you're using R from the commandline", command line should be two words.

- In the "Variables and assignment" section, one of the examples contains the line "and and now it has the value 100" where the word "and" is accidentally repeated twice.

Please let me know if anyone feels strongly about "work flow" and/or if I can be of help making these changes (new instructor undergoing checkout).

Thanks!

**Comment by jcoliver** [comment]
Thanks for these, @KNortheastern !
