### ISSUE TITLE
Episode 1 Intro to R & RStudio, managing environment 

### ISSUE THREAD

**Issue by apculley** [swcarpentry/r-novice-gapminder#623]
I’d suggest following the sentence: ‘If we type ls by itself, R will print out the source code for that function!’ with a very brief layperson explanation of what source code is, such as: ‘Source code what is going on behind the scenes whenever a function is run.’ (And then maybe add that we’ll be going over functions in detail later).

**Comment by jcoliver** [comment]
Thanks, @apculley !

**Comment by blongworth** [comment]
I've seen a lot of R learners forget the parens, especially if they've just taken a shell lesson. It's also a great time to introduce thinking of everything in R as an object, and to touch on default methods, in this case print().
