### ISSUE TITLE
Suggestion of adding demo() to Seeking Help episode

### ISSUE THREAD

**Issue by Fe-Sa** [swcarpentry/r-novice-gapminder#625]
I would like to suggest adding, and briefly explaining the demo() function to the "Getting help on packages" section of the "Seeking Help" episode of the R for Reproducible Scientific Analysis lesson. 
http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
