### ISSUE TITLE
Diagrams do not render properly on dplyr and tidyr lessons

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#63]
Perhaps you can figure this one out @remi-daigle?

Seems to be an issue with the pandoc -> html -> jekyll workflow somewhere... The diagrams using `DiagrammeR` don't display properly. See http://swcarpentry.github.io/r-novice-gapminder/13-dplyr.html and http://swcarpentry.github.io/r-novice-gapminder/14-tidyr.html

**Comment by remi-daigle** [comment]
I think at this point, the best solution is to simply save the `.png`'s and load them in the `.Rmd`. I also included the script used to generate the figures in the pull request #64 
(I tried to tag this issue when I created the pull request, but it didn't appear to work)

**Comment by naupaka** [comment]
Ok. I will take a look. Thanks for the quick turn-around!

**Comment by naupaka** [comment]
Can you pull down the new changes I made this morning first and then add your fixes on top?
