### ISSUE TITLE
Mention flexibility of variable selection in 'select' function 

### ISSUE THREAD

**Issue by adrianadepalma** [swcarpentry/r-novice-gapminder#630]
Episode name: R for Reproducible Scientific Analysis
Lesson: Dataframe Manipulation with dplyr
Link: http://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html

dplyr is being updated to version 1-0-0 (https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-select-rename-relocate/). Should the lesson mention others of the five ways to select variables with this function? In terms of reproducible analysis, the helper functions in particular (e.g., `starts_with` and `contains`) are extremely useful when working with larger datasets with many columns. Although I appreciate that this may overload some beginners.

**Comment by jcoliver** [comment]
Thanks, @adrianadepalma . This information would work well in an optional section. As you indicate, it has the potential to overload novice learners.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
