### ISSUE TITLE
Issue in appearance of lesson 'Exploring data frames' on github.io

### ISSUE THREAD

**Issue by JasonDaleTurner** [swcarpentry/r-novice-gapminder#639]
https://github.com/swcarpentry/r-novice-gapminder/blob/master/_episodes_rmd/05-data-structures-part2.Rmd
line 85-96

This code does not actually result in an error when viewing the episode page on github.io, it appears the coats column may not actually be a factor but instead be a character meaning the rbind command does not throw a warning.

**Comment by jcoliver** [comment]
Thanks, @JasonDaleTurner . This is a known issue #633 and we are working on it.
