### ISSUE TITLE
Exploring Data Frames- factor() and as.factor()

### ISSUE THREAD

**Issue by castanedaM** [swcarpentry/r-novice-gapminder#643]
I believe in the episode [Exploring Data Frames](https://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/) when they make the introduction to factors, it will be fit to mention the difference and connection between using as.factors() and the function factor().

While as.factor() will leave factor levels as they are, factor() will not. Using factor() allows you to set the level to the order you want, while as.factor will use the alphabetical order. 

A similar issue refereing to adding the importance of setting the levels  #520

**Comment by jcoliver** [comment]
Thank you for the suggestion, @MarianaCastaneda . I think at this point in the lesson, the distinction between `as.factor` and `factor` may be a bit too much in the weeds. It is an important difference, but may be distracting to for learners, many of whom are probably still grappling with the concept of different data types.

**Comment by jcoliver** [comment]
We are significantly revising episode 5 based on changes introduced in R 4.0. Please feel free to re-open if warranted.

**Comment by blongworth** [comment]
Is there a fork for the 4.0 updates? It's a good opportunity to explain factors and prepare learners for the kinds of issues they'll see with code that expects `stringsAsFactors = TRUE` and vice versa if they encounter an older version of R.

**Comment by naupaka** [comment]
@blongworth not yet, but I'm hoping to make a push to get it going in the next week or two. I am planning to have a callout in that lesson explaining the issue and how R < 4 and R > 4 will behave differently.
