### ISSUE TITLE
Suggestion: Command to read a data table from excel file in R

### ISSUE THREAD

**Issue by purvakulkarni7** [swcarpentry/r-novice-gapminder#647]
Use of excel files is quite popular when it comes to performing scientific research. 
Considering this, I would like to suggest adding, some instructions on reading excel files in the **Episode 4: Data Structures** [[https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html](https://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/index.html)] where `read.table` and `read.csv` has been briefly explained. 

The following bit of text and code might be useful:

**To read an excel file**
Install the `openxlsx` package
````
install.packages("openxlsx", dependencies = TRUE)
````
**Usage**
````
library("openxlsx")
my_df <- read.xlsx("BigExcelFile.xlsx", sheet = 1, startRow = 2, colNames = TRUE)
````

**Comment by jcoliver** [comment]
Thanks for the suggestion, @purvakulkarni7 . We are trying to minimize the use of third-party packages for our novice audience. In keeping with efforts to store data in open, easily computable formats (such as text files), we will stick with `read.csv` and `read.table` for now.
