### ISSUE TITLE
Change references of OS X to macOS?

### ISSUE THREAD

**Issue by mulderc** [swcarpentry/r-novice-gapminder#648]
Seeing macOS being called OS X which can be confusing for people not familiar with the pre-2016 name of macOS. Should this be updated to reflect current naming?

https://github.com/swcarpentry/r-novice-gapminder/blob/708ab907306ea764d2e279bb6048c6d9913523c3/_episodes_rmd/01-rstudio-intro.Rmd#L106

**Comment by jcoliver** [comment]
Great point, @mulderc . A review of materials for all references to OS X (OSX, Mac OS X, other permutations) would be warranted. Checking with the Carpentries Curriculum Committee would also be a good idea.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
