### ISSUE TITLE
Comments to improve the lesson "Producing Reports With knitr"

### ISSUE THREAD

**Issue by peranti** [swcarpentry/r-novice-gapminder#652]
I would like to share the following comments on the contents of the lesson [Producing Reports With knitr](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html): 

- Beginners might appreciate learning the chunk options `fig.pos` and `fig.cap` besides `fig.height` and `fig.width` in the output. 
- I feel this statement needs a bit more clarification: `Often there will be particular options that you’ll want to use repeatedly; for this, you can set _global_ chunk options, like so:` Once the global options are set, the changes apply to every following chunk unless the new defaults are overwritten in individual chunk headers. Isn't it? 
- How about mentioning the parameter for `chunk_name` as `label = chunk_name`? This would enable the readers in knowing the parameter `label` receiving the value `chunk_name`.

Hope these comments would be helpful in improving the content!

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by jcoliver** [comment]
Thank you, @peranti . These could indeed be useful revisions to the knitr lesson.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
