### ISSUE TITLE
RFC: Migration to R 4.0

### ISSUE THREAD

**Issue by zkamvar** [swcarpentry/r-novice-gapminder#655]
During the June Maintainer meeting, we asked for comments and experiences with the migration to R 4.0 so that we could create guidance for maintainers and instructors. We have drafted a short blog post (https://github.com/carpentries/carpentries.org/pull/830) to be released next week (2020-08-03) that describes our recommendations for migration. You can find a [preview of the blog post here](https://deploy-preview-830--stupefied-einstein-5bde90.netlify.app/blog/2020/08/r-4-migration/). **Please look over the blog posts and make comments by 2020-07-30 so that we can incoroporate any changes before the post goes live.**

To help identify the differences between R 3.6 and R 4.0, I have run this lesson in both versions and [posted the results](https://github.com/zkamvar/postmaul/blob/master/analysis.md#lesson-r-novice-gapminder) that show the differences in output chunks and entire markdown files.

**Comment by jcoliver** [comment]
Closing this, as we are using #633 for the transition to R 4.0.
