### ISSUE TITLE
Minor text corrections for Writing Good Software episode

### ISSUE THREAD

**Issue by mhog025** [swcarpentry/r-novice-gapminder#656]
Hi there,

I've been working through the materials as part of instructor training and just have a few suggestions for edits and corrections for the Writing Good Software episode text (https://swcarpentry.github.io/r-novice-gapminder/16-wrap-up/index.html).

**Structure your project folder**: First paragraph

'This' in place of 'It':

> ~~It~~This can be done completely manually, or with the help of RStudio’s `New Project` functionality, or a designated package, such as `ProjectTemplate`.

**Make code readable**: First paragraph

The following reads awkwardly:

> You want someone else to be able to pick up your code and be able to understand what it does: more often than not this someone will be you 6 months down the line, who will otherwise be cursing past-self.

Suggest either:

> You want someone else to be able to pick up your code and be able to understand what it does: more often than not, this someone will be yourself, 6 months down the line.

Or:

> You want someone else to be able to pick up your code and be able to understand what it does: more often than not, this someone will be yourself, 6 months down the line, and who will otherwise be cursing their past-self.

**Documentation: tell us what and why, not how**: Third sentence

Modify placement of 'that' at the end of the sentence:

> Try to also include comments that tell you *why* you’re solving a problem, and *what* that problem ~~that~~ is. 

**Break down problem into bite size pieces**: header

Correct header from:

> Break down problem into bite size pieces

to:

> Break down the problem into bite-size pieces

Cheers,
Mike.

**Comment by jcoliver** [comment]
Thanks, @mhog025 !

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
