### ISSUE TITLE
Define fuzzy search in Seeking Help episode 

### ISSUE THREAD

**Issue by ltcguthrie** [swcarpentry/r-novice-gapminder#657]
Hi,
I focused on the R novice lesson as a part of the instructor training and I have a suggestion for the Seeking Help episode text (http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html).

I think that it would be helpful to define fuzzy and provide an example of seeking help with a partial match in the section on doing a fuzzy search.

Original text:

If you’re not sure what package a function is in, or how it’s specifically spelled you can do a fuzzy search:

```
??function_name
```

Suggested text to add:
  
> A fuzzy search is when you search for an approximate string match. For example, you may remember that the function to set your working directory includes set.
> You can do a fuzzy search: 

```
??set
```

**Comment by jcoliver** [comment]
Thanks for the suggestion, @ltcguthrie . Want to submit a pull request with this suggestion?

**Comment by jcoliver** [comment]
Didn't mean to close XD

**Comment by jcoliver** [comment]
Addressed by #679
