### ISSUE TITLE
duplicate library carpentry under _includes, swc missing 

### ISSUE THREAD

**Issue by kristi-sara** [swcarpentry/r-novice-gapminder#658]
Was Looking for r-novice-gapminder  schedule/syllabus under _includes, and rather than 'swc' it says 'sc' and contains duplicate material from library carpentry (it looks like same commits from the lc part of the _includes). 

Unless I am missing something, looks like a typo and copy error

**Comment by fmichonneau** [comment]
Hi @kristi-sara!

The files you are mentioning are related to the workshop website templates (as in this [repository](https://github.com/carpentries/workshop-template). For historical reasons, the files needed by the workshop website template are also included in the lesson templates. However, they are not being used in lesson repositories (like this one). This inconsistency has been fixed on the workshop template repository and can be ignored here. I'm going to close the issue, but feel free to re-open if you think I'm missing something.
