### ISSUE TITLE
Data types lesson 4

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-gapminder#66]
http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1.html
R has 5 basic atomic types (meaning they can’t be broken down into anything smaller):

(there is a problem with indentation and how the atomic types are counted)
It looks like this:

    logical (e.g., TRUE, FALSE)
    numeric
    integer (e.g, 2L, as.integer(3))
    double (i.e. decimal) (e.g, -24.57, 2.0, pi)
    complex (i.e. complex numbers) (e.g, 1 + 0i, 1 + 4i)
    text (called “character” in R) (e.g, "a", "swc", 'This is a cat')

But should look more like this: 

    logical (e.g., TRUE, FALSE)
    numeric
        integer (e.g, 2L, as.integer(3))
        double (i.e. decimal) (e.g, -24.57, 2.0, pi)
    complex (i.e. complex numbers) (e.g, 1 + 0i, 1 + 4i)
    text (called "character" in R) (e.g, "a", "swc", 'This is a cat')

**Comment by naupaka** [comment]
Sure, I agree. Can you open a pull request with that fixed?

**Comment by orchid00** [comment]
Hi @naupaka, the problem needs to be fixed from the CSS (styles file) the indentation seems fine in the .md file

**Comment by naupaka** [comment]
My guess is that it's an issue with the pandoc rendering of markdown, which requires 4 spaces for an indent instead of the 2 which GitHub markdown uses.

**Comment by naupaka** [comment]
Yup, that was it. Fixed by 28cb09463
