### ISSUE TITLE
Including a section on how to change column names of data frame in this lesson

### ISSUE THREAD

**Issue by SaranjeetKaur** [swcarpentry/r-novice-gapminder#660]
(This issue is specifically created as my contribution for the instructor training checkout process.)
Can we have a section in this lesson which will explain the ways in which one can change the names of the columns of a data frame in R?

**Comment by jcoliver** [comment]
Thanks, @SaranjeetKaur . Is there a particular place in an episode where this would be most appropriate? It also might be something to consider for the dplyr lesson (i.e. `rename(new name = old name)`).

**Comment by stefpiatek** [comment]
I'd be happy to draft out a PR for this if you'd like?

**Comment by jcoliver** [comment]
That would be great, @stefpiatek .
