### ISSUE TITLE
instructions update: control flow in the R for reproducible scientific analysis lesson

### ISSUE THREAD

**Issue by Ksurg** [swcarpentry/r-novice-gapminder#666]
Hi, 

In the lesson section on control flow 
http://swcarpentry.github.io/r-novice-gapminder/07-control-flow/index.html

the following bold text should be updated:
R accepts both if() and **ifelse()** statements structured as outlined above, but also statements using R’s built-in ifelse() function. This function accepts both singular and vector inputs and is structured as follows:

This should be updated to say "else if () statements, as ifelse is not outlined above, but is explained in the next section.

**Comment by jcoliver** [comment]
Thanks, @Ksurg . Good point. Want to submit a PR with this change?

**Comment by Ksurg** [comment]
Hi Jeff,

Yes, but I am new to this process: do you have a link handy for submitting pull requests? (I can have a hunt around if you don’t)

Kind regards,

Kari Clifford

**Comment by jcoliver** [comment]
The contributing page has a section on submitting pull requests: [https://github.com/swcarpentry/r-novice-gapminder/blob/master/CONTRIBUTING.md#submitting-pull-requests](https://github.com/swcarpentry/r-novice-gapminder/blob/master/CONTRIBUTING.md#submitting-pull-requests).

**Comment by Ksurg** [comment]
Cheers 😊

**Comment by jcoliver** [comment]
Addressed by #667
