### ISSUE TITLE
Update _config.yml so license link works

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#669]
The assignment of `cc_by_human` is included in bin/boilerplate/_config.yml, but not _config.yml. I think this is what causes the license links to be broken in the footer of rendered lesson pages.

In _config.yml:
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"

In bin/boilerplate/_config.yml:
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
**cc_by_human: "https://creativecommons.org/licenses/by/4.0/"**

@fmichonneau is this something that needs fixing outside of this repository?

**Comment by fmichonneau** [comment]
This is a difficulty with our current setup. For the files included in the boilerplate folder, when they change in the styles repository, they need to be changed manually in the lessons. There is no easy way around this issue at the time. So for this particular issue, you need to copy the line manually from the _config.yml file in the boilerplate folder into your repository version of the _config.yml file. Thanks for spotting this issue.

**Comment by jcoliver** [comment]
Will do. Thanks for the info, @fmichonneau .

**Comment by jcoliver** [comment]
Addressed (for now) by #670
