### ISSUE TITLE
Avoid the use of "Dataframe"

### ISSUE THREAD

**Issue by PabRod** [swcarpentry/r-novice-gapminder#673]
## Problem
Currently, both _"Data frame"_ and _"Dataframe"_ coexist in the text. This is particularly noticeable in [the schedule](http://swcarpentry.github.io/r-novice-gapminder/), where lesson 5 uses _"Data frame"_ and sections 13, 14 use _"Dataframe"_.

Due to the importance of Data frames in R, I suggest being consistent with its naming.

## Solution
According to the [R documentation](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/data.frame), the correct form is _"Data frame"_.

## Related issues
#140 #145

**Comment by jcoliver** [comment]
Thanks, @PabRod . This is a good point - want to submit a PR for any of the episodes mentioned (5, 13, 14)?

**Comment by PabRod** [comment]
Woops! The build [failed](https://github.com/swcarpentry/r-novice-gapminder/pull/675/checks?check_run_id=1478905326) in the remote server. This the first time I work with `.Rmd` lesson files.

I may need some help, @jcoliver.

**Comment by tobyhodges** [comment]
Those errors aren't related to your changes, @PabRod [Looking at the build log](https://github.com/swcarpentry/r-novice-gapminder/pull/675/checks?check_run_id=1478905326), it seems to be mostly issues with syntax highlighting on code blocks elsewhere in the lesson. It shouldn't stop the pages from building after merge.
