### ISSUE TITLE
Rename (or split) episode "Exploring Data Frames"

### ISSUE THREAD

**Issue by PabRod** [swcarpentry/r-novice-gapminder#674]
## Problem
Most of the episode [Exploring Data Frames](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html) actually deals with **manipulating** data frames rather than **exploring** them. This is clear already from the episode's overview, where only 1 of the 6 objectives is related to exploration. 

## Solution
Please consider:

- Renaming the episode to "Manipulating Data Frames".
or
- Splitting the episode in two episodes: "manipulating" and "exploring".

**Comment by jcoliver** [comment]
Thanks for the input, @PabRod . The term "Exploring" is used _sensu lato_, where learners explore functionality of data frames.
