### ISSUE TITLE
Present an alternative upload function

### ISSUE THREAD

**Issue by IanniMuliterno** [swcarpentry/r-novice-gapminder#677]
Hello,

 I have a suggestion about the function used to upload the file. "read.csv" works well, but it would be good to present "fread", because all controls such as sep, colClasses and nrows are automatically detected. The function also deals large data well and has other advantages the user may need as they become advanced R users.

 Here is the link to a R-bloggers post cointaining a nice comparison of performance between fread and similar functions in R.
https://www.r-bloggers.com/2019/06/how-data-tables-fread-can-save-you-a-lot-of-time-and-memory-and-take-input-from-shell-commands/

**Comment by jcoliver** [comment]
Thanks, @IanniMuliterno . I agree that `fread` is quite useful for large data sets. For the purposes of this introduction to the R language, keeping it simple is key. I could see `fread` being introduced in an intermediate level lesson, especially one which explicitly deals with large data sets.
