### ISSUE TITLE
Misplaced output in Episode 5 - Exploring Dataframes

### ISSUE THREAD

**Issue by icrichmond** [swcarpentry/r-novice-gapminder#680]
Hi there, 

I am going through this lesson preparing for my teaching demo to become a Carpentries instructor. I am fairly certain that the warning message output in Episode 5 ([http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html](http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html)) is misplaced.

At the bottom of the first section "Adding Columns and Rows in Data Frames", the last thing requested is to add a new row: 
``` r
newRow <- list("tortoiseshell", 3.3, TRUE, 9)
cats <- rbind(cats, newRow)
cats
``` 

This command ultimately ends with a warning message and the added row having an NA value in the first column. However, the output listed here shows a complete table. Further, the warning message is printed further below, in the "Factors" section. I believe this is a mistake. The warning message is solved in the Factors section and should have the perfect table output shown at the bottom of the above section. 

I hope my message here is clear! Please let me know if you have any questions. Thanks for all your hard work on these lessons!

**Comment by jcoliver** [comment]
Thanks for the feedback, @icrichmond . This is most likely caused by different behavior of `read.csv` between R version <4.0 and more recent versions. We are currently working on a fix; you can find more information about this in #633 .
