### ISSUE TITLE
Lesson contribution – instructor checkout

### ISSUE THREAD

**Issue by Me6me82** [swcarpentry/r-novice-gapminder#682]
suggestion for The R for Reproducible Scientific Analysis  Lesson 
- **Introduction to R and RStudio**
good to introduce another source for R Packages like Bioconductor and how to install Packages using BiocManager

- **Seeking Help**
It will help to add a link to RStudio Cheatsheets : https://rstudio.com/resources/cheatsheets/

**Comment by jcoliver** [comment]
Thanks, @Me6me82 . The alternative package management is a bit advanced for the target audience of these lessons, but the cheetsheet link would be a nice addition.
