### ISSUE TITLE
make preview fails

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#7]
Looks like one of the python scripts isn't happy:
```
pandoc -s -t html \
	--template=_layouts/page \
	--filter=tools/filters/blockquote2div.py \
	--filter=tools/filters/id4glossary.py \
	-Vheader="$(cat _includes/header.html)" -Vbanner="$(cat _includes/banner.html)" -Vfooter="$(cat _includes/footer.html)" -Vjavascript="$(cat _includes/javascript.html)" \
	-o 01-rstudio-intro.html 01-rstudio-intro.md
pandoc: Error running filter tools/filters/blockquote2div.py
fd:4: hPutBuf: resource vanished (Broken pipe)
make: *** [01-rstudio-intro.html] Error 83
```

**Comment by tomwright01** [comment]
Works fine for me.
$git pull swc gh-pages
$make preview

**Comment by naupaka** [comment]
Which OS are you on? Which version of python?

**Comment by karawoo** [comment]
Works for me on Ubuntu 14.04 with Python 3.4.

**Comment by naupaka** [comment]
Here the prob: 
```
python blockquote2div.py                                                                    gh-pages
Traceback (most recent call last):
  File "blockquote2div.py", line 47, in <module>
    import pandocfilters as pf
ImportError: No module named pandocfilters
```

Simple fix: `pip install pandocfilters`

Then everything works.

**Comment by naupaka** [comment]
OS X 10.10.3, btw. Worth adding a note on this somewhere?

**Comment by karawoo** [comment]
Yeah I think so. Now that I think of it I've definitely run into this before.

**Comment by jdblischak** [comment]
This error is documented in the FAQ: https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/FAQ.md#debugging

**Comment by naupaka** [comment]
Excellent, thanks.

**Comment by abought** [comment]
In theory, `pandocfilters` should be installed so long as you run `pip install -r requirements.txt` with the files from lesson-template... it's definitely worth emphasizing this prerequisite. 
https://github.com/swcarpentry/lesson-template/blob/gh-pages/requirements.txt

It's [mentioned](https://github.com/swcarpentry/lesson-example) in lesson-example, if that helps...?

**Comment by gvwilson** [comment]
Can we catch an exception somewhere in our code if pandocfilters *isn't* 
installed, and print a link to the instructions?
