### ISSUE TITLE
Include tinytex in hint for pdf output in knitr lesson?

### ISSUE THREAD

**Issue by hfshr** [swcarpentry/r-novice-gapminder#701]
Hi!

Just a small suggestion as part of the checkout process... At the end of the [producing reports with knitr](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html) lesson, there is a tip pointing to some TeX installers that are needed for pdf output. I'm wondering if `tinytex` could maybe be mentioned here to provide an R-based solution to installing tex and any required packages automatically? The documentation is great (https://yihui.org/tinytex/) and might make the process of working with pdfs more straightforward for beginners?

**Comment by jcoliver** [comment]
Thanks for the suggestion, @hfshr . Want to submit a PR?

**Comment by hfshr** [comment]
Hi @jcoliver, great! Yes happy to submit a PR :+1:

**Comment by jcoliver** [comment]
Addressed by #704 .
