### ISSUE TITLE
Use of stringsAsFactors/factors and wording re: factor/vector columns

### ISSUE THREAD

**Issue by Alanocallaghan** [swcarpentry/r-novice-gapminder#705]
In reviewing this lesson I've noticed some oddities and some things that I consider incorrect.

First, stringsAsFactors is used a lot in code examples, but never explained. It's also set differently in different sections with no explanation why.

eg, here: https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L61
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L145
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L186
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/05-data-structures-part2.Rmd#L211-L214
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/05-data-structures-part2.Rmd#L227-L230
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/05-data-structures-part2.Rmd#L243

or if I `grep -r stringsAsFactors`:
```
14-tidyr.Rmd:gapminder <- read.csv("data/gapminder_data.csv", header = TRUE, stringsAsFactors = FALSE)
14-tidyr.Rmd:gap_wide <- read.csv("data/gapminder_wide.csv", header = TRUE, stringsAsFactors = FALSE)
14-tidyr.Rmd:country columns to be factors, so we use the stringsAsFactors argument for
14-tidyr.Rmd:gap_wide <- read.csv("data/gapminder_wide.csv", stringsAsFactors = FALSE)
05-data-structures-part2.Rmd:cats <- read.csv("data/feline-data.csv", stringsAsFactors = TRUE)
05-data-structures-part2.Rmd:> > 3. `as.numeric(human_age)` yields `1 2 3 4 4` because factors are stored as integers (here, 1:4), each of which is associated with a label (here, 28, 35, 56, and 63). Converting the factor to a numeric vector gives us the underlying integers, not the labels. If we want the original numbers, we need to convert `human_age` to a character vector (using `as.character(human_age)`) and then to a numeric vector (why does this work?). This comes up in real life when we accidentally include a character somewhere in a column of a .csv file supposed to only contain numbers, and forget to set `stringsAsFactors=FALSE` when we read in the data.
05-data-structures-part2.Rmd:>                  stringsAsFactors = FALSE)
05-data-structures-part2.Rmd:> >                  stringsAsFactors = FALSE)
05-data-structures-part2.Rmd:gapminder <- read.csv("data/gapminder_data.csv", stringsAsFactors = TRUE)
05-data-structures-part2.Rmd:> gapminder <- read.csv("data/gapminder_data.csv", stringsAsFactors = TRUE)
05-data-structures-part2.Rmd:> gapminder <- read.csv("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv", stringsAsFactors = TRUE)
05-data-structures-part2.Rmd:> > gapminder <- read.csv(file = "data/gapminder_data.csv", stringsAsFactors = TRUE)
04-data-structures-part1.Rmd:cats <- read.csv(file = "data/feline-data.csv", stringsAsFactors = TRUE)
04-data-structures-part1.Rmd:cats <- read.csv(file="data/feline-data_v2.csv", stringsAsFactors = TRUE)
04-data-structures-part1.Rmd:cats <- read.csv(file="data/feline-data.csv", stringsAsFactors = TRUE)
04-data-structures-part1.Rmd:> > cats <- read.csv(file="data/feline-data.csv", stringsAsFactors=FALSE)
```

I think this is not ideal, since this option can change how, and the default is, since R 4.0.0, now `FALSE`.
see: https://twitter.com/strnr/status/1242795235266224128
This means the workshop is teaching people to load data in a way which is not the default.
I think setting it makes the lesson more portable (eg, before R 4.0.0) but it should be consistent & explained.

Factors are also said to be "necessary" here: 
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L420-L424
in my experience they often aren't outside of relatively niche cases, and have the capacity to introduce very tricky bugs in novice code. Or, at least, they did that for me. Since `options("stringsAsFactors")` is now `FALSE` by default, this has a pretty good likelihood of introducing bug if users forget this option when reading in data.

https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L156-L164
> a data.frame is really a list of vectors and factors

This isn't correct. A data.frame column can be a list of arbitrary objects.
```{r}
df <- data.frame(x = I(list(1, "2", 3)))
df$x
# [[1]]
# [1] 1
# 
# [[2]]
# [1] "2"
# 
# [[3]]
# [1] 3
```

Also here:
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L237-L238

R isn't particularly opinionated about what can be a column of a dataframe, other than that it has to be a vector, factor, or list of length `nrow(dataframe)`. Vectors have to be of the same atomic type, but this is independent of the dataframe class, and lists can be of arbitrary objects (even S4 or other class systems if you're feeling very adventurous). This wording seems to imply some rigorous type checking when calling `data.frame()` that doesn't really happen.

**Comment by jcoliver** [comment]
Thanks for these suggestions, @Alanocallaghan . We are still working on the transition to R 4.0, where default `stringsAsFactors` value was changed in `read.csv()`. The current episodes are designed to be compatible with R < 4.0, which some attendees to Software Carpentry workshops may be using, but we agree there are opportunities for improvement. More discussions can be found in #633 .

**Comment by Alanocallaghan** [comment]
I don't really get why the default changing affects any of the comments here but I'll take your word for it

**Comment by jcoliver** [comment]
From OP: "stringsAsFactors is used a lot in code examples, but never explained. It's also set differently in different sections with no explanation why."

The current use of explicit values for `stringsAsFactors` in `read.csv()` ensures consistent behavior of `read.csv()` across versions of R. It was added as a temporary fix due to (1) the change in R 4.0 and (2) the reliance on a default `stringsAsFactors = TRUE` to purposefully introduce warnings in order to explain the behavior of factors. You can see the changes from previous versions (which, for the most part did not specify the value for `stringsAsFactors`) in #684 . If `stringsAsFactors` is _not_ specified, then for any version of R >= 4.0, the lesson text does not match the actual behavior of R: when adding a new row of data with a new coat color, no warning is thrown because the `coat` column is `character` not `factor`. We also do not view the current use as ideal, but it requires considerable overhaul, especially to Episode 5, which relies on the warning about invalid factor levels to discuss factors. This is a work in progress. :)

However, I agree that the additional points about data types in data.frames warrant additional consideration. Would you create separate issues for each of the points you feel still need to be addressed? Atomizing issues makes it easier for us to track and others to contribute.

**Comment by Alanocallaghan** [comment]
Fair enough, #711.

My primary point here is not "don't set stringsAsFactors" but "don't set an argument to different things in different places in the lesson without explaining it"
>  I think setting it makes the lesson more portable (eg, before R 4.0.0) but it should be consistent & explained.

I also still think that wording about factors being essential etc is probably not good to include as reflected by the decision to change the default.

I can see that changing the lesson to get around this altogether is a big overhaul, but in the interim I see this as a) very confusing material and b) potentially encouraging learners to adopt odd/dangerous practices. At the least I think it should be explained and factors really shouldn't be emphasised as being necessary.*

*I am willing to do it, I'm not simply demanding that you make a bunch of edits

**Comment by jcoliver** [comment]
And if you're keen to help out with the revision of Episodes 4 & 5, dealing with `read.csv()` behavior, please be sure to reach out to @naupaka , who is leading the effort.
