### ISSUE TITLE
Minor typo in lesson 01 Intro to R and RStudio

### ISSUE THREAD

**Issue by northernjamie** [swcarpentry/r-novice-gapminder#709]
Line 63 of this .Rmd file: https://github.com/swcarpentry/r-novice-gapminder/blob/main/_episodes_rmd/01-rstudio-intro.Rmd contains the line `It provides a built in editor`, which should be `It provides a built-in editor` (note the hyphen).

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by jcoliver** [comment]
Thanks, @northernjamie . Want to submit a pull request to fix this?
