### ISSUE TITLE
dataframe discussion is not really correct

### ISSUE THREAD

**Issue by Alanocallaghan** [swcarpentry/r-novice-gapminder#711]
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L156-L164
> a data.frame is really a list of vectors and factors

This isn't correct. A data.frame column can be a list of arbitrary objects.
```{r}
df <- data.frame(x = I(list(1, "2", 3)))
df$x
# [[1]]
# [1] 1
# 
# [[2]]
# [1] "2"
# 
# [[3]]
# [1] 3
```

Also here:
https://github.com/swcarpentry/r-novice-gapminder/blob/2bc6a654f272359651dfaf28b464c9b2ae30c635/_episodes_rmd/04-data-structures-part1.Rmd#L237-L238

R isn't particularly opinionated about what can be a column of a dataframe, other than that it has to be a vector, factor, or list of length `nrow(dataframe)`. Vectors have to be of the same atomic type, but this is independent of the dataframe class, and lists can be of arbitrary objects (even S4 or other class systems if you're feeling very adventurous). This wording seems to imply some rigorous type checking when calling `data.frame()` that doesn't really happen.

**Comment by jcoliver** [comment]
Thanks, @Alanocallaghan !

**Comment by shu251** [comment]
I have a suggested re-write of this to help offer an explanation of what has happened and to define data frames in another way:

> On Lines 152 to 164:

```
```{r}
cats$weight + 2
```

What happened here?
The cats data we are working with is something called a _data frame_ and data frames are one of the most common and versatile types of _data structures_ we will work with in R. In this example, the columns that make up a data frame cannot be composed of different data types. In this case, R does not read everything in the data frame as a double, therefore the whole column data type changes to something that is suitable for everything in the column.

When R reads a csv file, it reads it in as a data frame. Thus, when we loaded the cats csv file, ```cats``` is a data frame. We can check this by using the function ```class()```.

```{r}
class(cats)
```

_Data frames_ are composed of rows and columns, where each column has the same number of rows. Different columns in a data frame can be made up of different data types (this is what makes them versatile), but everything in a given column needs to be the same type (e.g., vector, factor, vs list).
```

**Comment by jcoliver** [comment]
Thanks, @shu251 . This is a nice addition, want to submit a PR?

**Comment by shu251** [comment]
https://github.com/swcarpentry/r-novice-gapminder/pull/718

**Comment by jcoliver** [comment]
This clarification provided in #718 closure, as the description does appear correct. While a column can be a `list` of arbitrarily-typed elements, every cell within a column of type `list` is also of type `list`:

```
df <- data.frame(a = I(list(one = c("c", "d"), 
                            two = 2, 
                            three = TRUE)))
# The column is of type list
typeof(df$a)
# [1] "list"
# Individual elements of the data frame are also lists
typeof(df$a[1])
# [1] "list"
```

Lest we attempt diving into vagaries of `[[` vs `[`, I think we can consider this addressed.
