### ISSUE TITLE
13-dplyr: Header needs correction

### ISSUE THREAD

**Issue by abanihas** [swcarpentry/r-novice-gapminder#712]
Link: https://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html

Please change the header "Using group_by() and summarize()" to "Using group_by()" as "summarize()" is not used in this section. The following section covers "summarize()" and has the appropriate heading.

**Comment by jcoliver** [comment]
Thanks @abanihas . Want to submit a PR?

**Comment by jcoliver** [comment]
Addressed by #715 .
