### ISSUE TITLE
Simplify downloading of gapminder-FiveYearData.csv

### ISSUE THREAD

**Issue by BernhardKonrad** [swcarpentry/r-novice-gapminder#72]
We currently ask students to download the zip file for the raw data:
https://github.com/swcarpentry/r-novice-gapminder/blame/gh-pages/02-project-intro.md#L159

Unzipping is an unnecessary pain here, it may be easier to download the `raw` version directly with a "right click -> save as" using this direct link
https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv

**Comment by naupaka** [comment]
My sense is that generally students don't have much trouble with unzipping files -- and in other instances of other lessons, they have to download zipped files because there are many that they need to work with. Why not just stay consistent? Seems fine to me either way in this particular case, though.

**Comment by BernhardKonrad** [comment]
I'm just reporting from a debriefing session where students did have problems with unzipping of this particular file.

I don't think consistency is more valuable than the simplest solution, especially when it's that much simpler. But yeah, it's not a big deal either way.

**Comment by naupaka** [comment]
Ah - my misunderstanding. I thought the link above was just to a zip of the data file itself, but the instructions have students download a zip of the whole repo and then navigate into the data folder to get it out. I usually give students the data with a dropbox or droplr link, your solution works well too. Submit a quick PR?

**Comment by BernhardKonrad** [comment]
Please review #74

**Comment by naupaka** [comment]
Closed by #74
