### ISSUE TITLE
Remove dot from facet_grid() function call?

### ISSUE THREAD

**Issue by worcjamessmith** [swcarpentry/r-novice-gapminder#721]
This issue is about the writing data episode (https://swcarpentry.github.io/r-novice-gapminder/11-writing-data/index.html) 

Challenge 1 has this code `p + facet_grid(. ~continent)`. However, `p + facet_grid(~continent)` is sufficient and doesn't require any further explanation beyond what has been used in previous episodes when introducing ggplot (i.e. of the dot). Possibly better to use the simpler option?

**Comment by jcoliver** [comment]
Good point, @worcjamessmith, especially since episode 14 (dplyr) also skips the use of the dot. Want to submit a PR?

**Comment by jcoliver** [comment]
Addressed by #722
