### ISSUE TITLE
13-dplyr: with ggplot2 "here is the code we used". did we?

### ISSUE THREAD

**Issue by NadineBestard** [swcarpentry/r-novice-gapminder#723]
In the lesson 13, dplyr. in the "Combining dplyr and ggplot2" section there is an example code of a ggplot2 with the countries that start with A and Z. It says "Here is the code we used  [in the plotting leson] (with some extra comments)". However, I do not see this plot in the ggplot2 lesson. 

Is this from an autdated version? I guess it would be good to update this lesson too if this is the case, so there is no time lost at this stage explaining the "previous" code.

**Comment by jcoliver** [comment]
Good catch, @NadineBestard . This does look like a relic from earlier versions. It may be best to update the corresponding portion of the dplyr lesosn with the subsetting to "Americas" as seen in the ggplot lesson under [Multi-panel figures](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html#multi-panel-figures).

**Comment by jcoliver** [comment]
Addressed by #727
