### ISSUE TITLE
Introduce the geom_line() function first, then add the 'by' aesthetic afterwards

### ISSUE THREAD

**Issue by K-C-Martin** [swcarpentry/r-novice-gapminder#742]
Teaching ggplot2 (live coding) for my Instructor demo, I found it a little awkward to demonstrate the difference between geom_point and geom_line while having to simultaneously add in the 'by' aesthetic - I found it smoother to first switch from geom_point to geom_line, then introduce the 'by' aesthetic as a second step.

See https://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html#layers

**Comment by jcoliver** [comment]
Addressed in #743
