### ISSUE TITLE
Updating objective

### ISSUE THREAD

**Issue by Penny-Han** [swcarpentry/r-novice-gapminder#754]
As part of my checkout process, I would like to make contribution to "R for Reproducible Scientific Analysis"

The final objective in "Creating Publication-Quality Graphics with ggplot2" says "To save a plot created with ggplot to disk"

The terminology seems out of date and no longer in line with the lesson itself.

It maybe more appropriate to update it to something such as "To export a plot created with ggplot"

Thanks

**Comment by jcoliver** [comment]
Thanks, @Penny-Han . While the term "export" _is_ used in the heading for the section, the body of this section still uses "save" terminology. For now I think we can stick with "save" in the learning objectives, as that term may be more accessible for novice learners than "export."
