### ISSUE TITLE
Suggestion: 02-project-intro.Rmd

### ISSUE THREAD

**Issue by ahfitzpa** [swcarpentry/r-novice-gapminder#767]
<Include ProjectTemplate package>
<summary><strong>ProjectTemplate is relevant in this episode</strong></summary>

The ProjectTemplate package in R is very useful and is introduced in 16-wrap-up.Rmd. However, in order to introduce to students to good software practices and increase their familiarity with how data should be stored it would be good to include it from the start of the lesson. Instead of student's having to manually set up data and fig folders as in later episodes, they would be created in this episode. What do you think?

**Comment by jcoliver** [comment]
Thanks for this, @ahfitzpa . ProjectTemplate can be useful, but for novices, we'd prefer to show how they can create folders without the need for additional libraries.
