### ISSUE TITLE
Remove tip about symlinking

### ISSUE THREAD

**Issue by mlell** [swcarpentry/r-novice-gapminder#768]
In Lesson 2 [they say](https://github.com/swcarpentry/r-novice-gapminder/blob/68b3c2ec6e981aa11e034aa6d9ba11937249ca1e/_episodes_rmd/02-project-intro.Rmd#L144-L157):

> ## Tip: avoiding duplication
> 
>  You may find yourself using data or analysis scripts across several projects. 
> Typically you want to avoid duplication to save space and avoid having to make updates to code in multiple places.
> 
> In this case, making “symbolic links”, which are essentially shortcuts to files somewhere else on a filesystem, can let you use existing code without having to move or copy it. Plus, any changes made to that code will only have to be made once.
> 
> On Linux and OS X you can use the `ln -s` command, and on Windows you can either create a shortcut or use the `mklink` command from the windows terminal.

I consider this a recipe for desaster and ask myself if you see it the same way:

1. Symbolic links are a complicated matter on Windows. They can only be created if you have the corresponding user capability (e.g. if you are admin) or if you use an elevated command prompt, which encourages bad security habits (admin user for non-admin tasks). Alternatively you can set your Windows 10 machine to debug mode. Moreover you [can delete all your files by deleting a symlink](https://superuser.com/a/306618) and you need [different commands on CMD and PowerShell to avoid that](https://superuser.com/a/595197).
2. Symbolic links to code and data are unnessecary, because you can just use the path in `source()`. It just obscurs where the information comes from with no benefit other than a few less characters in the code.
3. The suggested use case of "using data or analysis scripts across several projects" undermines the reproducibility of the project and will lead users inadvertently changing multiple unrelated projects with one code edit. R package version numbers and git submodules have been invented to prevent that. 

In my opinion, this tip will only introduce technical complexity and possibly hurt users while nothing is achieved that cannot alternatively been done by using the target path of the symlink in `read.table` or `source`. I think this tip should be deleted.

**Comment by jcoliver** [comment]
While Tips are generally optional, I agree that this has the potential to cause more headaches than it is worth.

**Comment by jcoliver** [comment]
Addressed by #772
