### ISSUE TITLE
Suggestion for Introduction to R and RStudio - Using R as a Calculator

### ISSUE THREAD

**Issue by ozlemtuncel** [swcarpentry/r-novice-gapminder#776]
The [Introduction to R and RStudio](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html) of [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/) introduces arithmetic calculations as the simplest way to use R. I think the section [Using R as a Calculator](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html#using-r-as-a-calculator) can be improved further: 

1. The section says: ``And R will print out the answer, with a preceding “[1]”. Don’t worry about this for now, we’ll explain that later. For now think of it as indicating output.'' It might be nice to give a hyperlink for the lesson that covers this information for more experienced students. 
2. Also, there is another section stating the following: "Like bash, if you type in an incomplete command, R will wait for...'". Since this is an introduction, it might be nice to refrain from using **bash** as an example here. Some R users might not be familiar with Unix Shell and how bash works. Instead, this section can be rephrased: "If there is an incomplete command, R will wait for you to complete your command. If you are familiar with Unix Shell's bash, you will realize that this is something common in both R and Unix Shell."

**Comment by jcoliver** [comment]
Thanks for these suggestions, @ozlemtuncel . I wonder, where _does_ the lesson explain the indexing :thinking: ? For the second point, users in a Software Carpentry workshop _should_ have already seen bash in use, given the structure of a SC workshop, so I don't think we should drop the mention of bash (it's an opportunity for reinforcement). Your suggestion with the language "For those who have used bash..." would be a nice addition (and Instructors would be able to adapt language as appropriate, if they are teaching in a workshop that did cover bash already).

**Comment by jcoliver** [comment]
I think the two things that could be addressed are:

1. Add a parenthetical note in the lesson indicating that indexing will be discussed in Subsetting Data (episode 6), with a link to the episode.
2. Update the language around bash as suggested in OP point 2, above.

**Comment by naupaka** [comment]
The second change is now merged via #779

**Comment by Drcars1** [comment]
The section says: And R will print out the answer, with a preceding “[1]”. Don’t worry about this for now, we’ll explain that later. I would remove the statement and replace it with "[1] is the index of the first element of the line being printed in the console. For more information on indexing vectors see the link www.thomasleeper.com/Rcourse/Tutorials/vectorindexing.html"

**Comment by naupaka** [comment]
Closed by #779 and #812
