### ISSUE TITLE
Lesson Contribution - Grammatical Update

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/r-novice-gapminder#784]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

I noticed an error in Episode 2 of the R for Reproducible Scientific Analysis as shown in the screenshot below.

Under the "?dput", you will see "Will dump the data you're working with into a format so that it can be copy and pasted by anyone else into their R session". The "copy" should be in the past tense like the "pasted".

It should read as follows: "Will dump the data you're working with into a format so that it can be copied and pasted by anyone else into their R session".

**Comment by matthieu-bruneaux** [comment]
Thank you @Talishask and @melibleq!
