### ISSUE TITLE
Functions Explained: Briefly Mention Packages

### ISSUE THREAD

**Issue by mjcasy** [swcarpentry/r-novice-gapminder#790]
Referring to episode : https://github.com/swcarpentry/r-novice-gapminder/blob/main/_episodes_rmd/10-functions.Rmd

Should we mention very briefly at the end that R packages are broadly just collections of functions like this?  E.g. in "Tip: Testing and documenting" after mentioning roxygen2

Packages are, in essence, bundles of functions with this formal documentation. Loading your own functions through `source("functions.R")` is equivalent to loading someone else's functions (or your own one day!) through `library("package")`.

**Comment by matthieu-bruneaux** [comment]
Thank you for your suggestion @mjcasy! This looks like a good idea to me.

Would you like to open a pull request with this change?

**Comment by matthieu-bruneaux** [comment]
This was addressed with PR #791. Thank you @mjcasy for your contribution!
