### ISSUE TITLE
Update episode 01 screenshots to show R version 4

### ISSUE THREAD

**Issue by ndporter** [swcarpentry/r-novice-gapminder#792]
The screenshots of the RStudio environment in [Episode 1](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html) show R version 3.5 but we want to encourage people to have version 4 installed.

**Comment by matthieu-bruneaux** [comment]
Thank you @ndporter, this is a good idea! It is good to keep the lesson material up-to-date and to encourage people to use a recent version of R. Would you like to submit a PR with an updated screenshot?

**Comment by ndporter** [comment]
PR is #794

**Comment by matthieu-bruneaux** [comment]
Thanks a lot for your contribution @ndporter! This was very helpful to keep the lesson up-to-date.

(Fixed with PR #794.)
