### ISSUE TITLE
Change of links to download RStudio Desktop IDE

### ISSUE THREAD

**Issue by edgardogv** [swcarpentry/r-novice-gapminder#795]
I would like to provide a suggestion that applies to these pages:

1. [https://swcarpentry.github.io/r-novice-gapminder/setup.html ](https://swcarpentry.github.io/r-novice-gapminder/setup.html)

2. https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html

The link for RStudio goes to the home page, which could be kind of a labyrinth for some people to locate the actual download link. So instead I would like to suggest to point the download link to the actual download site for the RStudio Desktop which is at https://www.rstudio.com/products/rstudio/download/#download 

I have used it successfully on my own teaching classes, hopefully it is useful for the Carpentries community as well. 

Now, one limitation of this approach is that RStudio is launching a new site on October 2022, re-branding as Posit, so maybe is better to wait until then to make the change. If this is something that makes sense, I can keep it on my radar and propose the change myself through GitHub at that point :)

**Comment by matthieu-bruneaux** [comment]
Thank you for your suggestion @edgardogv! Apologies for taking so long to reply to this issue, with the side effect that by now the RStudio re-branding to Posit has already taken place!

Would you like to submit a PR to address this?

**Comment by agudeloromero** [comment]
Hi @matthieu-bruneaux, I have updated those links as part of my Carpenters instructor certification.

**Comment by naupaka** [comment]
Should be addressed by PRs #810 and #811

**Comment by naupaka** [comment]
Waiting for those to pass automated checks

**Comment by naupaka** [comment]
Closed by #810 and #811
