### ISSUE TITLE
Typo or spelling mistake in Introduction to R and RStudio lesson

### ISSUE THREAD

**Issue by egeza** [swcarpentry/r-novice-gapminder#817]
Typo or spelling mistake in the lesson **Introduction to R and RStudio**, section [R scripts](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html#r-scripts), sentence <em> Files containg ... </em> should be <em> Files containing ... </em>

**Comment by matthieu-bruneaux** [comment]
Thank you for your contributions @egeza and @dawei-wang.
