### ISSUE TITLE
06-data-subsetting: order of operations 

### ISSUE THREAD

**Issue by davharris** [swcarpentry/r-novice-gapminder#84]
Currently, the callout on order of operations in 06-data-subsetting says:

> remember the order of operations. `:` is really a function, so what happens is it takes its first argument as -1, and second as 3...

I have two concerns with this:

1) "is really a function" doesn't seem germane: as I understand it, all operators are functions, but only some have lower precedence than the unary minus sign.

2) I don't think we can ask the students to "remember" order of operations here.  Even if the students knew where `:` fit in the hierarchy from high-precedence operators like `^` to low-precedence operators like `=`, they probably wouldn't anticipate that R gives very different precedences to unary and binary minus signs:

```
> -1:3      # Unary "minus" evaluated before `:`
[1] -1  0  1  2  3

> 0 - 1:3   # Binary "minus" evaluated after `:`
[1] -1 -2 -3
```

Given that we probably don't want a digression into [R's operator precedence](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html), I'm not sure what the solution is (other than recommending that students always use parentheses around arguments to `:` when math is happening nearby).  I thought I'd raise the issue to see what other SWC folk think.

**Comment by naupaka** [comment]
An alternative to get at the same issue is perhaps to simply ask people to try `-1:3` and compare the output to `-(1:3)` and explain the difference, which could go in the subsetting lesson or could go elsewhere.

**Comment by naupaka** [comment]
I am going to close this for now but am happy to reopen if someone wants to take a crack at a PR to improve how this is worded in the lessons.
