### ISSUE TITLE
Update "other great resources" 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/r-novice-gapminder#856]
The [Other Great Resources](https://swcarpentry.github.io/r-novice-gapminder/13-dplyr.html#other-great-resources) section of the dplyr episodes suggests some other great resources.

The link to “R for Data Science” goes to a version from 2017.  That itself notes that a 2023 version is available.  Consider using the 2023 version instead of the 2017 version.

**Comment by maneesha** [comment]
Note the same list appears at the bottom of the next episode, so the same comment would apply there as well.

**Comment by matthieu-bruneaux** [comment]
Thank you very much for spotting this problem @maneesha!

Since it was a simple fix I went ahead and prepared and merged a small PR myself. Both links should point to the latest version now.
