### ISSUE TITLE
Remove code that is not needed

### ISSUE THREAD

**Issue by SarithaKodikara** [swcarpentry/r-novice-gapminder#873]
### How could the content be improved?

In the episode exploring data frames (https://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2.html), renaming row names is unnecessary as R re-names them sequentially. So, in the section 'Append to a data frame', the following code snippet can be removed.

```
rownames(cats) <- NULL
cats
```

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2.html

**Comment by matthieu-bruneaux** [comment]
Thank you for noticing this @SarithaKodikara!

If you would like to submit a PR addressing this, I would be happy to review and merge it.

**Comment by matthieu-bruneaux** [comment]
Thank you for your PR and for helping us to keep the lesson up to date @SarithaKodikara!
