### ISSUE TITLE
Archival PRs

### ISSUE THREAD

**Issue by aammd** [swcarpentry/r-novice-gapminder#9]
Over in the git-novice lessons they use closed PRs to keep an archive of [workshop archives](https://github.com/swcarpentry/git-novice/pulls?q=is%3Apr+is%3Aclosed+label%3Aworkshop-archive).  To track how different people implement and change the lessons. Shall we try a similar approach here? 

I will try this approach for this week's SWC workshop at [Simon Fraser University](https://github.com/ttimbers/2015-04-30-SFU)

**Comment by sritchie73** [comment]
This sounds like a good idea to me.

**Comment by hdashnow** [comment]
+1

**Comment by sritchie73** [comment]
I'm just trying to work out the logistics of this now. I want the workshop website to point to the teaching materials used, however GitHub complains if I try to have two copies of the same repository. This will be problematic when running multiple workshops with successive iterations of the materials.

**Comment by aammd** [comment]
Couldn't we use different branches? my PR archive from [a recent workshop](https://github.com/swcarpentry/r-novice-gapminder/pull/43) was sent from a branch of my fork. The same fork also has branches which are current with `swcarpentry/r-novice-gapminder` so that I can help to maintain it.

**Comment by karawoo** [comment]
One downside is you don't get the nice rendered Jekyll site from any branch other than `gh-pages`. So if your workshop site is going to point to the materials, it'll have to point to the files on GitHub, which is slightly less convenient for learners to view. I also like having the lessons open in a browser on my iPad while I teach, so I need my changes to be in the `gh-pages` branch. What I've done in the past is make my changes to the `gh-pages` branch of my fork, teach the workshop, then create a new branch to contain my changes and then roll back `gh-pages` to where it was before the workshop. I can then share a link to the new branch with the learners after the workshop (but again they have to view the files on GitHub which is not ideal).

**Comment by aammd** [comment]
@karawoo I think that is a really good point! Perhaps we need to clarify this as an archive **for whom**. I was thinking of this as a way for people developing the lessons to see how they had been adapted and modified -- the really good content developed for any one workshop would be here, in this repo, not living on various forks. I was even thinking of how the archival PRs could contain comments from the debriefing that follows a workshop!  Thus an archive for *lesson writers/contributors*

However, it makes a lot of sense that an instructor would want to be able to point students to their own version of the material. And they should be able to generate the jekyll website if they choose. In this case, we are talking an archive for *learners*

I really like the workflow you outlined there, Kara. I'd like to elaborate that into a step-by-step guide that new instructors could follow, one that will allow instructors to:
* fork the lessons and modify
* serve their modifications on an Attractive Jekyll Website
* send a PR to the original repo to archive
* keep their modifications to show their students (bonus for keeping a nice jekyll website)
* continue to suggest modifications to original lesson from an up-to-date branch (as @sritchie73 points out)
* repeat the process next time they teach, while losing none of the previous steps.

I'm going to cc/ @daisieh (who invented this idea) & @gvwilson
