### ISSUE TITLE
Connecting RStudio with git

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/r-novice-gapminder#93]
I'm teaching a workshop where we've done unix and then git and now the r-novice-gapminder material. Tomorrow, I'd really like to show the students how to integrate git with RStudio. Today we started down this path, but when we went into the preferences, it was clear that OS X wouldn't show the /usr/bin/ folder which is where git is stored. Of course, I've long since forgotten how to do this. I'm not sure where it is stored with the Window's installer or how to point RStudio there. Any suggestions on what needs to be done? If anyone can help me, I'll happily file a pull request to include the instructions in `01-rstudio-intro.Rmd` once the workshop is over.

**Comment by pschloss** [comment]
Found it with some help here: https://twitter.com/PatSchloss/status/704811988078215168

In Mac OS X: Cmd-shift-G allows you to manually type in `/usr/bin/` and then you can select `git`. For Windows this does the trick: https://stat545-ubc.github.io/git03_rstudio-meet-git.html

Do you think it would be worth putting something into the instructor's guide or the setting up RStudio module to indicate this? The Mac OS X is a bigger issue than the windows because you can't see the /usr folder without this solution.

**Comment by naupaka** [comment]
For OS X, you can do `Shift + Command + G` to bring up a dialog that lets you go to any path, including `/usr/bin`. For Windows, [git bash](https://git-for-windows.github.io/) (I believe) puts `git.exe` in `C:\Program Files\Git\bin`

**Comment by naupaka** [comment]
Beat me to it @pschloss!

**Comment by naupaka** [comment]
I think it would be great to have this info in the RStudio set up module (and perhaps the instructor's guide as well). It's the sort of thing that comes up at every single workshop.

**Comment by pschloss** [comment]
Cool, I'll try to pull something together in the next few days for this as a PR. The other thing that would be good would be to mention an explicit workflow for getting RStudio to talk to github and the need for something like 

`git config --global credential.helper 'cache --timeout=10000000'`

to cache the password from the terminal so one can push/pull from within RStudio

**Comment by naupaka** [comment]
Excellent idea to extend timeout. Students always get frustrated by repeated password entering -- this is a nice quick fix. There's also a "Shell..." option in the "More" drop-down in the git tab in RStudio if you want to do the quick pref setting that way.

**Comment by naupaka** [comment]
Closed by #138
