### ISSUE TITLE
tidyr lesson - inconsistencies in dataframe atomic types

### ISSUE THREAD

**Issue by thesarahmeister** [swcarpentry/r-novice-gapminder#94]
When you load the gap_wide data from the .csv file in the repo, columns 37 and 38 get inputted as integers and columns 1 and 2 get inputted as factors. When you follow along in the lesson the gap_wide_new columns 1 and 2 are characters and columns 37 and 38 are numeric. This means the all.equal() function wont work until you make those changes in the gap_wide dataframe.

**Comment by tomwright01** [comment]
I think this is now resolved by #136. If not please let me know and we will open this issue again.
Thanks everyone.
